### ISSUE TITLE
Too many values to unpack (expected 5) with BayesSearchCV

### ISSUE THREAD

**Issue by snv6fe** [scikit-optimize/scikit-optimize#1006]
Hey guys,

I was trying the BayesSearchCV function and encountered the error: Too many values to unpack (expected 5) 
I even tried the sample example from the documentation linked below and still returned the same error to me.

Any ideas about the reason?

Thanks in advance.

![Screenshot 2021-02-23 at 17 06 46](https://user-images.githubusercontent.com/79515806/108871638-a3c78300-75f9-11eb-914a-bc78ff758162.png)
https://scikit-optimize.github.io/stable/auto_examples/sklearn-gridsearchcv-replacement.html#sphx-glr-auto-examples-sklearn-gridsearchcv-replacement-py

**Comment by apethani21** [comment]
I am also getting the same error, using version 0.8.1 and Python 3.7.10.

**Comment by leehanchung** [comment]
> 
> 
> I am still having this issue, are there solutions?

Check your scikit-learn version. Current version of BayesSearchCV only works with `scikit-learn==0.23.2`
