### ISSUE TITLE
How does the uniform generator work？

### ISSUE THREAD

**Issue by strugglepanda** [scikit-optimize/scikit-optimize#1015]
Hi 
I tried to generate uniformly distributed initial points：

opt_gp = Optimizer([(0.0, 6.0)], base_estimator="GP", initial_point_generator = 'grid',random_state=1)
opt_gp.ask(8)

[[4.0], [3.0], [2.0], [4.5], [0.0], [1.5], [6.0], [4.0]]

it is not uniform and some number appeared twice

**Comment by kernc** [comment]
`initial_point_generator='grid'` should be _asymptotically_ uniform—no guarantees for any particular small sample.

Generating hundreds of points confirms it is:
```py
>>> opt_gp = Optimizer([(0, 6)], initial_point_generator='grid', n_initial_points=1001)
>>> x = np.array(opt_gp.ask(1000)).flatten()
>>> np.histogram(x, bins=6)
(array([163, 167, 166, 170, 167, 167]), array([0., 1., 2., 3., 4., 5., 6.]))
```
Here's the implementation if you'd like to study/improve it:
https://github.com/scikit-optimize/scikit-optimize/blob/9334d50a1ad5c9f7c013a1c1cb95313a54b83168/skopt/sampler/grid.py
