### ISSUE TITLE
skopt.Space prior does not check argument validity

### ISSUE THREAD

**Issue by gcp** [scikit-optimize/scikit-optimize#1017]
https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/space/space.py#L292

The "transform" part is checked for validity, but not the "prior" part. As a result, anything that isn't "uniform" will silently be treated as "log-uniform".

(But this has no effect due to other bugs, which I'll also file)

**Comment by kernc** [comment]
`Integer(Dimension)` and `Categorical(Dimension)` also have `.prior` and use it unchecked ...
https://github.com/scikit-optimize/scikit-optimize/blob/9334d50a1ad5c9f7c013a1c1cb95313a54b83168/skopt/space/space.py#L486-L505
https://github.com/scikit-optimize/scikit-optimize/blob/9334d50a1ad5c9f7c013a1c1cb95313a54b83168/skopt/space/space.py#L608

**Comment by gcp** [comment]
>Integer(Dimension) and Categorical(Dimension) also have .prior and use it unchecked ...

The usage in Categorical is quite different and it doesn't seem as prone to implicit fall-through because of a misspelling or similar. Added the check for Integer too.
