### ISSUE TITLE
TypeError when dumping results generated with Tqdm callback

### ISSUE THREAD

**Issue by Rob192** [scikit-optimize/scikit-optimize#1026]
Hello ! 
I do not understand the following issue that occurs to me. Maybe, you can help :) 
I was trying to implement the solution described in #674 by @LucaCappelletti94. However, when I am trying to save the results of my optimization I am getting the following error on Windows. 

TypeError: cannot serialize '_io.TextIOWrapper' object

Here is some code to reproduce the error :  
```python
import numpy as np
import skopt
from tqdm import tqdm
from pathlib import Path

from skopt import gp_minimize
from skopt.space import Real
from skopt.utils import use_named_args

class TqdmSkopt(object):
    def __init__(self, **kwargs):
        self._bar = tqdm(**kwargs)

    def __call__(self, res):
        self._bar.update()

dimensions = [Real(name='x', low=-2.0, high=2.0)]

@use_named_args(dimensions=dimensions)
def f(x):
    return (np.sin(5 * x) * (1 - np.tanh(x ** 2)) *
            np.random.randn() * 0.1)

n_calls = 10

res = gp_minimize(f, dimensions, n_calls=n_calls, callback=[TqdmSkopt(total=n_calls, desc="Gaussian Process")])
skopt.dump(res, Path('./data/test.z'))
```

**Comment by kernc** [comment]
Apparently our code had changed since 2019, turning to multiprocess/pickle even when `n_jobs=1`?

This is somewhat of a tqdm issue, whose progress bar can't be pickled for containing presumably a `logging.Logger` object. Here's [a "fix" as implemented in skorch](https://github.com/skorch-dev/skorch/pull/663/files#diff-99093b2ede6e0b87e60833cdad813b44d47ba738788fa9c7f7405f4fea38c300R581-R591).

**Comment by Rob192** [comment]
Hello @kernc 
Sorry for not answering this earlier. Your solution solved by problem. 

```python
class tqdm_skopt(object):
    def __init__(self, **kwargs):
        self._bar = tqdm(**kwargs)

    def __call__(self, res):
        self._bar.update()

    def __getstate__(self):
        # don't save away the temporary pbar_ object which gets created on
        # epoch begin anew anyway. This avoids pickling errors with tqdm.
        state = self.__dict__.copy()
        del state['_bar']
        return state
```
