### ISSUE TITLE
Notebook: comparison between GP-based, dummy and tree-based optimisation

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#103]

**Comment by betatim** [comment]
Should use a problem where it is clear whether or not dummy opt is being outperformed or not. The current benchmarks might be "too easy". If we increase the number of dimensions of the problem we should (exponentially?) reduce the chances of hitting the minimum with a random sample. #16 might contain something useful wrt a harder benchmark.

**Comment by betatim** [comment]
I started work on this.
