### ISSUE TITLE
Scipy.optimize.minimum constraints in a class Python

### ISSUE THREAD

**Issue by Tchiimy** [scikit-optimize/scikit-optimize#1039]
Hello,

That's maybe a dumb question but I have difficulties to setup the constraints for the minimum function.

I have a python class in which I call this method : 

```
    def minim_solver(self, objective):

        x_init = [0.20, 0.015, 0.03, 0.03, 0.03]

        self.objective = objective
        self.bnds()

        cons = ({'type': 'ineq', 'fun': lambda x: 0.01 - x[1] - x[3]},
                {'type': 'ineq',
                    'fun': lambda x: 0.01 - x[2] - x[0]},
                {'type': 'ineq', 'fun': lambda x: 0.08 - x[4]})

        result = scipy.optimize.minimize(lambda x: self.fun(x), x_init, method='SLSQP', bounds=self.bnds, constraints=cons, options={
            'disp': True, 'ftol': 1E-1, 'eps': 1.4901161193847656e-01})
        print(result.x)
```

To summarize I want to play with the vector x (5 parameters) to generate a mesh and do FEM with this fun(x) : 

```
    def fun(self, x):

        # solver x[0] --> x0,y0,z0
        # solver x[1] --> l,h,w

        # modify values
        self.added_mass_modify(x)

        # generate new mesh
        self.freq_solv(0.01, 6, 0.0)
        print(x)
        self.modes_plot(0, 0.01)

        # Calculate the gap
        Ecart = abs((self.objective - self.Freqs[0]) / (self.objective)) * 100

        return Ecart
```

But when I try the code with or without the "constraints=cons" I have no differencies and my vector x doesn't respect the constraints.

So I'm not sure if I created the constraints correctly or if it's my class structure that messed up everything.

Do you have any recommandations or examples like this that I could tcheck ?

**Comment by kernc** [comment]
Is this about `scipy.optimize.minimize` or `skopt`?

**Comment by Tchiimy** [comment]
> 
> 
> Is this about `scipy.optimize.minimize` or `skopt`?

It's about[ `scipy.optimize.minimize`](https://docs.scipy.org/doc/scipy/reference/reference/generated/scipy.optimize.minimize.html?highlight=scipy%20optimize%20minimize#scipy.optimize.minimize)

**Comment by kernc** [comment]
Therefore, it's the wrong forum. Try [StackOverflow](https://stackoverflow.com/search?q=%5Bscipy%5D+constraints) or one of the [SciPy-centric support venues](https://www.scipy.org/scipylib/mailing-lists.html#mailing-lists)?
