### ISSUE TITLE
Warning about np.float being deprecated when defining a space

### ISSUE THREAD

**Issue by freddyaboulton** [scikit-optimize/scikit-optimize#1043]
Repro:

```python
import warnings
from skopt.space import Real

warnings.simplefilter("always")

with warnings.catch_warnings(record=True) as warn:
    real = Real(0.0, 1.0)

assert str(warn[0].message) == '`np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.\nDeprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations'
```

I'm seeing this warning all over my team's CI. I think it's coming from this [line](https://github.com/scikit-optimize/scikit-optimize/blob/747b43fb03126de5cb26e2090d6ecd93943a2dd7/skopt/space/space.py#L272). Is there a plan for getting ahead of the incoming deprecation?

**Comment by kernc** [comment]
It's actually coming from one of the lines touched by https://github.com/scikit-optimize/scikit-optimize/pull/1023 but as yet unreleased. Maybe try master.

**Comment by freddyaboulton** [comment]
Thank you @kernc ! Yes, it is fixed on master.
