### ISSUE TITLE
[Feature Request] Support more distributions in space.Real

### ISSUE THREAD

**Issue by Abdelgha-4** [scikit-optimize/scikit-optimize#1054]
I think it would offer more flexibility if it was possible to use any type of distributions in the search.
In particular I think it would be useful in `BayesSearchCV` to use the same distributions allowed in `RandomizedSearchCV` (such as those from `scipy.stats.distributions`)

**Comment by kernc** [comment]
Duplicate of https://github.com/scikit-optimize/scikit-optimize/issues/603.
