### ISSUE TITLE
Specify starting point `x0`

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#114]
As we have already noticed, the starting points of the optimization process may be critical in some situations. For this reason, I think it might be nice to be able to provide one or several starting points, similarly as with the `x0` parameter in `scipy.optimize.minimize`. This would be an alternative to random initialization, but one that would allow to bootstrap the process with a priori knowledge.

What do you think?

**Comment by betatim** [comment]
👍 

We should have a think how/if we could combine this with the ability to "resume" the optimisation process. Similar to `warm_start`. Run `*_minimize(maxiter=25)`, inspect the output, decide that you should have done `maxiter=30`, now you want to resume from where you left off or provide the values of `func` at the first 25 iterations.

Related #68

**Comment by glouppe** [comment]
We should probably put this a bit higher on our list of priorities, see eg https://twitter.com/balazskegl/status/755375668582547456 by @kegl

**Comment by MechCoder** [comment]
Fixing this right now.

**Comment by glouppe** [comment]
Fixed by #119
