### ISSUE TITLE
np.int no longer works with numpy >= 1.24

### ISSUE THREAD

**Issue by vishalthatsme** [scikit-optimize/scikit-optimize#1158]
https://github.com/scikit-optimize/scikit-optimize/blob/a2369ddbc332d16d8ff173b12404b03fea472492/skopt/space/transformers.py#L262

**Comment by vishalthatsme** [comment]
Also on line 275.

**Comment by ChromaticIsobar** [comment]
This is a know issue. You may want to refer to #1138 for solutions and further discussion.
