### ISSUE TITLE
Doc: optimisation -> optimization

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#121]
As suggested by @rasbt

https://twitter.com/rasbt/status/755411036136615937

**Comment by betatim** [comment]
[seven starting points](https://github.com/scikit-optimize/scikit-optimize/search?utf8=%E2%9C%93&q=optimisation).

---

I have to ask: we are sure we want 🇺🇸 and not 🇬🇧 ? :)

**Comment by rasbt** [comment]
Haha I probably don't have a say in this but I would definitely prefer the former ... Also, you don't want to change names of functions and modules, right? :)

**Comment by betatim** [comment]
If recent 🇬🇧 behaviour is anything to go by we would be changing all the things 😃.
