### ISSUE TITLE
Reduce the number of iterations in `test_tree_based_minimize`

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#125]
Now that we have more sensible defaults, it might be worth checking to see if the tests in `test_tree_opt` can pass with lesser number of iterations so that the tests run faster.

**Comment by glouppe** [comment]
Working on it!

**Comment by glouppe** [comment]
Also releasing scikit-learn 0.18 would be really nice easily to gain a few minutes of installation time. :s

**Comment by MechCoder** [comment]
One release at a time :p

**Comment by glouppe** [comment]
Fixed in #126

**Comment by betatim** [comment]
Should we also reduce the number of iterations in the GP tests? Otherwise closing this issue.

**Comment by glouppe** [comment]
Woops, forgot to close. Yes I also reduced iterations for GPs as part of #126.

**Comment by betatim** [comment]
Oh yes, apparently I need my 👓 adjusting ...
