### ISSUE TITLE
Accepting discontinuous sets for a dimension?

### ISSUE THREAD

**Issue by ardunn** [scikit-optimize/scikit-optimize#154]
Does skopt allow for discontinuous sets of data for a dimension?

For example, if I wanted to search along param x_1 from 1-100 excluding 50-55, how would this be accomplished?

**Comment by betatim** [comment]
I can't think of a straightforward way to do it with what is currently implemented.

Could you give some examples for use cases? Taking those into account will make for a better implementation.

**Comment by glouppe** [comment]
This is not directly possible at the moment, but for a simple constraint like you could define you can hack around something like:

```
def objective(x):
    ...
    this_param = x[i]
    if this_param > 50:
        this_param +=5.0
    ...
    return something

minimize(objective, [(...), (0.0, 95.0), (...)])
```

(i.e., you remap the (0,95) interval onto (0,50)+(55,100))
