### ISSUE TITLE
Add skopt.benchmarks functions

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#16]
For now, we could be move in the two benchmarks functions defined in the tests of `gp_opt.py`.

**Comment by glouppe** [comment]
Other possible benchmarks, as collected by @betatim in #2 

http://automl.org/benchmarks.html
http://www.sfu.ca/~ssurjano/optimization.html

**Comment by MechCoder** [comment]
I really think, we should reopen this.

**Comment by AlexanderFabisch** [comment]
This might also be interesting: http://coco.gforge.inria.fr/

**Comment by glouppe** [comment]
@MechCoder What else do you have in mind for this? (I think  we should avoid vague issues that will never be 100% fulfilled.)

**Comment by MechCoder** [comment]
OK, let us close this and add I'll add more specific ones.
