### ISSUE TITLE
Normalization to [0,1]?

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#160]
For a project I am working on, I just found that normalizing input values to [0,1] yields better results. 

In general, I think this is not necessary, as the GP kernel should be able to learn the proper scaling, but I do see differences in practice. 

We shall investigate more systematically on few examples whether this is necessary and either i) pick a better default kernel or ii) systematically rescale so that the transformed space is [0,1]^p, no matter what. In a very early version of the codebase, we were indeed doing that.

Also, option ii has some advantages, as it allows not shooting oneself in the foot when playing with custom `base_estimator`.

**Comment by betatim** [comment]
Indeed this got lost when fiddling with the spaces API.

Are there any downsides to always transforming? It seems like it should be ok. Just wondering for tree based models which don't have a problem with varying scales if there is a penalty they end up paying for getting normalised dimensions only.

**Comment by MechCoder** [comment]
Should we postpone this to after 0.1?

**Comment by glouppe** [comment]
Yes, this is just an exploratory branch at the moment
