### ISSUE TITLE
Double check all default parameters

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#166]
All default parameters should be double checked, as I believe some of our choices are currently suboptimal.

- [x] gp_minimize: default kernel?
- [x] gp_minimize: default noise level alpha for the GP? or prefer alpha=0.0 + a WhiteKernel() component?
- [x] gp_minimize: search=sampling vs search=lbfgs?
- [x] gp_minimize: when search=lbfgs, maxiter? n_restarts_optimizer?
- [x] gp_minimize: n_points?
- [x] forest_minimize: n_points?
- [x] forest_minimize: default base estimator?
- [x] default acquisition function? from the literature and from our tests, EI seems to be the best choice among the functions we have. 
- [x] default values for kappa and xi?

I am tagging this as major, as these tweaks can change results from poor to great. We should fix that before 0.1.

**Comment by glouppe** [comment]
We should also double check with has being done in other BO packages.

**Comment by MechCoder** [comment]
For `forest_minimize`, I think the default base estimator, that is the extra trees regressor comes closest to SMAC's defaults as it smoothens the decision surface.
Also the number of points are 10000

**Comment by glouppe** [comment]
Fixed by #174 until the next iteration :)
