### ISSUE TITLE
Upload re-rendered example notebooks for each PR

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#178]
Find out if we can have travis upload the re-rendered `examples/` notebooks somewhere for each new PR so we can see if changes affect the notebooks. This would be similar to running the tests for each new commit in a PR, except we re-execute the notebooks and upload them somewhere as rendered HTML.

**Comment by MechCoder** [comment]
I'll try having a look today. It is irritiating to have to change all the notebooks, especially when we have made a API change.

**Comment by MechCoder** [comment]
Is it possible to "execute" the notebooks from the terminal? I don't think so.

**Comment by glouppe** [comment]
Reopening, Travis is not happy.

https://travis-ci.org/scikit-optimize/scikit-optimize/jobs/149973693#L520

**Comment by glouppe** [comment]
Also, would be nice to try to silence those messages: https://scikit-optimize.github.io/notebooks/bayesian-optimization.html (first cell)

**Comment by glouppe** [comment]
I reverted changes from #186 at e3f0552c5d517ba457fcd72f90ba2e1b55a43d1d since it made one of the notebooks to disappear.

**Comment by betatim** [comment]
A bit that was missing from #186 was uploading them somewhere (or making a nbviewer link) so we can review them.

**Comment by MechCoder** [comment]
Seems like Travis failed because of a timeout? If that is the case, then we have no choice but to move to CircleCI

**Comment by MechCoder** [comment]
This should be fixed now in master. I have set the timeout to 15 minutes. Feel free to reopen or open a new issue if something fails.
