### ISSUE TITLE
Select dimensions to show in `plot_objective`

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#182]
The `plot_objective()` function can take a (very) long time to run for problems like `hart6` + two extra dimensions. Much longer than just `hart6`. Measured with the subjective "waiting for the plot to appear" stop watch in my head.

Adding a parameter with which to select the dimensions for which to make the plots and which dimensions to skip would be useful. If you are using the function several times to inspect your optimisation result you might want to only see a subset of all the dimensions.

**Comment by betatim** [comment]
Creating the final plot in the notebook created for #179 takes a lot of time. Speeding that up by removing dimensions or using `Parallel` is the aim of this issue.

**Comment by jusjusjus** [comment]
I extended plotting a bit for user-defined axis labels https://github.com/jusjusjus/scikit-optimize .  I totally agree though, that computation time is the real issue.  It could be useful to have some result caching here.  Maybe we should create a branch to improve visualization?  Did you put some work into this already?

**Comment by betatim** [comment]
I don't think anyone has worked on this specific issue.

I was thinking of letting users select a subset of all the dimensions in the search space when calling, something like: `plot_objective(dimensions=['dim1', 'other_dim',...])`

The easiest way to get changes into skopt is to create a PR, we don't really create long lived branches in this repository.

**Comment by jusjusjus** [comment]
Well, one way of assigning names would be to give space a name property.  Actually, the clean way to do would be to have a dict interface when assiging bounds.  Space.name could be assigned the key of the dict, which could also coincide with the function argument name of the parameter to optimize.  That could be considered somewhat of a depart from the scipy.optimize way though, and be more tensorflow-esque:
```
def fn(x):
    ...
res = gp_minimize(fn, {'x': (1.0, 6.5)})
```
What are your thoughts?

Something like `plot_objective(dim=['x'])` would become hell of a lot easier to implement, I think, though.

**Comment by betatim** [comment]
Check out #508 where we just merged support for naming dimensions.
