### ISSUE TITLE
Remove forest_minimize(base_estimator=dt)?

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#188]
` forest_minimize(base_estimator=dt)` is expected to perform poorly almost always. I would be in favor of removing it before the release, to avoid users shooting themselves in the foot. 

(For the power user, an exact equivalent can still be retrieved by passing `base_estimator=RandomForestRegressor(n_estimators=1, max_feature=1.0, bootstrap=False)`).

**Comment by betatim** [comment]
If we can not think of a single case/application where you would prefer a DT over a small RF or ET I am Ok with removing it. (I can't think of a use case)

**Comment by MechCoder** [comment]
Yes let's remove
