### ISSUE TITLE
relate ro robo

### ISSUE THREAD

**Issue by amueller** [scikit-optimize/scikit-optimize#19]
relevant: https://github.com/automl/RoBO

**Comment by glouppe** [comment]
also https://github.com/jmetzen/bayesian_optimization from @jmetzen

**Comment by jmetzen** [comment]
As for "my" repo: it's only partly usable without BOLeRO, which is not yet publicly available (any news on this @afabisch ?).  What could be useful is the implementation of the entropy search acquisition function, which is non-trivial and often outperforms UCB or EI considerably in terms of sample-efficiency (at the expense of being computationally very expensive).
