### ISSUE TITLE
Provide gradients for EI

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#191]
It seems it is possible to derive the gradients of the EI acquisition instead of approximating it numerically, as we currently do when `search="lbfgs"`.

See https://github.com/HIPS/Spearmint/blob/master/spearmint/choosers/acquisition_functions.py#L248

**Comment by MechCoder** [comment]
I'm trying to have a look at this over the next few days.

**Comment by MechCoder** [comment]
I think an easier first step would be to provide gradients to LCB. WDYT?

**Comment by glouppe** [comment]
Sure, but EI works much better

**Comment by betatim** [comment]
Checkout #244 for an idea on using autograd.

**Comment by glouppe** [comment]
For EI, code for computing the gradient is given at the link I posted above.

**Comment by MechCoder** [comment]
The code involves computing the gradient of the predicted mean and variance with respect to x, (which in turn involves computing the gradient of the kernel with respect to x). I'm working on that right now.

See: https://github.com/HIPS/Spearmint/blob/master/spearmint/choosers/acquisition_functions.py#L208
