### ISSUE TITLE
Pseudo-random sampling for random start points

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#193]
See discussion in #187

**Comment by glouppe** [comment]
Note that this can be used in different places:
- in `dummy_minimize`
- as an alternative to `search="sampling"`
- to provide initial points to the solver when `search="lbfgs"`

**Comment by betatim** [comment]
Another strategy we should consider (for tree based methods?) is creating samples at the edges/boundaries of the search space as the initialisation points. If your minimum is close to an edge this will help, in other cases you are wasting samples.

**Comment by MechCoder** [comment]
Having a look right now.

**Comment by betatim** [comment]
Probably related to #250

**Comment by glouppe** [comment]
Pseudo random sampling did not prove to be worth the trouble over simpler uniform random sampling (see #262).

Closing for now.
