### ISSUE TITLE
Save instance of results object on to disk

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#201]
Sometimes at the end of long optimization runs, we would like to store the objects to disk for future use.

One immediate use-case is https://github.com/scikit-optimize/scikit-optimize/issues/180

For pickling, lambdas etc, I suggest we backport cloudpickle (https://github.com/apache/spark/blob/master/python/pyspark/cloudpickle.py) to `skopt.externals`, unless others have better ideas.

**Comment by betatim** [comment]
This is a duplicate of #190. Should we move there or close that one?

**Comment by MechCoder** [comment]
Ah I forgot about that. I'll close this.
