### ISSUE TITLE
Suppress warning in auto-generated notebooks

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#221]
https://scikit-optimize.github.io/notebooks/hyperparameter-optimization.html
https://scikit-optimize.github.io/notebooks/bayesian-optimization.html

Yuck :(

**Comment by MechCoder** [comment]
@betatim was responsible for that in https://github.com/scikit-learn/scikit-learn/pull/7261 . So he should fix it :-)
