### ISSUE TITLE
skopt Import Error

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#223]
I am unable to import skopt from anywhere else except the base directory. For example, if I try importing skopt from the examples/ directory, I just get

```
/usr/local/lib/python3.4/dist-packages/scikit_optimize-0.1-py3.4.egg/skopt/__init__.py in <module>()
     58 """
     59 
---> 60 from . import acquisition
     61 from . import benchmarks
     62 from . import callbacks

ImportError: cannot import name 'acquisition'
```

Is anyone able to reproduce?

**Comment by betatim** [comment]
Tried to reproduce by created a new conda environment for `skopt`:

```
$ conda create -n skopt-test python=3.5 numpy scipy`
$ pip install -e git+https://github.com/scikit-learn/scikit-learn.git#egg=scikit-learn-0.18dev
```

but with this importing `sklearn` (master @ 9864cd5a) fails with the following message:
```
>>> import sklearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thead/anaconda/envs/skopt-test/lib/python3.5/site-packages/sklearn/__init__.py", line 57, in <module>
    from .base import clone
  File "/Users/thead/anaconda/envs/skopt-test/lib/python3.5/site-packages/sklearn/base.py", line 11, in <module>
    from .utils.fixes import signature
ImportError: No module named 'sklearn.utils'
```
so I will have to understand that a bit better.

In my normal dev conda environment for `skopt` importing `skopt` from a random directory works as expected.

**Comment by MechCoder** [comment]
Is this after installing the updated version of skopt?, (i.e after https://github.com/scikit-optimize/scikit-optimize/pull/219)?

**Comment by MechCoder** [comment]
Should be fixed by https://github.com/scikit-optimize/scikit-optimize/pull/224

**Comment by pavelkomarov** [comment]
I am currently having this problem too: We installed scikit optimize in to an Anaconda environment, and I can not import it from anywhere except its root directory without getting `ImportError: cannot import name acquisition`.

Whose idea was it to ever do anything as ridiculous as `from . import X`?

**Comment by betatim** [comment]
Could you post a few instructions on how to reproduce your error? I created a new conda environment and ran `pip install scikit-optimize` in it. With that setup I can execute `import skopt` without an error.

**Comment by donnydongchen** [comment]
Just in case someone came across this error again:
I am using Anaconda and when I do either `pip install scikit-optimize` or `conda install -c conda-forge scikit-optimize` as found online, it threw `ImportError: cannot import name acquisition`.

Empirical Solution:
`conda install scikit-optimize` and restart the kernel if you are on Jupyter Notebook/Lab. Somehow, I needed to `conda install numpy`, `conda install scikit-learn`, and then `conda install scikit-optimize`, but you might not need to.

**Comment by tordbb** [comment]
I got a similar error when trying to import gp_minimize from skopt: 
> (...) cannot import name 'gp_minimize' from 'skopt' (...)

but it all sorted out when I restarted pyCharm.
