### ISSUE TITLE
Update installation instructions when sklearn 0.18 is released

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#226]

**Comment by betatim** [comment]
Once `sklearn` 0.18 has been released we should be able to have a one line install command `pip install scikit-optimize`. Potential show stopper for that is that `sklearn` doesn't install its dependencies (??)

**Comment by betatim** [comment]
The day has finally come! http://scikit-learn.org/stable/whats_new.html#version-0-18

**Comment by betatim** [comment]
For `skopt-0.1` people will still have to do the complicated step though no? `setup.py` says it requires `scikit-learn>=0.18dev`. Or is `0.18>=0.18dev`??
