### ISSUE TITLE
Deploy documentation only when a release is made?

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#227]
Or alternatively we can have a dev version. Not sure how easy or tough that is

**Comment by glouppe** [comment]
I am in favour of keeping an online documentation in sync with master (either as a /dev/ or as it is now).

**Comment by glouppe** [comment]
(This is fairly easy, we only need to specify another directory in which to copy the auto-generated files. Then upon release, we can sync them back at the index manually.)

**Comment by holgern** [comment]
This is now fixed, there is now a stable release available at https://scikit-optimize.github.io/stable and the documentation for master can be found here: https://scikit-optimize.github.io/dev
From 0.7 on, there will be also a doc version containing the latest release from a major version:
https://scikit-optimize.github.io/0.7
