### ISSUE TITLE
small remarks of python setup.py process

### ISSUE THREAD

**Issue by stonebig** [scikit-optimize/scikit-optimize#238]
```
>python setup.py sdist bdist_wheel 
running sdist
...
warning: sdist: standard file not found: should have one of README, README.rst, README.txt
... 
warning: check: missing meta-data: if 'author' supplied, 'author_email' must be supplied too
```

**Comment by betatim** [comment]
Thanks for this. Does anyone know what github does if you have a `README` with markdown in it (as opposed to the `README.md` we have now)?

Should we create `skopt@gmail.com` or `FindUsOnGitHub@example.com` or ... what do people do for the email address?

**Comment by mp4096** [comment]
GitHub does not render any markup if the `README` file is without extension. Unfortunately, I don't have an example for Markdown, but here's an rST `README` which is not rendered (GitHub does render rST properly, one just has to specify the extension): https://github.com/coin-or/rbfopt

**Comment by holgern** [comment]
Can be closed, Readme has now a rst ending.
