### ISSUE TITLE
Bayesian optimisation example "broken"

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#252]
Something isn't quite right with one of the examples:

https://scikit-optimize.github.io/notebooks/bayesian-optimization.html

final plot shows that the model predicts a "constant". There was a discussion about this somewhere but I can't find it right now. I think we suspected it was related to a change in adding noise to the kernel??

**Comment by MechCoder** [comment]
having a look

**Comment by MechCoder** [comment]
All right, so I've been playing around with this for a while. Here is my code to reproduce with sklearn's GaussianProcessRegressor. I've also assumed that the standard deviation of the noise is known apriori, that is I've set `alpha` to be 0.1 which is never the case.

```python
import numpy as np
import matplotlib.pyplot as plt

from sklearn.gaussian_process import GaussianProcessRegressor
from skopt.learning.gaussian_process.kernels import ConstantKernel
from skopt.learning.gaussian_process.kernels import Matern

def f(x, noise_level=0.1):
    return np.sin(5 * x[0]) * (1 - np.tanh(x[0] ** 2)) + np.random.randn() * noise_level

x_predict = np.linspace(-2, 2, 400).reshape(-1, 1)
x_fit = np.linspace(-2, 2, 20).reshape(-1, 1)
y = np.array([f(x) for x in x_fit])
y_predict = np.array([f(x) for x in x_predict])

cov_amplitude = ConstantKernel(1.0, (0.01, 1000.0))
matern = Matern(nu=2.5)
kernel = cov_amplitude * matern

skgpr = GaussianProcessRegressor(
    kernel=kernel, alpha=0.1, normalize_y=True, random_state=0)
skgpr.fit(x_fit, y)
y_pred_opt, y_std_opt = skgpr.predict(x_predict, return_std=True)
plt.plot(x_fit.ravel(), y, "ro")
plt.plot(x_predict.ravel(), y_predict, label="y_true")
plt.plot(x_predict.ravel(), y_pred_opt, label="y_pred, skopt GP")
plt.xlabel("X")
plt.ylabel("Predictions")
plt.legend()
plt.show()
```

If you run the code a number of times, you'll get plots ranging from 
![noise_1](https://cloud.githubusercontent.com/assets/1867024/19708997/f9002ab8-9af0-11e6-9341-d936a021623d.png)

to

![noise_2](https://cloud.githubusercontent.com/assets/1867024/19709014/1c537a6a-9af1-11e6-8061-36327838e697.png)

depending upon the function values at the values of x sampled. However note that if I increase the 
number of values in `x_fit` to 100, we are able to estimate the original function correctly (which is highly unlikely for hyperparameter optimisation problems even more in higher dimensional spaces). I suggest let us get rid of this for now.

**Comment by MechCoder** [comment]
The flat prediction might be explained by this line from the kernel cookbook, http://www.cs.toronto.edu/~duvenaud/cookbook/index.html

" If your function happens to have a discontinuity or is discontinuous in its first few derivatives (for example, the abs() function), then either your lengthscale will end up being extremely short, and your posterior mean will become zero almost everywhere"

**Comment by glouppe** [comment]
What is the effect of increasing the number of random starts in the underlying optimizer? By default, only one run is being done, which might avoid being stucked in local minima. Would  be worth trying to mitigate this.
