### ISSUE TITLE
Condense hyper parameter example

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#254]
Can we shorten the example about [tuning hyper-parameters](https://scikit-optimize.github.io/notebooks/hyperparameter-optimization.html) while retaining the pipeline example?

One approach would be to shorten the explanatory text and generally try and condense things. It is good to show off the pipeline feature to make people aware of it. Especially now that you can swap whole steps! At the same time we want to avoid the wall of text problem.

**Comment by MechCoder** [comment]
Also not sure PCA on categorical variables + applying it on a tree-based method makes sense. Might make more sense to use something like scaling set on and off + SGD or something similar. WDYT?

**Comment by glouppe** [comment]
> Also not sure PCA on categorical variables makes sense. Might make more sense to use something like scaling set on and off + SGD or similar. WDYT?

+1. The current example is really not convincing at all, since not using pipelines is better in all cases (see last plot).

**Comment by betatim** [comment]
Are there any useful preprocessors you'd want to use with a tree based model?

**Comment by glouppe** [comment]
Not really, except maybe some feature expansion + selection.

**Comment by MechCoder** [comment]
Having a look now.
