### ISSUE TITLE
Expose `base_estimator` in `GBTQuantiles`

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#26]
Comment by @glouppe in #9: 

Would be good to expose the `base_estimator` in this newly introduced class. Default params of `GradientBoostingRegressor` are very likely to give poor results.

**Comment by glouppe** [comment]
Also, not fan of `GBT` (sorry for being picky). Let's be explicit instead. What about `GradientBoostingQuantileRegressor`? or `GradientBoostingQuantiler`?

**Comment by betatim** [comment]
No worries, I also don't like the name but couldn't come up with something good. `GradientBoostingQuantileRegressor` is my favourite so far.

**Comment by betatim** [comment]
Reopened as we still need to expose `base_estimator`
