### ISSUE TITLE
How to cite scikit-optimize?

### ISSUE THREAD

**Issue by bjodah** [scikit-optimize/scikit-optimize#263]
Hi,

Currently I've been performing some modelling for experimentalists (academic research).
I have found `skopt` to be very useful and I would like to cite it.
Do you have any preferred format when citing `skopt`? (I've searched the repo and docs but couldn't find any guidance)

Also, do you offer any recommendations on what other references to cite (I've used `forest_minimize` for example)?

**Comment by mp4096** [comment]
+1

Maybe a Zenodo DOI?

**Comment by betatim** [comment]
Right now we don't have anything beyond a link to the repo 😄 

Thanks for bringing this up. We haven't discussed this much yet.

My preference would be to make a submission to JOSS, this then gives everyone something to cite. However Zenodo DOI and JOSS have the annoying feature that it is for a particular version of the software. Which is nice if you want to track versions, but means we'd have to make a new submission for every release ... so I have a slight preference towards creating a "thing" that people can cite that is valid forever and then specify by hand which release they used.

Another thing to ponder, can we put "The scikit-optimize contributors" as the author? Then there is the whole question of should we do that ... (in HEP there is a field for the collaboration in citations now so often you see `Aardvark et al. [XYZ collaboration], ...`)

**Comment by betatim** [comment]
Regarding a reference for `forest_minimize`: it is inspired by the work in SMAC, but I don't think we implement exactly what they do. Maybe SMAC cites something telling us what inspired them?

**Comment by mp4096** [comment]
JOSS looks really nice.

Personally, I think that requesting a Zenodo DOI for each version is only a minor inconvenience. Submitting a new JOSS entry seems to be a little bit more intensive.

As for the authors, [`scikit-learn`](https://zenodo.org/record/49911) seem to include all the contributor into the authors list. At the same time I think it is 100% ok to mention a `scikit-optimize collaboration` and reference [`AUTHORS.md`](https://github.com/scikit-optimize/scikit-optimize/blob/master/AUTHORS.md).

**Comment by betatim** [comment]
@bjodah how soon do you need an answer? I think we will take a few more days to make up our mind, so if you need to move faster, feel free to do what you think is best 😃

**Comment by bjodah** [comment]
A few days waiting time is no problem (I am guessing we will submit in a few weeks but I'm not the main author so hard to say for sure).

Not that it is any of my business, but I thought I could mention that there is also [JORS](http://openresearchsoftware.metajnl.com/) (Journal of Open Research Software).

**Comment by betatim** [comment]
Any thoughts?

Otherwise I would say let's create zenodo entry for every (future) release -> DOI for people to cite to signify which version they use.

If and when we do something nice that is original research (or otherwise should be documented in an article) we tackle that on a case by case basis.

---

If we want to discuss this more I would suggest we start with collecting a list of the problems that we are trying to solve via citation as that will help us figure out what the solution should be.

**Comment by MechCoder** [comment]
fine with me.

**Comment by glouppe** [comment]
In machine learning, there is a long tradition of publishing short software papers in JMLR OSS+arXiv (http://www.jmlr.org/mloss/). These papers are then used for citations. This is not ideal because the list of authors is fixed and prevent future contributors from getting proper credits, but at the same time they are much better indexed and accounted for than Zenodo and alikes.

**Comment by betatim** [comment]
Problems we need to solve:

* give credit to all contributors
* create citable entity so people can document version of skopt they used
* create citable entity so people can give credit for ideas

Can we write a JMLR OSS for every release that is text wise only a minor update on the previous paper?

Can we update the authorlist for a arxiv paper? Then we could create one arxiv entry and update it for ever release. In some sense arxiv is "ideal" for this as they already support multiple versions of one paper. (it would totally screw with any kind of naive citation counting if you became an author at some point in the future)

(I am a little outside of the citation collecting game ATM so I am biased towards lowest hassle/most radical solution.)

**Comment by betatim** [comment]
Or would we be happy to publish an article on "all of skopt" every ~6months? This might be slow enough that we don't run into unhappy editors who don't like us (re)publishing essentially the same text every few months. This is opposed to publishing on every release.

**Comment by glouppe** [comment]
One thing we could do as well is have a collective author name, e.g "the scikit-optimize authors" and then publish once in JMLROSS / arXiv.

**Comment by betatim** [comment]
I think we should make a submission to JOSS with a collective author name as first author (or only author??) with the next release. THen we can ponder what to do next after. WDYT?

**Comment by chschroeder** [comment]
I just stumbled on this topic, while searching for something else. This should now be resolved by #607.

**Comment by betatim** [comment]
Good spot. Closing

**Comment by microprediction** [comment]
Ah, well if you ever change your mind... tiny PR here is welcome :) [CITE.md](https://github.com/microprediction/humpday/blob/main/CITE.md)
