### ISSUE TITLE
Hide stdout when running `py.test`

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#273]
Can py.test capture stdout when running tests by default? Currently you get to see a lot of output when running the tests instead of just Fail/Pass.

**Comment by mp4096** [comment]
It's actually strange that `pytest` does print to the `stdout` during tests although it should capture it per default: http://doc.pytest.org/en/latest/capture.html

> During test execution any output sent to `stdout` and `stderr` is captured. If a test or a setup method fails its according captured output will usually be shown along with the failure traceback.

**Comment by glouppe** [comment]
Actually tests use `nose`, for which the output is captured by default. Closing.
