### ISSUE TITLE
Set n_restarts_optimizer > 0 in GPRegressor

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#282]
This is super important. We should set n_restarts_optimizer > 0 in GPRegressor.

The motivation is that we should not waste function evaluations if afterwards we are making a very poor job a modeling the GP. 

Yes it will make things slower, but that is worth it in my opinion.

What do others think? @MechCoder @betatim

**Comment by MechCoder** [comment]
Yes, we should. I set it to 2 in the other pull request. What do you want to set it to?

**Comment by glouppe** [comment]
Yes 2 seems like a good start.


(sent from my phone)
