### ISSUE TITLE
Optimizer Strategies as Classes?

### ISSUE THREAD

**Issue by scottee** [scikit-optimize/scikit-optimize#286]
Probably a feature request...  

Is there a way to use these optimizers as classes instead of just functions?  If not, is there a reason not to do that?  What I'd like to do is pass around the optimizer strategy as an object and allow uses of it in various contexts w/o having to know the details of the strategy function or its parameters.  I'm imagining something where __init__() takes all the args normally given in the function call, and each strategy class has a optimize() method which would call something similar (or equivalent) to the existing functions.

This could also potentially support sklearn parameter updating, etc.

I would think this approach would also allow more tailoring of the strategies, but I'm making a lot of guesses in saying that.

**Comment by MechCoder** [comment]
Does https://github.com/scikit-optimize/scikit-optimize/pull/234 handle your request?

**Comment by scottee** [comment]
Thanks for the quick reply.  My opinion is I don't think so, but it
depends...

Ask-and-tell seems to be more about asynchronous evaluation of the
objective function.  I'm not suggesting that.  (Although I can see how it
would be useful, especially if it includes a "restart where I left off"
concept.)  If ask-and-tell requires you to use classes, then it might solve
what I'm suggesting as a side effect.  But the classes seem like an after
thought, not something designed from the ground up as a 1st class citizen.

One way to evaluate what I'm suggesting is if I could add my own
optimization algorithm class into skopt class framework easily, without
having to re-implement much except my new algorithm.

-Eric Scott

**Comment by betatim** [comment]
For freezing parameters you could use `partial` like we do in some of the tests. Would that work for you?

**Comment by scottee** [comment]
Partials are nice for wrapping the args of a single function (which is my
most immediate need), but not for all the other features you get with
classes.  For example, it doesn't give me the ability to have an interface
with multiple methods or add a new algorithm as a derived class.

**Comment by betatim** [comment]
I'm not sure I understand. To implement a new method you can write a new function that implements it and reuse the components that are used to build the methods provided by scikit-optimize no? Almost all the current methods use `base_optimizer` to do the actual work, the difference come from passing in a different `base_estimator` or acquisition function. For example `forest_optimize` is about 20lines of code most of which deals with `forest_optimize` specific parameters.

Maybe you could propose a concrete example of what you'd like to do to help us understand better.

(#234 is a first step towards making those building blocks easier to reuse)

**Comment by betatim** [comment]
Closing this for now, we can always reopen it again later.
