### ISSUE TITLE
Reload after dump and continue optimizing

### ISSUE THREAD

**Issue by kittythecat** [scikit-optimize/scikit-optimize#305]
Would it be possible to dump() the optimizer and then later load() such that optimization can be continued (by supplying the function to minimize)?

**Comment by betatim** [comment]
I think all the information that you would need is in what `dump()` saves. You need to get it out by hand though and feed it in as initial points etc when you call your `foo_optimize()`. You could also try out the [new ask-and-tell interface](https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/optimizer/optimizer.py#L20) ([and not yet documented](https://github.com/scikit-optimize/scikit-optimize/issues/296) which was added to help with uses cases like this.

Having a convenient way (single function) to save and then resume an optimizer would be a welcome addition to the code base.

**Comment by kittythecat** [comment]
Thank you, at first i thought to use initial points, but that means that it re-evaluates these points again. I think the ask/tell is exactly what I'm looking for. I'll try it out asap. If I have time, I'll make a small notebook document.

**Comment by betatim** [comment]
For initial points you can provide both the coordinate (`x0`) and value at those points (`y0`): https://scikit-optimize.github.io/optimizer/index.html. Let us know how using the ask-and-tell interface goes.

**Comment by betatim** [comment]
The `Optimizer` class can be `dump`ed and `load`ed:

```python
import pickle
s = pickle.dumps(opt)
opt = loads(s)
```

Would it be convenient to integrate this with `skopt.dump/load`? Would require reformatting some of the arguments etc. As a user I would probably expect to use `skopt.dump` for all `skopt` instances, assuming that it does something clever. Thoughts?

**Comment by kittythecat** [comment]
Both the initial value input and the ask/tell seems to work nicely. I really like the new ask/tell interface, very useful!
Although I will have to figure out how to use the new Optimizer class to obtain OptimizerResults that can be used in the visualizations.
I think it would be more clear if the optimizer class can be dumped through skopt.dump(). I also tend to always remove the objective since it's generally not serializable.
Thanks for the help!

**Comment by betatim** [comment]
Closing this so we can have a focussed discussion in #316 and #315.

**Comment by bernardocaldas** [comment]
Hi @kittythecat , any chance you could show how you did this? Would be interested in restarting the  optimization after a previous run!

**Comment by adidenkov** [comment]
For anyone still interested, I wrote some [code to reload optimizations](https://gist.github.com/adidenkov/98f286c5c6b4789f140fa79041f282bb#file-reload-py).
