### ISSUE TITLE
skopt.load/dump can not handle `Optimizer` instances

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#316]
`Optimizer` instances can not be serialised with `skopt.dump/load`. This is probably unexpected for users, or at the very leat inconvenient. More discussion in #305

It would make sense to extend `dump/load` to support "all" of the `skopt` classes etc.

Needs a bit of discussing in terms of API as this is mainly syntactic sugar on top of `pickle`, so we need to find a way that is actually nicer to use than the bare `pickle`.

**Comment by glouppe** [comment]
Would be good to add a test for that.

I tried locally and this appeared to work.
