### ISSUE TITLE
Run examples as part of the CI

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#32]
Avoid broken examples like what happened in #29 by running them as part of travis. Not sure if there is anything more useful we can do than to check that they run with exit code == 0.

**Comment by glouppe** [comment]
Shall we leave this open, provided examples will be eventually replaced with the notebooks?

**Comment by betatim** [comment]
Yes. One way would be calling `nbconvert --execute` and then thinking about how to detect failure.

**Comment by MechCoder** [comment]
Reopened since circleci could not catch the error in https://github.com/scikit-optimize/scikit-optimize/pull/209

**Comment by MechCoder** [comment]
Fixed by https://github.com/scikit-optimize/scikit-optimize/commit/8d804453ea5a2499ef405ca13eff86c9312fa8eb
