### ISSUE TITLE
what does the convergence_plot show?

### ISSUE THREAD

**Issue by agamemnonc** [scikit-optimize/scikit-optimize#321]
For instance, in the hyper-parameter optimization example:
https://scikit-optimize.github.io/notebooks/hyperparameter-optimization.html

Is "min f (x) after n calls" the minimum of computed cross-validated scores at the queried locations , or the estimated minimum of the posterior mean of the cross-validated score model at an arbitrary location?

Thanks.

**Comment by glouppe** [comment]
https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/plots.py#L69

We plot the minimum over the `i` first queried locations.

**Comment by MechCoder** [comment]
It's not the posterior mean at a random point (true minimum?) though that might be interesting as well.

**Comment by AtrCheema** [comment]
@glouppe I just want to know, what is the logic behind plotting minimum and not the original values. In my case, if I do not plot the minimum, I get same plot as mentioned in issue #748 .
