### ISSUE TITLE
Support Forum?

### ISSUE THREAD

**Issue by dhirschfeld** [scikit-optimize/scikit-optimize#347]
Is there any support forum (other than GH issues) where I can ask questions? If there is, it may be worthwhile to highlight it in the project README.

Not knowing a better place to ask I'll post a couple of questions below to avoid cluttering up the issues with too much noise...

**Comment by dhirschfeld** [comment]
#### Q1: Warm-starting
If you've run an optimization `res = gp_minimize(objective, space, n_calls=10)` and have the results but want to futher explore the parameter-space are you able to *re-start* the optimization process so that it continues on from where it left off so that you don't have to re-explore the same parameters as calculated in the initial optimization run?

**Comment by MechCoder** [comment]
Yes! There are arguments `x0` and `y0` where you can provide the initial parameters corresponding to a warm start.

**Comment by dhirschfeld** [comment]
#### Q2: Save optimizer on error
I ran an optimization for a few hours before it blew up with a MemoryError :(
 It might be nice for long-running optimizations to have a `filename` argument which would save the optimizer upon completion or in the case of an exception. - e.g.

[*base.py*](https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/optimizer/base.py#L231-L243)
```python
n_iterations = n_calls - n_init_func_calls
try:
    for n in range(n_iterations):
        next_x = optimizer.ask()
        # no need to fit a model on the last iteration
        fit_model = n < n_iterations - 1
        next_y = func(next_x)
        if not np.isscalar(next_y):
            raise ValueError("`func` should return a scalar")

        res = optimizer.tell(next_x, next_y, fit=fit_model)
        res.specs = specs

        _eval_callbacks(callbacks, optimizer, specs)
finally:
    if filename is not None:
        optimizer.save(filename)  # useful convenience method added!
    
return res
```
Would a PR implementing the above be welcomed?

In either case saving the optimizer possibly deserves a more prominent mention in the docs - I was surprised when I read about it in Gilles' PyData Amsterdam presentation after which all I could find was a brief mention at the bottom of the ask-and-tell notebook.

**Comment by dhirschfeld** [comment]
Thinking more about Q2 - this could also be done externally if rather than a function call you constructed an object with a run method e.g.
```python
optimizer = GaussianProcessOptimizer(objective, space)
try:
    res = optimizer.run(n_calls=10)
finally:
    optimizer.save(filename)
```
Warm-starting could then just be a second call to the run method. That would obviously be a much larger change though. If there's interest in either approach I can open an issue to flesh out the design?

**Comment by glouppe** [comment]
Regarding Q2, the nicest solution would be to add some kind of `CheckpointCallback`, following an API similar to https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/callbacks.py 

If you feel like contributing, this should of moderate difficulty :)

**Comment by dhirschfeld** [comment]
IIUC to re-start an optimization you can use the original result object as follows:
```python
res = gp_minimize(objective, space, n_calls=10)
updated_res = gp_minimize(objective, space, n_calls=10, x0=res.x_iter, y0=res.func_vals)
```
 It seems to work, but the iteration count starts at 1 rather than `len(res.func_vals)`. The minimum is at `res.x` though which suggests that it is correct.

**Comment by dhirschfeld** [comment]
I'm not too sure how a callback would work given an exception would break the `for n in range(n_iterations)` loop without a try/except block. In either case I'm completely underwater at the moment so likely wouldn't find the time in the near future. Nevertheless I thought I'd bring it up as hopefully useful feedback.

I was running 3 parallel `gp_minimize` optimizations when they all blew up with the memory error. In two of them I was able to go into the debugger and save the results so I could continue. In the last I accidentally misspelled `debugg` and the resulting NameError blew away the last exception and consequently my ability to save the state. Hence my desire for something more robust/automated!

**Comment by glouppe** [comment]
@dhirschfeld The are two things that need to be contributed. One would be to have a `CheckpointCallback` whose goal is to pickle after every epoch the full state of the optimizer. The second would be to polish/improve the API to resume optimization (currently it is possible by properly setting `x0`, `y0`, `n_random_starts`, etc, but that can be cumbersome and requires some knowledge of the internals).

**Comment by MechCoder** [comment]
@dhirschfeld Are you currently working on creating a CheckPoint Callback? I think it would be pretty useful.

**Comment by dhirschfeld** [comment]
Not current sorry - have a lot of things going on so haven't had time to familiarise myself with the codebase enough to give it a crack.

Happy for anyone else to pick it up if they have the time...

**Comment by holgern** [comment]
A CheckpointSaver is available https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/callbacks.py, I think i can close this issue.
