### ISSUE TITLE
Methods to optimize the acquisition function

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#35]
Right now we support `lbfgs` and `random sampling`. What are some other methods to optimize the acquistion function?

**Comment by MechCoder** [comment]
@glouppe @betatim What are your thoughts on this?

**Comment by betatim** [comment]
Is there some prior art/literature on using random sampling? It seem like a really strange strategy to use.

One more thing to put on the list would be something like `bfgs` but with multi start (start from `n` random points and only keep the best minimum of all `n` attempts)

**Comment by glouppe** [comment]
+1 for several random restarts added to l-bfgs. 

Other than that, I have seen the "DIRECT" algorithm been used and cited in several BO papers/packages. 
https://hosting.cs.vt.edu/hpcs2008/HPCS08DIRECTtut.pdf

**Comment by glouppe** [comment]
... and here is the commonly used Python implementation https://pypi.python.org/pypi/DIRECT/

**Comment by betatim** [comment]
From today's arxiv: http://arxiv.org/abs/1604.00169 from the abstract it sounds like this does away with acquisition functions all together. Could be OT here but also maybe not.

**Comment by glouppe** [comment]
Partially fixed as part of #38

**Comment by betatim** [comment]
Trees predict a constant for each leaf. This means `bfgs` (and other gradient based) optimisers give up. Pointers to smarter ways for finding the minimum of an ensemble of trees welcome. This is needed for #34.

**Comment by glouppe** [comment]
I am closing this, as this issue is too vague without a clear objective. 

See #74 for ongoing work on local search (one of the many possible solvers).
