### ISSUE TITLE
Dummy_minimize in benchmarks

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#358]
After the work of @iaroslav-ai , we should have a dummy_minimize function in benchmarks to see if we are performing better than random.

**Comment by MechCoder** [comment]
To make months of hard-work to not go waste, I hope the answer is yes!

**Comment by iaroslav-ai** [comment]
I can test it by running benchmark with dummy_minimize. Especially with neural networks, my expectation would be that we are performing better than random (but the test will tell of course).
On related note: I suggest to add dummy_minimize to all problems in benchmark. Also I would propose to reformat the tables in the benchmark to group by problem, but not the method, which would make it easier to compare methods with each other on some particular problem.

**Comment by iaroslav-ai** [comment]
P.S. I have results for n_calls = 200. Maybe I push everything together after I have results with dummy minimize.

**Comment by MechCoder** [comment]
Sounds like a good idea.

**Comment by iaroslav-ai** [comment]
I have pushed results in #362 . Mostly non - random algorithms are better, but the difference is not as significant as I expected.

**Comment by glouppe** [comment]
Closing this issue, as results for `dummy_minimize` are reported in `benchmarks/README.md`.
