### ISSUE TITLE
ValueError: Domain error in arguments, when tuning SVM

### ISSUE THREAD

**Issue by nsriram13** [scikit-optimize/scikit-optimize#366]
I am trying to tune the hyperparameters of an SVM using `skopt`. Following the example on the docs I implemented the below. However, I am getting a `ValueError: Domain error in arguments.` error. Is it something about the way I have set it up?

```python
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn import datasets, svm
from skopt import gp_minimize

iris = datasets.load_iris()
X, y = iris.data, iris.target
X = X[y != 0, :2]
y = y[y != 0]

clf = svm.SVC(kernel='rbf', gamma=10, C=100)


def objective(params):
    kernel_gamma, penalty_C = params

    clf.set_params(gamma=kernel_gamma,
                   C=penalty_C)

    return -np.mean(cross_val_score(clf, X, y, cv=5, n_jobs=-1))


space = [(0.01, 0.001),  # gamma
         (10, 20, 200)]  # C

res_gp = gp_minimize(objective, space, n_calls=100, random_state=0)

print("Best score=%.4f" % res_gp.fun)
```

 Full stack trace below:

```
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-ce3d26def919>", line 30, in <module>
    res_gp = gp_minimize(objective, space, n_calls=100, random_state=0)
  File "C:\Program Files\Anaconda3\lib\site-packages\skopt\optimizer\gp.py", line 247, in gp_minimize
    callback=callback, n_jobs=n_jobs)
  File "C:\Program Files\Anaconda3\lib\site-packages\skopt\optimizer\base.py", line 234, in base_minimize
    next_x = optimizer.ask()
  File "C:\Program Files\Anaconda3\lib\site-packages\skopt\optimizer\optimizer.py", line 181, in ask
    return self.space.rvs(random_state=self.rng)[0]
  File "C:\Program Files\Anaconda3\lib\site-packages\skopt\space\space.py", line 456, in rvs
    columns.append(dim.rvs(n_samples=n_samples, random_state=rng))
  File "C:\Program Files\Anaconda3\lib\site-packages\skopt\space\space.py", line 102, in rvs
    samples = self._rvs.rvs(size=n_samples, random_state=rng)
  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 466, in rvs
    return self.dist.rvs(*self.args, **kwds)
  File "C:\Program Files\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 936, in rvs
    raise ValueError("Domain error in arguments.")
ValueError: Domain error in arguments.
```

**Comment by MechCoder** [comment]
The parameters in the space list should be the bounds and not the values themselves. The error is because `space[0][0] is greater than space[0][1]`.

In this particular example, since there are just 6 hyperparameters you can just do an exhaustive search.

**Comment by MechCoder** [comment]
We should still raise a better error message though, as noted in https://github.com/scikit-optimize/scikit-optimize/issues/301

**Comment by nsriram13** [comment]
I see now. This makes sense!

**Comment by nsriram13** [comment]
A followup q on the `space` parameter. If we have a hyperparameter space that is a set of discrete and continuous values. For instance, for the SVM:

- the kernels can be one of the three options of `rbf`, `poly` or `linear` 
- `C` and `gamma` can be expressed as a range. 

Is the best way to run a `gp_optimize` for each of the discrete set and  pick the one that gives the best objective score?

**Comment by MechCoder** [comment]
You can providing categorical parameters as a list. (https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/space/space.py#L456)

What is not supported is providing numerical parameters as a list. If you do provide them as a list, then it should still work but each numerical parameter is treated as a category, that is ordering is not respected
