### ISSUE TITLE
acq_optimizer is not documented in forest_minimize

### ISSUE THREAD

**Issue by mirca** [scikit-optimize/scikit-optimize#367]
The argument ``acq_optimizer`` is not presented in the docstring of ``forest_minimize``.

Additionally, ``acq_optimizer`` is later passed as ``acq_optimizer="sampling"`` to ``base_minimize``. Although that makes sense because ``forest_minimize`` uses a tree-based regression model, I think the user should be aware of that behavior, at least. 

Should ``acq_optimizer`` be removed from ``forest_minimize``?

**Comment by betatim** [comment]
I vote yes for removing it as you can't set it to anything other than "sampling". The only caveat would be if we plan to introduce an alternative to sampling in the near future.
