### ISSUE TITLE
Is Cython required or not? (is it used ?)

### ISSUE THREAD

**Issue by Naereen** [scikit-optimize/scikit-optimize#377]
Hi.

The `requirements.txt` file states cython as a requirement, but the `README.md` and the `setup.py` both don't specify it as a dependency.
I think it is not used. So maybe remove it from requirements.txt ?

**Comment by MechCoder** [comment]
No, it's not required, thanks for the catch.

Would you like to submit a PR?

**Comment by Naereen** [comment]
OK.

The CI will say "OK" soon.

**Comment by Naereen** [comment]
Please close the issue when merged.
