### ISSUE TITLE
Could some simple Cython-magic be used for speed up ?

### ISSUE THREAD

**Issue by Naereen** [scikit-optimize/scikit-optimize#378]
Apparently, Cython was first thought to be used but it is not yet the case, am I right?

I think some simple Cython versions of the heavier part of skopt could help to have a quicker library?
I am not an expert in Cython so cannot offer to test it and suggest a PR, but if any other contributor can try it, I am certain it will most surely improve performance of skopt (`learning` and `optimizer` modules).

**Comment by MechCoder** [comment]
No, I don't think so.

The `gp` module relies on vectorized numpy operations and lbfgs for log-likelihood maximisation. The predict of the `forest`s can probably be cythonized but I don't think it is worth it., prediction is quick.

**Comment by Naereen** [comment]
OK
