### ISSUE TITLE
Rewrite README.md using restructured text so that it renders nicely on the PyPi page

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#382]
For eg: https://pypi.python.org/pypi/requests

Credits: @Naereen from https://github.com/MechCoder/mondrian-art/commit/fcb639dbbc055fdb41e8ffc283a18856dbc637be#commitcomment-22325181

**Comment by Naereen** [comment]
I suggest to use [`pandoc`](http://pandoc.org/MANUAL.html) to (possibly automatically) convert the README.md file (as displayed on GitHub) to a README.rst file (to be displayed on PyPi).

**Comment by betatim** [comment]
I think pypi uses the value of the `long_description` in `setup.py` so we also need to modify that to be something like `open('README.rst').read()`.

For dib-lab/khmer we recently switched (back to) rst: https://github.com/dib-lab/khmer/pull/1696 for exactly this reason :)

**Comment by Naereen** [comment]
Exactly. Can someone with write access do this change, instead of a PR, please?

**Comment by Naereen** [comment]
> (I remember seeing a large project where the `setup.py` file used [pandoc Python interface](https://pypi.python.org/pypi/pypandoc) to convert the `README.md` to rST on the fly... but that's way too heavy I think -- and I cannot find it again!)

**Comment by betatim** [comment]
I can make a PR later to change the README and change the `setup.py`.
