### ISSUE TITLE
skopt.plots in 1-dimension

### ISSUE THREAD

**Issue by cranmer** [scikit-optimize/scikit-optimize#388]
I'm working on simple examples with optimization with respect to a single variable.
Both 
```
from skopt.plots import plot_evaluations
from skopt.plots import plot_objective
```

seem to fail if I'm only optimizing wrt a single variable
```
/Users/cranmer/anaconda/lib/python3.5/site-packages/skopt/plots.py in plot_objective(result, levels, n_points, n_samples, zscale)
    305         for j in range(space.n_dims):
    306             if i == j:
--> 307                 xi, yi = partial_dependence(space, result.models[-1], i,
    308                                             j=None,
    309                                             sample_points=rvs_transformed,

IndexError: list index out of range
```

**Comment by betatim** [comment]
Should definitely give a more useful error message. As well as special casing the way things are displayed for a 1D space (eg no need for partial dependence plots).

**Comment by Young-Todd** [comment]
I am running into the same error when calling `plot_objective()` but where my number of dimensions is 4:

![plot_error](https://user-images.githubusercontent.com/16848331/26945574-2cff0076-4c5a-11e7-9dd7-e9a607868634.png)

**Comment by davenovelli** [comment]
I'm getting the same, because result.models is an empty list:

```
In [119]: res_fm.models
Out[119]: []
```

**Comment by Young-Todd** [comment]
I am also getting an empty list from `.models.`

**Comment by glouppe** [comment]
How many calls have you made? One needs to have n_calls > n_random_starts
for building at least one surrogate model.

**Comment by Young-Todd** [comment]
Making sure that n_calls > n_random_starts fixed the problem for me, thank you!

**Comment by davenovelli** [comment]
Once I increased the number of calls it started working. Thanks!

**Comment by betatim** [comment]
Let's keep it open as the original problem isn't fixed yet (one dimensional spaces don't plot well)
