### ISSUE TITLE
Preconfigured base_estimators

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#390]
When using `Optimizer` it is a bit tedious to configure the `base_estimator` every time. Thoughts on us providing some of the estimators used in `*_minimize` as something users can access when building their own optimizer?

I'd find it useful.

**Comment by glouppe** [comment]
+1

See also #338

**Comment by betatim** [comment]
Something like `from skopt.estimators import GPWithCategories`?

**Comment by MechCoder** [comment]
We can also use just strings, `base_estimator="gp"` etc where the strings correspond to the default estimators in the respective minimize functions.

**Comment by glouppe** [comment]
+1 for Manoj's suggestion. Simple and easy-to-use.

**Comment by betatim** [comment]
+1 for strings to configure things. However I would still like to have something that helps take up some of the boilerplate when creating my own base estimator. It is mostly the same as the default but has a different kernel...or some such. So if we can expose the estimators that `base_estimator='gp'` gives you as something the user can call that would be nice.

**Comment by MechCoder** [comment]
What are you looking for in addition to importing from `skopt.learning`?

**Comment by betatim** [comment]
```python
from skopt import Optimizer
from skopt.learning import GaussianProcessRegressor
from skopt.learning.gaussian_process.kernels import ConstantKernel
from skopt.learning.gaussian_process.kernels import Matern

cov_amplitude = ConstantKernel(1.0, (0.01, 1000.0))
other_kernel = Matern(
    length_scale=np.ones(1),
    length_scale_bounds=[(0.01, 100)],
    nu=2.5)
base_estimator = GaussianProcessRegressor(
    kernel=cov_amplitude * other_kernel,
    normalize_y=True, alpha=0.0, noise="gaussian",
    n_restarts_optimizer=2)
optimizer = Optimizer([(0., 2*np.pi)], base_estimator, n_random_starts=5)
```

I ended up copy&pasting this code to get started. I think cutting down on arguments to type would already be good or something like this
```python
est = default_gp_estimator(kernel=my_kernels, n_restarts_optimizer=4)
optimizer = Optimizer([(0., 2*np.pi)], base_estimator, n_random_starts=5)
```
similarly for trees.

**Comment by MechCoder** [comment]
I'm missing something but you still have to type out `my_kernels`, is it not?

**Comment by betatim** [comment]
Yes, for my uses it is the kernel that gets changed around but all the options to `GaussianProcessRegressor` stay the same.

I think if we move the few lines that create the base estimators into a function that users can call instead of having it in `base_minimize` and co then I'd already be happy and I reckon our code would get more readable as well.

**Comment by MechCoder** [comment]
Sure +1. For some reason, I thought `default_gp_estimator` to be a class and not a function in your example.

**Comment by glouppe** [comment]
Tagging this for 0.4. This issue becomes more and more frequent as code grows.

**Comment by MechCoder** [comment]
ok, working on it now.
