### ISSUE TITLE
Unintuitive deduction of dimension type 

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#391]
```python
optimizer = Optimizer([(0, 1.124124)], base_estimator, n_random_starts=5)
```

to me it is wrong that this would create an `Integer` dimension. We should check if both or any of the limits is a float and then create a `Continous` dimension.

**Comment by MechCoder** [comment]
:-/

**Comment by betatim** [comment]
Given how much  ambiguity there is in trying to guess the correct space type, should we a) stop supporting it and ask for explicit `space.Integer`, etc or b) try to guess but in cases we know are ambiguous print a warning stating what we deduced?

**Comment by glouppe** [comment]
I think the simplest rule should be to not downcast in case of doubt.
Therefore impose Real if one of the bounds is float.

Or alternatively, assume Real always by default, unless bounds are
explicitly given as Integer.

(sent from my phone)

**Comment by mirca** [comment]
Summoning the second statement of The Zen of Python, which says: "Explicit is better then implicit" , I would say ``a) stop supporting it and ask for explicit space.Integer`` looks a slightly better (though not perfect) choice.

I also think ``a)``:
1. Makes the code more readable
2. Gets rid of ambiguity
3. Makes output cleaner (no need to raise warnings in case of ambiguity, etc)

**Comment by betatim** [comment]
The downside of "explicit" is that it increases the amount of typing required for simple cases (simple should be simple).

**Comment by MechCoder** [comment]
@mirca Nice argument. But unfortunately it goes against the first statement of the Zen of Python which states, "Beautiful is better than ugly" :p 

Jokes apart, We can just list out all the cases and handle them on a case-by-case basis.

1. Greater than 3 -> `Categorical`
2. When equal to 3:
    Third argument either "uniform" or "log-uniform" -> `Real`
    Else -> `Categorical`
3. When equal to 2:
    Atleast one is string -> `Categorical`
    Else atleast one is float -> `Real`
    Else -> `Integer`

Did I miss anything?

**Comment by mirca** [comment]
@MechCoder hahaha =)

I don't think you missed anything :)
