### ISSUE TITLE
Difference of gp_minimize and surrogate model optimize

### ISSUE THREAD

**Issue by TsingQAQ** [scikit-optimize/scikit-optimize#392]
Hi there,

Thanks for your lovely tool, this is neither a bug report nor any feature request.

I a beginner and searching for a tool to perform surrogate model based optimization,like MATLAB [DACE](http://www2.imm.dtu.dk/projects/dace/dace.pdf) toolbox, I have limited knowledge about Kriging, though when I see this bayesian optimization toolbox, I'm a little bit confused: What is the difference and relationships of Kriging based optimization and bayesian optimization? 

At first sight they both use gauss process, build a surrogate model and optimize through cheap function(e.g acquisition function), and sample new points(EI, PI, MSP etc) to make model more precise or for better values. Then what are their difference?

Really hope that someone could give me some intuitive explanations. Thanks in advance.

**Comment by betatim** [comment]
I think that bayesian optimisation, sequential model based optimisation and kriging are the names used in different domains for the same/(very) similar ideas.

**Comment by TsingQAQ** [comment]
Thanks @betatim , 
    So if that is the case, they'll also have similar/same performance on some numerical benchmark functions ?(e.g [Rastrigin](https://en.wikipedia.org/wiki/Rastrigin_function),  [Rosenbrock](https://en.wikipedia.org/wiki/Rosenbrock_function), etc)

**Comment by MechCoder** [comment]
yes!
