### ISSUE TITLE
`dummy_minimize` with ask and tell?

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#406]
Just realized this, does the current API allow one to use random search with the ask and tell API? (in a user-friendly way)

**Comment by betatim** [comment]
Only in a hacky way by never calling `tell` as that will (after #381) forever return random points.

**Comment by MechCoder** [comment]
The first step would be to make `base_minimize` default to random_search when `base_estimator` is None. Once this is done, it should be quite straightforward to extend this to the Optimizer API.

**Comment by betatim** [comment]
Should we use `base_estimator=None` to mean "return random points forever" in `Optimizer` then? I think I like it. An alternative could be to set `n_initial_points=-1`

**Comment by MechCoder** [comment]
I would suggest `base_estimator=None` or maybe `base_estimator="random"`

**Comment by iaroslav-ai** [comment]
I would prefer `base_estimator="random"` as then it is quite explicit

**Comment by glouppe** [comment]
or `base_estimator="dummy"` for name consistency?
