### ISSUE TITLE
Demo of using skopt "ask-and-tell" API for multi-armed bandit problems

### ISSUE THREAD

**Issue by Naereen** [scikit-optimize/scikit-optimize#407]
Hi,
For my research, I wrote [this small notebook](http://perso.crans.org/besson/phd/notebooks/BlackBox_Bayesian_Optimization_for_Bandit_problems.html), showing how to use the (awesome) ["ask-and-tell"](https://scikit-optimize.github.io/notebooks/ask-and-tell.html) API for skopt `Optimizer`s.
It shows that it is easy to compare a Black-Box Bayesian optimization algorithm, here [`RandomForestRegressor`](https://scikit-optimize.github.io/learning/index.html#skopt.learning.RandomForestRegressor), on [Multi-armed bandits problems](https://en.wikipedia.org/wiki/Multi-armed_bandit) :slot_machine:. It is compared against classical online algorithms like [UCB](http://sbubeck.com/SurveyBCB12.pdf) and [Thompson sampling](https://en.wikipedia.org/wiki/Thompson_sampling).

I don't know if it can be interesting for `skopt`'s documentation, but I wanted to let you know. :sparkles:

If you want to include it / point to it, don't hesitate to ask me for rewriting or cleaning or improving the notebook! The most important part is [here](http://perso.crans.org/besson/phd/notebooks/BlackBox_Bayesian_Optimization_for_Bandit_problems.html#Implementation) :hammer_and_wrench:

Thanks :smiley:.

**Comment by betatim** [comment]
I think we need more examples and narrative documentation. So I think we should add it to the examples section. Is there someone around who knows enough about multi-arm bandits and the like to judge the content?

**Comment by betatim** [comment]
After a first read through I think we should include a shortened version in the docs and link to the long version.

**Comment by Naereen** [comment]
Hi,
I agree, and this long version uses a toolbox I am working on for which a doc is already online (http://banditslilian.gforge.inria.fr/) but the code itself is not (yet) open-source.

I will write a smaller version, with manual implementation of UCB and Thompson Sampling, as short as possible, and try to make it self-contained.

**Comment by betatim** [comment]
Ok. Making it self contained is good, especially if it otherwise involves code that people can't get :) We should find someone who understands both SMBO and the more classic multi arm bandit methods so we have some kind of sanity check on the comparisons (comparing A with B almost always upsets someone if you aren't careful :) )

**Comment by Naereen** [comment]
Here, on that small notebook, I compare:
- "very slow" Black Box Bayesian optimization,
- against "quick" online bandit algorithms (state-of-the-art),

Both perform almost as well, the Bayesian optimization being slightly better (on some toy problem) but really slower.

**Comment by MechCoder** [comment]
Thanks a lot for the highly detailed notebook. I am not too familiar with multi-arm bandit methods either but upon a quick read, I find that the goal of multi-armed bandits is to minimize the expected reward after n iterations, while bayesian optimisation finds the argmin of the expensive function. Both seem to solve different problems right?

Or is the rationale that inspite of SMBO solving a different problem, it performs as well?

**Comment by Naereen** [comment]
@MechCoder Indeed the Multi-Armed bandit problem is a reinforcement learning problem where the task is the maximize the expected reward (or minimize the regret) upon an (unknown) horizon n. This is essentially done by finding the best arm and not pulling all the sub-optimal arms. And here the Bayesian optimization task aims finding the optimal arm, by trying all of them, which will result in a small regret also.

I think what was interesting is to show that black box Bayesian optimization can also be applied to reinforcement learning experiments, even if the cost in terms of computational complexity is not worth the improvement in terms of rewards gain / regret diminution (as `BlackBoxOpt` performs indeed way better than state-of-the-art Thompson Sampling or klUCB on the basic examples I considered).

> I am re-running the experiments with a longer horizon and more repetitions (reduce noise in the plots), and after I will rewrite it more concisely to be self-contained (and only present one experiment).
