### ISSUE TITLE
Store name for each dimension

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#424]
It would be useful to be able to give a name to a dimension, for plotting and other bookkeeping purposes mainly. We could also use it in https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/utils.py#L322 and friends.

I'd propose the following API: `Dimension(..., name=None)` so that existing code keeps working. I'd also not allow people setting this name via the "inferring things" interface.

**Comment by iaroslav-ai** [comment]
I think this is a great idea. Should actually simplify a few things.

**Comment by mirca** [comment]
I guess one can use something like `self.__class__.__name__`, for example:
```
>>> from skopt import space
>>> unit_real = space.Real(low=0, high=1)
>>> unit_real.__class__.__name__
'Real'
```
Is that useful for the plotting purposes that you have in mind?

**Comment by iaroslav-ai** [comment]
I think what @betatim has in mind is a situation where you can give different names to dimensions of same type. This can be used then to convert from list of dimensions to dictionary more easier (this is used in BayesSearchCV).

**Comment by betatim** [comment]
Nods, I was thinking of naming dimensions for debugging/readability/plotting purposes, so something like: `space.Real(0, 1, name='learning rate')` or `space.Integer(0, 100, name='number of trees')`.
