### ISSUE TITLE
Update README.md with ask-and-tell example

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#425]
Hi,

I think it would be good to add a quick ask-and-tell example to the README.md. This is something quite unique about scikit-optimize that we should highlight more. 

Also, not sure why the README now includes twice the CircleCI badge.

**Comment by betatim** [comment]
> Also, not sure why the README now includes twice the CircleCI badge.

I think we made a mistake during the conversion to restructured text.
