### ISSUE TITLE
Update hyper-parameter example notebook

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#427]
Now that we have `BayesSearchCV` we should update/cross link the bayes search CV example notebook and then hyper-parameter optimisation one.

As part of this we should also change the name of the searchcv notebook so it renders more like the others on our webpage:

<img width="243" alt="screen shot 2017-07-10 at 09 06 02" src="https://user-images.githubusercontent.com/1448859/28006330-15ac551e-654f-11e7-9c5b-7ddef051fb37.png">

**Comment by iaroslav-ai** [comment]
Ah did not know about that. Will fix.

**Comment by betatim** [comment]
Didn't realise either until I looked at the webpage and was wondering what the searchcv link was :)
