### ISSUE TITLE
Sphinx based documentation

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#428]
Thoughts on switching to sphinx?

Our current documentation system has served us well so far so switching isn't the highest priority. For me personally it would be easier to use sphinx (because other projects use it, so one less tool to use) and we could maybe remove some of the documentation from `skopt.__doc__` etc. There are also nice utilities like sphinx-gallery which people will recognise from other projects.

The reason I am thinking about documentation is that I think we need to structure our examples a bit better/add some links and narrative that tell new people in which order to read them.

Thoughts?

**Comment by glouppe** [comment]
No objection on my side. If you have experience with Sphinx and could setup the doc with it, then let's go for it! 

Also, Sphinx is more widely adopted than our hackish doc builder, which means it should be easier to maintain (by us and future us).
