### ISSUE TITLE
Cannot import 'BayesSearchCV'

### ISSUE THREAD

**Issue by skycrazer** [scikit-optimize/scikit-optimize#429]
When importing BayesSearchCV I get the following error:

from skopt import BayesSearchCV
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-c612d67a6b4a>", line 1, in <module>
    from skopt import BayesSearchCV
ImportError: cannot import name 'BayesSearchCV'

Im using Python 3.5 with Pycharm, Anaconda.

Any solutions to that? Appreciate any help.

**Comment by iaroslav-ai** [comment]
Did you install using pip? If yes, then try to install development version:
```
git clone https://github.com/scikit-optimize/scikit-optimize.git
cd scikit-optimize
pip install -e.
```

**Comment by iaroslav-ai** [comment]
Hmm sorry, was a bit in a rush, did not see that you use Anaconda. Maybe something like [this](https://stackoverflow.com/questions/19042389/conda-installing-upgrading-directly-from-github) could help to install the latest version of the code (but I do not use Anaconda myself, so not sure). 
The BayesSearchCV was added only recently, so the code in the repo might not be available in the online packages of scikit-optimize. This will be updated to include the most recent code soon.

**Comment by skycrazer** [comment]
Actually I tried 
"git clone https://github.com/scikit-optimize/scikit-optimize.git
cd scikit-optimize
pip install -e." within git bash. 
I get the following error.. not welcoming :-(

> "### SK@SK-PC MINGW64 ~/scikitoptimize/scikit-optimize (master)
> $ pip install -e.
> Obtaining file:///C:/Users/SK/scikitoptimize/scikit-optimize
> Requirement already satisfied: numpy in c:\program files\anaconda3\lib\site-pack                                                                                                                                  ages (from scikit-optimize==0.4.dev0)
> Requirement already satisfied: scipy in c:\program files\anaconda3\lib\site-pack                                                                                                                                  ages (from scikit-optimize==0.4.dev0)
> Requirement already satisfied: scikit-learn>=0.18 in c:\program files\anaconda3\                                                                                                                                  lib\site-packages (from scikit-optimize==0.4.dev0)
> Collecting scikit-garden (from scikit-optimize==0.4.dev0)
>   Using cached scikit-garden-0.1.3.tar.gz
> Requirement already satisfied: matplotlib in c:\program files\anaconda3\lib\site                                                                                                                                  -packages (from scikit-optimize==0.4.dev0)
> Requirement already satisfied: cython in c:\program files\anaconda3\lib\site-pac                                                                                                                                  kages (from scikit-garden->scikit-optimize==0.4.dev0)
> Requirement already satisfied: six>=1.10 in c:\program files\anaconda3\lib\site-                                                                                                                                  packages (from matplotlib->scikit-optimize==0.4.dev0)
> Requirement already satisfied: python-dateutil in c:\program files\anaconda3\lib                                                                                                                                  \site-packages (from matplotlib->scikit-optimize==0.4.dev0)
> Requirement already satisfied: pytz in c:\program files\anaconda3\lib\site-packa                                                                                                                                  ges (from matplotlib->scikit-optimize==0.4.dev0)
> Requirement already satisfied: cycler>=0.10 in c:\program files\anaconda3\lib\si                                                                                                                                  te-packages (from matplotlib->scikit-optimize==0.4.dev0)
> Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in c:\pr                                                                                                                                  ogram files\anaconda3\lib\site-packages (from matplotlib->scikit-optimize==0.4.d                                                                                                                                  ev0)
> Building wheels for collected packages: scikit-garden
>   Running setup.py bdist_wheel for scikit-garden: started
>   Running setup.py bdist_wheel for scikit-garden: finished with status 'error'
>   Complete output from command "c:\program files\anaconda3\python.exe" -u -c "im                                                                                                                                  port setuptools, tokenize;__file__='C:\\Users\\SK\\AppData\\Local\\Temp\\pip-bui                                                                                                                                  ld-jhlmczyw\\scikit-garden\\setup.py';f=getattr(tokenize, 'open', open)(__file__                                                                                                                                  );code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'ex                                                                                                                                  ec'))" bdist_wheel -d C:\Users\SK\AppData\Local\Temp\tmp26vm066npip-wheel- --pyt                                                                                                                                  hon-tag cp35:
>   Appending skgarden.mondrian.tree configuration to skgarden.mondrian
>   Ignoring attempt to set 'name' (from 'skgarden.mondrian' to 'skgarden.mondrian                                                                                                                                  .tree')
>   Appending skgarden.mondrian.ensemble configuration to skgarden.mondrian
>   Ignoring attempt to set 'name' (from 'skgarden.mondrian' to 'skgarden.mondrian                                                                                                                                  .ensemble')
>   Appending skgarden.mondrian configuration to skgarden
>   Ignoring attempt to set 'name' (from 'skgarden' to 'skgarden.mondrian')
>   Appending skgarden.quantile configuration to skgarden
>   Ignoring attempt to set 'name' (from 'skgarden' to 'skgarden.quantile')
>   Appending skgarden configuration to
>   Ignoring attempt to set 'name' (from '' to 'skgarden')
>   running bdist_wheel
>   running build
>   running config_cc
>   unifing config_cc, config, build_clib, build_ext, build commands --compiler op                                                                                                                                  tions
>   running config_fc
>   unifing config_fc, config, build_clib, build_ext, build commands --fcompiler o                                                                                                                                  ptions
>   running build_src
>   build_src
>   building extension "skgarden.mondrian.tree._tree" sources
>   building extension "skgarden.mondrian.tree._splitter" sources
>   building extension "skgarden.mondrian.tree._criterion" sources
>   building extension "skgarden.mondrian.tree._utils" sources
>   build_src: building npy-pkg config files
>   running build_py
>   creating build
>   creating build\lib.win-amd64-3.5
>   creating build\lib.win-amd64-3.5\skgarden
>   copying skgarden\forest.py -> build\lib.win-amd64-3.5\skgarden
>   copying skgarden\setup.py -> build\lib.win-amd64-3.5\skgarden
>   copying skgarden\__init__.py -> build\lib.win-amd64-3.5\skgarden
>   creating build\lib.win-amd64-3.5\skgarden\mondrian
>   copying skgarden\mondrian\setup.py -> build\lib.win-amd64-3.5\skgarden\mondria                                                                                                                                  n
>   copying skgarden\mondrian\__init__.py -> build\lib.win-amd64-3.5\skgarden\mond                                                                                                                                  rian
>   creating build\lib.win-amd64-3.5\skgarden\quantile
>   copying skgarden\quantile\ensemble.py -> build\lib.win-amd64-3.5\skgarden\quan                                                                                                                                  tile
>   copying skgarden\quantile\setup.py -> build\lib.win-amd64-3.5\skgarden\quantil                                                                                                                                  e
>   copying skgarden\quantile\tree.py -> build\lib.win-amd64-3.5\skgarden\quantile
>   copying skgarden\quantile\utils.py -> build\lib.win-amd64-3.5\skgarden\quantil                                                                                                                                  e
>   copying skgarden\quantile\__init__.py -> build\lib.win-amd64-3.5\skgarden\quan                                                                                                                                  tile
>   creating build\lib.win-amd64-3.5\skgarden\mondrian\ensemble
>   copying skgarden\mondrian\ensemble\forest.py -> build\lib.win-amd64-3.5\skgard                                                                                                                                  en\mondrian\ensemble
>   copying skgarden\mondrian\ensemble\setup.py -> build\lib.win-amd64-3.5\skgarde                                                                                                                                  n\mondrian\ensemble
>   copying skgarden\mondrian\ensemble\__init__.py -> build\lib.win-amd64-3.5\skga                                                                                                                                  rden\mondrian\ensemble
>   creating build\lib.win-amd64-3.5\skgarden\mondrian\tree
>   copying skgarden\mondrian\tree\setup.py -> build\lib.win-amd64-3.5\skgarden\mo                                                                                                                                  ndrian\tree
>   copying skgarden\mondrian\tree\tree.py -> build\lib.win-amd64-3.5\skgarden\mon                                                                                                                                  drian\tree
>   copying skgarden\mondrian\tree\__init__.py -> build\lib.win-amd64-3.5\skgarden                                                                                                                                  \mondrian\tree
>   running build_ext
>   No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying fro                                                                                                                                  m distutils
>   customize MSVCCompiler
>   customize MSVCCompiler using build_ext
>   building 'skgarden.mondrian.tree._tree' extension
>   compiling C sources
>   error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C+                                                                                                                                  + Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
> 
>   ----------------------------------------
>   Failed building wheel for scikit-garden
>   Running setup.py clean for scikit-garden
> Failed to build scikit-garden
> Installing collected packages: scikit-garden, scikit-optimize
>   Running setup.py install for scikit-garden: started
>     Running setup.py install for scikit-garden: finished with status 'error'
>     Complete output from command "c:\program files\anaconda3\python.exe" -u -c "                                                                                                                                  import setuptools, tokenize;__file__='C:\\Users\\SK\\AppData\\Local\\Temp\\pip-b                                                                                                                                  uild-jhlmczyw\\scikit-garden\\setup.py';f=getattr(tokenize, 'open', open)(__file                                                                                                                                  __);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, '                                                                                                                                  exec'))" install --record C:\Users\SK\AppData\Local\Temp\pip-hrxull4y-record\ins                                                                                                                                  tall-record.txt --single-version-externally-managed --compile:
>     Appending skgarden.mondrian.tree configuration to skgarden.mondrian
>     Ignoring attempt to set 'name' (from 'skgarden.mondrian' to 'skgarden.mondri                                                                                                                                  an.tree')
>     Appending skgarden.mondrian.ensemble configuration to skgarden.mondrian
>     Ignoring attempt to set 'name' (from 'skgarden.mondrian' to 'skgarden.mondri                                                                                                                                  an.ensemble')
>     Appending skgarden.mondrian configuration to skgarden
>     Ignoring attempt to set 'name' (from 'skgarden' to 'skgarden.mondrian')
>     Appending skgarden.quantile configuration to skgarden
>     Ignoring attempt to set 'name' (from 'skgarden' to 'skgarden.quantile')
>     Appending skgarden configuration to
>     Ignoring attempt to set 'name' (from '' to 'skgarden')
>     running install
>     running build
>     running config_cc
>     unifing config_cc, config, build_clib, build_ext, build commands --compiler                                                                                                                                   options
>     running config_fc
>     unifing config_fc, config, build_clib, build_ext, build commands --fcompiler                                                                                                                                   options
>     running build_src
>     build_src
>     building extension "skgarden.mondrian.tree._tree" sources
>     building extension "skgarden.mondrian.tree._splitter" sources
>     building extension "skgarden.mondrian.tree._criterion" sources
>     building extension "skgarden.mondrian.tree._utils" sources
>     build_src: building npy-pkg config files
>     running build_py
>     creating build
>     creating build\lib.win-amd64-3.5
>     creating build\lib.win-amd64-3.5\skgarden
>     copying skgarden\forest.py -> build\lib.win-amd64-3.5\skgarden
>     copying skgarden\setup.py -> build\lib.win-amd64-3.5\skgarden
>     copying skgarden\__init__.py -> build\lib.win-amd64-3.5\skgarden
>     creating build\lib.win-amd64-3.5\skgarden\mondrian
>     copying skgarden\mondrian\setup.py -> build\lib.win-amd64-3.5\skgarden\mondr                                                                                                                                  ian
>     copying skgarden\mondrian\__init__.py -> build\lib.win-amd64-3.5\skgarden\mo                                                                                                                                  ndrian
>     creating build\lib.win-amd64-3.5\skgarden\quantile
>     copying skgarden\quantile\ensemble.py -> build\lib.win-amd64-3.5\skgarden\qu                                                                                                                                  antile
>     copying skgarden\quantile\setup.py -> build\lib.win-amd64-3.5\skgarden\quant                                                                                                                                  ile
>     copying skgarden\quantile\tree.py -> build\lib.win-amd64-3.5\skgarden\quanti                                                                                                                                  le
>     copying skgarden\quantile\utils.py -> build\lib.win-amd64-3.5\skgarden\quant                                                                                                                                  ile
>     copying skgarden\quantile\__init__.py -> build\lib.win-amd64-3.5\skgarden\qu                                                                                                                                  antile
>     creating build\lib.win-amd64-3.5\skgarden\mondrian\ensemble
>     copying skgarden\mondrian\ensemble\forest.py -> build\lib.win-amd64-3.5\skga                                                                                                                                  rden\mondrian\ensemble
>     copying skgarden\mondrian\ensemble\setup.py -> build\lib.win-amd64-3.5\skgar                                                                                                                                  den\mondrian\ensemble
>     copying skgarden\mondrian\ensemble\__init__.py -> build\lib.win-amd64-3.5\sk                                                                                                                                  garden\mondrian\ensemble
>     creating build\lib.win-amd64-3.5\skgarden\mondrian\tree
>     copying skgarden\mondrian\tree\setup.py -> build\lib.win-amd64-3.5\skgarden\                                                                                                                                  mondrian\tree
>     copying skgarden\mondrian\tree\tree.py -> build\lib.win-amd64-3.5\skgarden\m                                                                                                                                  ondrian\tree
>     copying skgarden\mondrian\tree\__init__.py -> build\lib.win-amd64-3.5\skgard                                                                                                                                  en\mondrian\tree
>     running build_ext
>     No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying f                                                                                                                                  rom distutils
>     customize MSVCCompiler
>     customize MSVCCompiler using build_ext
>     building 'skgarden.mondrian.tree._tree' extension
>     compiling C sources
>     error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual                                                                                                                                   C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
> 
>     ----------------------------------------
> Command ""c:\program files\anaconda3\python.exe" -u -c "import setuptools, token                                                                                                                                  ize;__file__='C:\\Users\\SK\\AppData\\Local\\Temp\\pip-build-jhlmczyw\\scikit-ga                                                                                                                                  rden\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replac                                                                                                                                  e('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --recor                                                                                                                                  d C:\Users\SK\AppData\Local\Temp\pip-hrxull4y-record\install-record.txt --single                                                                                                                                  -version-externally-managed --compile" failed with error code 1 in C:\Users\SK\A                                                                                                                                  ppData\Local\Temp\pip-build-jhlmczyw\scikit-garden\"

**Comment by iaroslav-ai** [comment]
Hummm
Yeah seems to be something with compilation of scikit-garden. 
It also seems that you are missing [Microsoft Visual C++ 14.0](http://landinghub.visualstudio.com/visual-cpp-build-tools). Did you try to install it?

**Comment by skycrazer** [comment]
I installed it again, also Visual C++... It simply does not work when installing from the github repo.. too many errors, particularly compilation of scikit-garden.

Importing scopt works when running "pip install scikit-optimize".. However BayesSearchCV (the most important function :-)) does not work.

"Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.
IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
PyDev console: using IPython 5.1.0
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\Users\\SK\\PYCHARM', 'C:/Users/SK/PYCHARM'])
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
from skopt.space import Real, Categorical, Integer
Backend Qt5Agg is interactive backend. Turning interactive mode on.
from skopt import BayesSearchCV
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-c612d67a6b4a>", line 1, in <module>
    from skopt import BayesSearchCV
ImportError: cannot import name 'BayesSearchCV'"

Maybe somebody can update the scikit-optimize version you get by simply calling "pip install scikit-optimize". Would that be possible? Thanks.

**Comment by iaroslav-ai** [comment]
Hmm sorry about that. The version of the software was to 0.4 just very recently,  (in #421), so update on pip and other places should come soon. 
@MechCoder do you know what could be going on with scikit-garden?

**Comment by skycrazer** [comment]
Thanks for you effort. Im really looking forward to using the package.

**Comment by betatim** [comment]
The latest version of scikit-optimize on pypi does not depend on scikit-garden yet. We split things only after the release. So that is probably why installing from pypi works, but installing the latest version of scikit-optimize fails.

scikit-garden contains C code so unfortunately you need a working compiler to install it.

**Comment by HugoDLopes** [comment]
Hi, after making the `pip install scikit-optimize` I get:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
----> 8 from skopt import BayesSearchCV

ImportError: cannot import name 'BayesSearchCV'

Any work-around this?

**Comment by glouppe** [comment]
BayesSearchCV is not yet available on pip. It will be shipped with next
release of scikit-optimize, which should happen soon.

**Comment by jkquijas** [comment]
Sweet! No wonder I could't use BayesSearchCV. @glouppe awesome presentation in Amsterdam btw. Found out about this great library in the youtube video.

**Comment by iaroslav-ai** [comment]
Close due to #486
