### ISSUE TITLE
Build static documentation

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#43]
To consolidate the package, we should generate a static version of the documentation. 

I recently found https://github.com/BurntSushi/pdoc which seems to be quite nice and easy for that purpose.

**Comment by glouppe** [comment]
Hi!

I recently setup http://diana-hep.org/carl/ with automated deployment through Travis. 

I could do the same here if you like it.

**Comment by MechCoder** [comment]
Hey! Would be great if you could do that :-)

**Comment by glouppe** [comment]
Then for this, I think it would be best if the project was moved to its own organization. What do you think?

**Comment by betatim** [comment]
`scikit-optimize/scikit-optimize` ?

**Comment by MechCoder** [comment]
We should do that? Do you want me to do it?

**Comment by glouppe** [comment]
Yep, that would be nice. Then I'll proceed with the static documentation.

**Comment by betatim** [comment]
I think @MechCoder is the right person to do it.

ps. missed my chance to smuggle some english spelling into the python ecosystem haven't I.

**Comment by glouppe** [comment]
> Do you want me to do it? 

Actually, only you can do it because we dont have ownership over your repo :)

**Comment by glouppe** [comment]
Fixed by #63

**Comment by MechCoder** [comment]
This looks great. Thanks a lot for all your work.

**Comment by glouppe** [comment]
Note that I had to bend a bit the docstring format, because it is Markdown-based only. We should be aware that the format is therefore now a bit different than docstring format in scikit-learn.
