### ISSUE TITLE
Reduce `n_iter` in BayesSearchCV

### ISSUE THREAD

**Issue by MechCoder** [scikit-optimize/scikit-optimize#438]
In comparison, the scikit-learn equivalent RandomizedSearchCV (http://scikit-learn.org/dev/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#sklearn.model_selection.RandomizedSearchCV) has `n_iter=10` by default.

**Comment by iaroslav-ai** [comment]
Hmm I understand that you mean that this way we are more consistent with sklearn. But does this make sense actually? 10 calls does not seem like a large enough number of iterations to reach to interesting parameter configs for non - trivial models (not to mention that we on average initialize for 10 calls with random params). So a naive user might not figure out n_iter to set it to large number, and then wander why results are not very good. This especially might happen, if one switches from GridSearchCV, where you do not specify n_iter, and hence one might even forget to set it. What do you think?

**Comment by MechCoder** [comment]
Lol yes, I never meant to reduce it to 10 but to something smaller than 128.

**Comment by betatim** [comment]
For `*_minimize` the default number of calls is 100, so maybe for this we go for 50 or so?

We could also scale it with the number of dimensions?

**Comment by iaroslav-ai** [comment]
50 is fine by me.
I propose to set it to 50 for now, and think about possible scaling strategies later.

**Comment by iaroslav-ai** [comment]
Hmm intended to open PR, but somehow pressed the wrong button :( 
Now `n_iter=50`. If no further comments will arise, I will close this issue later.

**Comment by betatim** [comment]
Don't add commits to `master` :) I have my `origin` remote setup as `https://github.com/...` and with 2FA this means I can't push there which helps avoid accidentally `git push -f`'ing. If I do really want to push to `origin` I need to dig out a personal access token to do so. Works quite well as I almost never have to push here directly anyway.

**Comment by iaroslav-ai** [comment]
Super sorry about that! I actually used github.com UI, and there you have 2 options - commit to master or create PR, and default is to commit to master, I somehow forgot to switch to the latter :(

**Comment by betatim** [comment]
No worries.

UIs ... kids these days :)
