### ISSUE TITLE
UserWarning: The objective has been evaluated at this point before.   warnings.warn("The objective has been evaluated "

### ISSUE THREAD

**Issue by ashish-ram** [scikit-optimize/scikit-optimize#441]
Hi, 
I am testing some simple functions with skopt. I could run the example in the documentation successfully, but with the following simple function, i think it is not working as expected. What is the meaning of this warning ? I am clueless about which settings to tune in this case ?
````
from skopt import gp_minimize
import numpy as np
import matplotlib.pyplot as plt

def fun1D(x):
    return np.power(6*x[0]-2,2)*np.sin(12*x[0]-4)
from skopt import gp_minimize

res = gp_minimize(fun1D,              # the function to minimize
                  [(0, 1.0)],         # the bounds on each dimension of x
                  acq_func="EI",      # the acquisition function
                  n_calls=30,         # the number of evaluations of f 
                  n_random_starts=5,  # the number of random initialization points
                  random_state=123)   # the random seed
```
`

**Comment by betatim** [comment]
What is happening is that the minimizer keeps suggesting points at which the objective has already been evaluated. You could print out the argument `x` in `fun1D` to see what is happening. This usually means that the minimization has converged and the optimizer keeps suggesting the same point (the optimum).

**Comment by ashish-ram** [comment]
Hi @betatim 
Yes, infact that is what is happening. I plotted the convergence curve and it is flat. My question was how to get rid of such situation, is there any tuning parameter which I am missing, because clearly is it not the minima. It is actually the very first function evaluation and the algorithm gets stuck at the same point.

**Comment by betatim** [comment]
In older versions of scikit-optimize the deduction of the type of a dimension in the optimisation space wasn't very smart. What happened often is the user wanted a `Real` dimension but ended up with a `Integer`. This often leads to warnings like this. In this case there would only be two possible values 0 and 1. 

If you are using v0.3 then try making both bounds a float or specify explicitly the type of the dimension with:
`space = skopt.space.Space([skopt.space.Real(low=0, high=1)])`

**Comment by ashish-ram** [comment]
thanks for the help @betatim . got it sorted!!

**Comment by civilinformer** [comment]
I am getting the same error but I dont think the solution given applies. Could you please reopen this issue?

**Comment by civilinformer** [comment]
`dimensions = [(0.001,1000.0, 'log-uniform'), (0.001,1000.0, 'log-uniform'), (0.001,1000.0, 'log-uniform' ), [5,6,7,8],(10.,1000.,'log-uniform')]
res = gp_minimize(cross_validate, dimensions, base_estimator=None, n_calls=40, n_random_starts=3, acq_func='gp_hedge', 
        acq_optimizer='auto', x0=[5.78, 1.0, 0.1,7,200.], random_state=iseed, verbose=True, callback=None, n_points=10000, n_restarts_optimizer=5, xi=0.01,             
        kappa=1.96, noise='gaussian', n_jobs=1)
`

**Comment by MaxGhenis** [comment]
I'm also getting this when it's clearly not converged yet.

**Comment by civilinformer** [comment]
Was there a fix? I started to experience this issue again when I handed it lists of previously evaluated points using gbtr_minimize. For some reason, it picks some of these previously evaluated points again. Most of the dimensions are real, so why should it repeat itself?
