### ISSUE TITLE
Documentation Notebook Running Error: ask and tell

### ISSUE THREAD

**Issue by kejiashi** [scikit-optimize/scikit-optimize#442]
It works when specifying to specific optimizers (e.g. "gp_minimize") instead of calling "Optimizer" directly. Not sure if I understand the right procedure. But following the notebook example on [ask-and-tell](https://scikit-optimize.github.io/notebooks/ask-and-tell.html), it raises error at

> opt = Optimizer([(-2.0, 2.0)], "ET", acq_optimizer="sampling")

Error message:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-42-b1fdabe08028> in <module>()
> ----> 1 opt = Optimizer([(-2.0, 2.0)], base_estimator="ET", acq_optimizer="sampling")
> 
> ~/anaconda3/lib/python3.6/site-packages/skopt/optimizer/optimizer.py in __init__(self, dimensions, base_estimator, n_random_starts, acq_func, acq_optimizer, random_state, acq_func_kwargs, acq_optimizer_kwargs)
>     145             else:
>     146                 self._non_cat_inds.append(ind)
> --> 147         self._check_arguments(base_estimator, n_random_starts, acq_optimizer)
>     148 
>     149         self.n_jobs = n_jobs
> 
> ~/anaconda3/lib/python3.6/site-packages/skopt/optimizer/optimizer.py in _check_arguments(self, base_estimator, n_random_starts, acq_optimizer)
>     153         if not is_regressor(base_estimator):
>     154             raise ValueError(
> --> 155                 "%s has to be a regressor." % base_estimator)
>     156         self.base_estimator = base_estimator
>     157 
> 
> ValueError: ET has to be a regressor.
> 

Running environment/pkg version:

> IPython 6.1.0
> IPython.core.release 6.1.0
> PIL 4.1.1
> _csv 1.0
> _ctypes 1.1.0
> _curses b'2.2'
> _decimal 1.70
> argparse 1.1
> cffi 1.10.0
> colorama 0.3.9
> csv 1.0
> ctypes 1.1.0
> ctypes.macholib 1.0
> cycler 0.10.0
> dateutil 2.6.0
> decimal 1.70
> decorator 4.0.11
> distutils 3.6.1
> docutils 0.13.1
> docutils.utils.roman 1.4
> docutils.utils.smartquotes 1.5_1.6: Fri, 27 Jul 2007 07:06:40 -0400
> ipaddress 1.0
> ipykernel 4.6.1
> ipykernel._version 4.6.1
> ipython_genutils 0.2.0
> ipython_genutils._version 0.2.0
> ipywidgets 6.0.0
> ipywidgets._version 6.0.0
> jedi 0.10.2
> json 2.0.9
> jupyter_client 5.0.1
> jupyter_client._version 5.0.1
> jupyter_core 4.3.0
> jupyter_core.version 4.3.0
> logging 0.5.1.2
> matplotlib 2.0.2
> numpy 1.12.1
> numpy.core 1.12.1
> numpy.core.multiarray 3.1
> numpy.core.umath b'0.4.0'
> numpy.core.umath_tests b'0.1'
> numpy.lib 1.12.1
> numpy.linalg._umath_linalg b'0.1.4'
> numpy.matlib 1.12.1
> optparse 1.5.3
> pexpect 4.2.1
> pickleshare 0.7.4
> pkg_resources._vendor.packaging.__about__ 16.7
> pkg_resources._vendor.six 1.10.0
> pkg_resources.extern.appdirs 1.4.0
> pkg_resources.extern.packaging 16.7
> pkg_resources.extern.pyparsing 2.1.8
> pkg_resources.extern.six 1.10.0
> platform 1.0.8
> prompt_toolkit 1.0.14
> ptyprocess 0.5.1
> pygments 2.2.0
> pyparsing 2.1.4
> re 2.2.1
> scipy 0.19.0
> scipy._lib.decorator 4.0.5
> scipy._lib.six 1.2.0
> scipy.integrate._dop b'$Revision: $'
> scipy.integrate._ode $Id$
> scipy.integrate._odepack  1.9 
> scipy.integrate._quadpack  1.13 
> scipy.integrate.lsoda b'$Revision: $'
> scipy.integrate.vode b'$Revision: $'
> scipy.interpolate._fitpack  1.7 
> scipy.interpolate.dfitpack b'$Revision: $'
> scipy.linalg 0.4.9
> scipy.linalg._fblas b'$Revision: $'
> scipy.linalg._flapack b'$Revision: $'
> scipy.linalg._flinalg b'$Revision: $'
> scipy.optimize._cobyla b'$Revision: $'
> scipy.optimize._lbfgsb b'$Revision: $'
> scipy.optimize._minpack  1.10 
> scipy.optimize._nnls b'$Revision: $'
> scipy.optimize._slsqp b'$Revision: $'
> scipy.optimize.minpack2 b'$Revision: $'
> scipy.sparse.linalg.eigen.arpack._arpack b'$Revision: $'
> scipy.sparse.linalg.isolve._iterative b'$Revision: $'
> scipy.special.specfun b'$Revision: $'
> scipy.stats.mvn b'$Revision: $'
> scipy.stats.statlib b'$Revision: $'
> six 1.10.0
> sklearn 0.18.1
> sklearn.base 0.18.1
> sklearn.externals.funcsigs 0.4
> sklearn.externals.joblib 0.10.3
> sklearn.externals.six 1.4.1
> skopt 0.3
> sphinx 1.6.2
> traitlets 4.3.2
> traitlets._version 4.3.2
> urllib.request 3.6
> zlib 1.0
> zmq 16.0.2
> zmq.sugar 16.0.2
> zmq.sugar.version 16.0.2

**Comment by betatim** [comment]
If you installed scikit-optimize via `pip install scikit-optimize` then passing a string isn't yet supported. Take a look at the docstring for `skopt.Optimizer` to confirm that.

To get started with contributing you should create a new conda environment and setup things along the lines of: https://github.com/scikit-optimize/scikit-optimize#development

**Comment by kejiashi** [comment]
Thanks, Tim. This is solved!
