### ISSUE TITLE
Bayesian optimization priors

### ISSUE THREAD

**Issue by Deepblue129** [scikit-optimize/scikit-optimize#446]
For hyper parameter optimization, it's very expensive to run. Assuming you've optimized your hyper parameters once. 

But you add another hyper parameter or change your model a little bit. 

Can you use the previous runs as a prior for Bayesian optimization to help speed up the process?

**Comment by betatim** [comment]
Two options come straight to mind:
* use the previous evaluations as initial points (pass as `x0` and `y0`). If you added a dimension you will have to think about how to assign a value for that
* you can change the distribution from which values are sampled for each dimension of your search space (take a look at the `skopt.space.Real/Integer` classes)

More complex schemes have been discussed (see for example #332) but not yet done.

**Comment by iaroslav-ai** [comment]
From #332 and #325 it seemed like the most simple and yet efficient thing would be to just reuse points with minimal / low values of objective from previous optimization problems as initialization for new ones. One could attempt also to learn one surrogate model for multiple optimization problems, but at least at the time it seemed to lead to models which converge quickly initially, but seem to be overconfident in what space was explored, and hence skip points with good objective values. These results are biased however towards ML domain. Better but more surrogate specific results you can find [in here](https://papers.nips.cc/paper/5086-multi-task-bayesian-optimization.pdf).

Do you have some particular use case in mind maybe?

**Comment by Deepblue129** [comment]
That gives me a better idea of what to do. Thank you!

The use case for me was hyperparameter optimization.
