### ISSUE TITLE
Support creating dimension from numpy rvs?

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#448]
Just noticed that we aren't 100% drop in compatible with `RandomizedSearchCV`:
```python
opt = RandomizedSearchCV(
    SVC(),
    {
        'C': Real(1e-6, 1e+6, 'log-uniform'),  
        'gamma': Real(1e-6, 1e+1, 'log-uniform'),
        'degree': Integer(1, 8),  # integer valued parameter
        'kernel': Categorical(['linear', 'poly', 'rbf']),  # categorical parameter
    },
    n_iter=32
)
```
Well. You can pass just `(low, high)` to `BayesSearchCV` but that doesn't work with `RandomizedSearchCV` (requires objects with a `rvs()`).

Should we add support for converting arbitrary numpy rvs into `Dimension` objects?

**Comment by betatim** [comment]
edit: `RandomizedSearchCV` needs scipy distributions not numpy.

**Comment by glouppe** [comment]
I am -1 for that. Let's not complicate further the API.

In our case, specifying a custom distribution would only be useful for sampling the first random init points. I am not convinced it is worth adding the complexity.

**Comment by betatim** [comment]
It would also be hard to extract limits from the scipy distribution objects. So the user would have to always provide some extra information.

Closing.
