### ISSUE TITLE
lie to the optimizer bug

### ISSUE THREAD

**Issue by Deepblue129** [scikit-optimize/scikit-optimize#454]
Code:
```
optimizer = Optimizer(dimensions=[[64, 128], (4, 1)])
x = optimizer.ask(n_points=4)
```

Note (4, 1) -> (1, 4)  also fails:
```
optimizer = Optimizer(dimensions=[[64, 128], (1, 4)])
x = optimizer.ask(n_points=4)
```

Version:
```
>>> skopt.__version__
'0.4-dev'
```

Traceback:
```
Traceback (most recent call last):
  File "example/tune.py", line 188, in <module>
    main()
  File "example/tune.py", line 171, in main
    x = optimizer.ask(n_points=len(devices))
  File "/usr/local/lib/python3.5/dist-packages/skopt/optimizer/optimizer.py", line 336, in ask
    opt.tell(x, y_lie)  # lie to the optimizer
  File "/usr/local/lib/python3.5/dist-packages/skopt/optimizer/optimizer.py", line 396, in tell
    check_x_in_space(x, self.space)
  File "/usr/local/lib/python3.5/dist-packages/skopt/utils.py", line 192, in check_x_in_space
    % (x, space.bounds))
ValueError: Point ([64, 2]) is not within the bounds of the space ([[64, 126, 252, 512], (4, 1)]).
```

**Comment by betatim** [comment]
Currently there are no checks in either `Real` or `Integer` for the lower bound being lower than the upper bound. So `(4, 1)` leads to `Integer(low=4, high=1)` which then breaks. We should add a check for that.

Is it important for you to specify the bounds in reverse order?

For me
```python
In [1]: import skopt

In [2]: opt = skopt.Optimizer(([64, 128], [1,4]))

In [3]: opt.space
Out[3]: 
Space([Integer(low=64, high=128),
       Integer(low=1, high=4)])

In [4]: opt.ask(n_points=4)
Out[4]: [[86, 3], [65, 1], [124, 2], [67, 3]]
```
runs without problems. I assume from the traceback you posted that you specified a categorical space for the first dimension with entries 64, 126, 252 and 512, that also works for me.

**Comment by Deepblue129** [comment]
Welp.

Specified it in reverse order because the documentation seems to hint at that:
https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/space/space.py#L474

> `In [2]: opt = skopt.Optimizer(([64, 128], [1,4])`

> `optimizer = Optimizer(dimensions=[[64, 128], (1, 4)])`

Looks the difference between your code and mine is I used a `tuple` rather than a `list`.
The documentation notes it should be a tuple ```a `(upper_bound, lower_bound)` tuple (for `Real` or `Integer` dimensions)```

**Comment by betatim** [comment]
Tuple vs list should make no difference.

Fix for the docs in #455

**Comment by Deepblue129** [comment]
Was able to reproduce my error:
```
>>> import skopt
>>> opt = skopt.Optimizer(dimensions=[(True, False)])
>>> x = opt.ask(n_points=4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 336, in ask
    opt.tell(x, y_lie)  # lie to the optimizer
  File "/usr/local/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 396, in tell
    check_x_in_space(x, self.space)
  File "/usr/local/lib/python3.6/site-packages/skopt/utils.py", line 192, in check_x_in_space
    % (x, space.bounds))
ValueError: Point ([1]) is not within the bounds of the space ([(True, False)]).
```

Looks like (True, False) in the wrong order also mess things up.

**Comment by betatim** [comment]
I'd recommend using `skopt.space.Categorical`/`Integer`/`Real` to explicitly specify the type of dimension you want. When a user passes in a list of tuples we try and deduce the type from what the user passed and that is a bit tricky.

In this case the mechanism incorrectly deduces that the user wanted an `Integer` space though you were probably looking for a `Categorical`.

To fix this take a look at https://github.com/scikit-optimize/scikit-optimize/blob/47e3ae545c7f499b029ac56c7ff7dd273af910f9/skopt/space/space.py#L69-L75
