### ISSUE TITLE
sklearn-0.19: deprecation warnings of y_train_mean

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#462]
In sklearn-0.19, the `y_train_mean` of `GaussianProcessorRegressor` has been deprecated. See:
https://github.com/scikit-learn/scikit-learn/blob/ec0dbf0399c4187a1d17e66de17265c67588373f/sklearn/gaussian_process/gpr.py#L153

This results in tons of warnings, as scikit-optimize itself depends on this attribute, at https://github.com/scikit-optimize/scikit-optimize/blob/e08a067abfa759fa60f279eaf2df569bafc79147/skopt/learning/gaussian_process/gpr.py#L305

Reported in #461.

**Comment by glouppe** [comment]
Fixed in #464

**Comment by amueller** [comment]
That seems like a good hot-fix but I'm not sure scikit-optimize wants to rely on private attributes?

**Comment by glouppe** [comment]
> That seems like a good hot-fix but I'm not sure scikit-optimize wants to rely on private attributes?

Previously, this wasn't in a private attribute :(

**Comment by amueller** [comment]
I can't seem to find a discussion of public vs private in https://github.com/scikit-learn/scikit-learn/pull/7846 It looked like there was no compelling reason to leave it public, it definitely needed to be renamed because it didn't end with a trailing underscore. We could still make it public again if there's a good reason, but we should do so quickly then.

**Comment by amueller** [comment]
maybe @jnothman or @tguillemot remember?

**Comment by jnothman** [comment]
I suppose we should have been more careful with it. PR to make it public?

**Comment by jnothman** [comment]
But `y_train_` is stored! Why can't you take the mean yourself at no enormous cost??

**Comment by MechCoder** [comment]
> But y_train_ is stored! Why can't you take the mean yourself at no enormous cost??

+1. How do you feel about sending your first PR to scikit-optimize :p ?

**Comment by jnothman** [comment]
Ah, @MechCoder, there was a time when I watched your every issue, but there's just too much to keep abreast of across projects.
