### ISSUE TITLE
BayesSearchCV docs render poorly

### ISSUE THREAD

**Issue by jnothman** [scikit-optimize/scikit-optimize#468]

**Comment by betatim** [comment]
True, I'd vote to keep them like this as the are mostly "rest" style which is what I am trying to get to in #428 anyway.

**Comment by betatim** [comment]
Do you have an opinion on this @MechCoder?

**Comment by MechCoder** [comment]
Not really, just depends on how fast you would like to release!

**Comment by betatim** [comment]
Release once `BayesSearchCV` works with the new scikit-learn I'd say. Not sure if revamping the documentation would be done by then.

**Comment by holgern** [comment]
Solved by switching to sphinx.
