### ISSUE TITLE
n_random_starts not totally deprecated in base_minimize

### ISSUE THREAD

**Issue by kejiashi** [scikit-optimize/scikit-optimize#469]
In [Optimizer.py](https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/optimizer/optimizer.py#L61), `n_random_starts` is described to be replaced by `n_initial_points`. However in [base.py](https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/optimizer/base.py#L56), this parameter is still in use. Does this need to be unified as well?

**Comment by betatim** [comment]
No, this is on purpose. There is a bit of discussion [here](https://github.com/scikit-optimize/scikit-optimize/pull/381). @MechCoder might also remember some details.

I'll close this, feel free to reopen if you disagree.

**Comment by kejiashi** [comment]
After reading the whole comments, could finally get a sense of what's going on and being fixed. ¯\_(ツ)_/¯ Now it totally makes sense to me about every "number of points" operation within `Optimizer` and `*_minimize`.

The doc string in `Optimizer` is not confusing as it clearly states "If len(x0) < n_initial_points, additional points are sampled at random." But I would suggest similar changes to be reflected in `base.py` as well.

Right now it says,

> * `n_random_starts` [int, default=10]:
>         Number of evaluations of `func` with random points before
>         approximating it with `base_estimator`.

Because the whole depreciation thing in optimizer, it could be clearer if stated as:

> * `n_random_starts` [int, default=10]:
>         Number of evaluations of `func` with random points **to sample**
>         **apart from `x0`** before approximating it with `base_estimator`.

But there's huge possibility that it's just me. :)
