### ISSUE TITLE
skopt cannot compute distance between chosen parameters

### ISSUE THREAD

**Issue by baharian** [scikit-optimize/scikit-optimize#470]
I am using `skopt`'s `BayesSearchCV` for hyper-parameter tuning in a neural network with a number of hidden layers (could be, say, from 3 to 6). The neural network is implemented using Keras (on top of Theano), and I am using Keras' `KerasClassifier()` wrapper which exposes a scikit-learn-like API.

This search is implemented as follows

    n_layers = 3
    hidden_layers_space = [range(5, 30 + 1) for _ in range(n_layers)]
    params_dict = {'num_hidden_layers': Categorical([n_layers]),
                'num_units_hidden': Categorical([element for element in itertools.product(*hidden_layers_space)]), # entire search space for hidden layer sizes
                'dropout_frac': Real(0.05, 0.25),
                'activation': Categorical(['relu', 'selu']),
                'output_activation': Categorical(['sigmoid', 'softmax']),
                'optimization': Categorical(['RMSprop', 'Nadam']),
                'learning_rate': Real(1e-4, 1e-2, prior = 'log-uniform')
                }
    clf = BayesSearchCV(estimator = KerasClassifier(DeepNeuralNetworkClassifier), search_spaces = params_dict, scoring = 'neg_log_loss', cv = CV_folds, error_score = 0, n_iter = 30, verbose = 3, n_jobs = 2)
    clf.fit(DF[DF.columns.drop('quit')].values, reshape_quit_2classes(DF['quit'].values))

where `DeepNeuralNetworkClassifier` is my implementation of a neural network using Keras, and `CV_folds` is a pre-defined set of training and validation datasets. The code runs fine for a while, picking hyper-parameters and training and validating neural networks using these hyper-parameters, but eventually it fails with the following error:

> ---------------------------------------------------------------------------

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-253-d3751eff0065> in <module>()
> ----> 1 perform_Bayesian_CV(p4.users_df_ml, False, '2016-07-03', 3, 2, 'LogLoss', 'NN', 3)
> 
> <ipython-input-252-43420f109966> in perform_Bayesian_CV(df, reshaped, end_date, folds, step_ahead_weeks, scoring, method, n_layers)
>      22     clf = BayesSearchCV(estimator = get_base_clf(method), search_spaces = params_dict, scoring = scorer, cv = CV_folds, error_score = 0, n_iter = 30, verbose = 3, n_jobs = 2)
>      23     if method == 'NN':
> ---> 24         clf.fit(DF[DF.columns.drop('quit')].values, reshape_quit_2classes(DF['quit'].values))
>      25     else:
>      26         clf.fit(DF[DF.columns.drop('quit')].values, DF['quit'].values)
> 
> /Users/s/source/scikit-optimize/skopt/searchcv.pyc in fit(self, X, y, groups)
>     573                 self.step(
>     574                     X, y, space_id,
> --> 575                     groups=groups, n_jobs=n_jobs_adjusted
>     576                 )
>     577                 n_iter -= n_jobs
> 
> /Users/s/source/scikit-optimize/skopt/searchcv.pyc in step(self, X, y, space_id, groups, n_jobs)
>     495 
>     496         # get parameter values to evaluate
> --> 497         params = optimizer.ask(n_points=n_jobs)
>     498         params_dict = [point_asdict(search_space, p) for p in params]
>     499 
> 
> /Users/s/source/scikit-optimize/skopt/optimizer/optimizer.pyc in ask(self, n_points, strategy)
>     326         X = []
>     327         for i in range(n_points):
> --> 328             x = opt.ask()
>     329             X.append(x)
>     330             if strategy == "cl_min":
> 
> /Users/s/source/scikit-optimize/skopt/optimizer/optimizer.pyc in ask(self, n_points, strategy)
>     299         """
>     300         if n_points is None:
> --> 301             return self._ask()
>     302 
>     303         supported_strategies = ["cl_min", "cl_mean", "cl_max"]
> 
> /Users/s/source/scikit-optimize/skopt/optimizer/optimizer.pyc in _ask(self)
>     359             next_x = self._next_x
>     360             min_delta_x = min([self.space.distance(next_x, xi)
> --> 361                                for xi in self.Xi])
>     362             if abs(min_delta_x) <= 1e-8:
>     363                 warnings.warn("The objective has been evaluated "
> 
> /Users/s/source/scikit-optimize/skopt/space/space.pyc in distance(self, point_a, point_b)
>     684         distance = 0.
>     685         for a, b, dim in zip(point_a, point_b, self.dimensions):
> --> 686             distance += dim.distance(a, b)
>     687 
>     688         return distance
> 
> /Users/s/source/scikit-optimize/skopt/space/space.pyc in distance(self, a, b)
>     257         if not (a in self and b in self):
>     258             raise RuntimeError("Can only compute distance for values within "
> --> 259                                "the space, not %s and %s." % (a, b))
>     260         return abs(a - b)
>     261 
> 
> RuntimeError: Can only compute distance for values within the space, not 0.01 and 0.000612330223628.

I do not understand why the chosen values shown above (0.01 and 0.000612330223628) are out of the search space. I am assuming that these two numbers are from the `learning_rate` subspace (in which case they should belong to the subspace) and not from the `dropout_frac` subspace (in which case the parameter sampler has done something horribly wrong!). Is there any way to check this?

**Comment by betatim** [comment]
Can you rerun this and drop into the debugger at the end so we can find out which dimension it is that is causing the problem? We should also improve the error message to print out the dimension.

A simple attempt to reproduce this failed :-(:
```python
In [1]: from skopt import space

In [2]: rr = space.Real(1e-4, 1e-2, prior = 'log-uniform')

In [3]: for n in range(100000):
   ...:     assert rr.rvs() in rr

In [6]: a = 0.01

In [7]: b = 0.000612330223628

In [8]: (a in rr and b in rr)
Out[8]: True
```

**Comment by baharian** [comment]
sorry for the n00b question: how do i "drop into the debugger at the end"?

i also have checked the sampling process (similar to your example above), but it too failed to reproduce the problem.

**Comment by betatim** [comment]
Take a look at https://docs.python.org/3.2/library/pdb.html. I'd try either `python -m pdb my_script.py` or add `import pdb; pdb.set_trace()` to the line just before the exception is raised.

This will give you something very similar to the interactive python interpreter but in the middle of your program as it is running.

**Comment by baharian** [comment]
FYI, I have been prototyping my code in IPython, so all the runs were/are performed within IPython.

I put `import pdb; pdb.set_trace()` between the two lines
    clf = BayesSearchCV(...)
    clf.fit(...)
(see OP) -- because the fail occurred during the execution of the `fit()` method -- and there was no error this time around! I am not sure how to proceed from here.

One thing I noticed is that the only sample taken from the subspace `activation` -- defined as `'activation': Categorical(['selu', 'relu']),` -- is `'relu'` and that `'selu'` is never sampled in `30` iterations.

**Comment by betatim** [comment]
Ok. Not sure what to do for the moment if we can't (easily) reproduce it.

---

In a jupyter notebook (and ipython too I think) you can use the `%debug` magic to start a debugger after an exception was raised.

**Comment by betatim** [comment]
Closing this for now as it seems resolved. Feel free to reopen.

I sampled some points from `Categorical` with two options and it seems consistent with being 50:50. Within `BayesSearchCV` it might be different as one option could always be worse than the other so the acquisition function doesn't pick it.

**Comment by echo66** [comment]
Greetings!

I had a similar issue: for the following variable

_rr = Real(5.4199999999999999, 27.309999999999999)_

I ended up with the following error:

_Can only compute distance for values within the space, not 27.31 and 21.98._

**Comment by betatim** [comment]
One thing I have noticed is that the limit computation stops working properly if you use the `log` transform. Trying to make an example that will reproduce it.

**Comment by betatim** [comment]
If you change the [hyper-parameter optimisation notebook](https://github.com/ogrisel/euroscipy_2017_sklearn/blob/master/02_Hyper_parameter_optimization.ipynb) like so:
```python
bayes_search = BayesSearchCV(
    clf,
    {"max_depth": (1, 32, 'log-uniform'), # modification
     "max_features": (1, 96),
     "min_samples_leaf": (15, 40)
    },
    n_iter=15,
    scoring='roc_auc'
)

bayes_search.fit(X_dev, y_dev)
```

then you get the bug. The error message I get is: "Can only compute distance for values within the space, not 32.0 and 3.3578093094." if you drop into the debugger:
```
> /Users/thead/anaconda/envs/euroscipy-tutorial/lib/python3.6/site-packages/skopt/space/space.py(262)distance()
    260         if not (a in self and b in self):
    261             raise RuntimeError("Can only compute distance for values within "
--> 262                                "the space, not %s and %s." % (a, b))
    263         return abs(a - b)
    264 

ipdb> up
> /Users/thead/anaconda/envs/euroscipy-tutorial/lib/python3.6/site-packages/skopt/space/space.py(690)distance()
    688         distance = 0.
    689         for a, b, dim in zip(point_a, point_b, self.dimensions):
--> 690             distance += dim.distance(a, b)
    691 
    692         return distance

ipdb> p a
32.000000000000007
ipdb> p b
3.3578093093966261
ipdb> p dim
Real(low=1, high=32, prior=log-uniform, transform=normalize)
```

you see that `a` is 32.000000000000007 which is outside the range. I think this is from taking the log and then undoing that again.

**Comment by echo66** [comment]
@betatim thanks for the analysis and debugging! :D

Is this considered expected behavior or should it be marked as a bug?

**Comment by betatim** [comment]
It is definitely a 🐛. Do you want give fixing this a go?

**Comment by fcharras** [comment]
I've been affected by this too.

**Comment by betatim** [comment]
Do you have a good idea how to fix it? I se two options:
* make `__contains__` more lenient so that 32.000000000000000000007 is still inside 32
* make sampling smarter so it rounds down values to the max from the boundary

Maybe there is a third (and better) solution?

**Comment by Hvass-Labs** [comment]
I just started looking at skopt for use with Keras and TensorFlow and came across this thread. So take my input with a grain of salt :-)

@betatim suggested in his last post to either make a floating-point comparison more 'lenient' or to limit the sampling range. I don't know how you do the actual sampling and this might be a rounding problem somewhere in the skopt code. Making the comparison more 'lenient' seems like a bad idea - what should the tolerance be?! But limiting the sampling range seems like a simple and good solution. I did something similar in one of my older projects. Perhaps this code-snippet is helpful:

https://github.com/Hvass-Labs/swarmops/blob/master/swarmops/tools.py#L116-L127

**Comment by pavelkomarov** [comment]
I just got this bug too. I guess I need to update.

**Comment by vlimant** [comment]
facing the same issue here. is there a work-around somehow ?

**Comment by pavelkomarov** [comment]
You can avoid using log-uniform, or you can update.
