### ISSUE TITLE
BayesSearchCV only searches through first parameter space

### ISSUE THREAD

**Issue by savvastj** [scikit-optimize/scikit-optimize#476]
I tried running a couple of toy examples, including the advanced example from the documentation, and `BayesSearchCV` seems to only search over the first parameter space in the list of tuples that I pass to `search_spaces`. 

[Here](https://github.com/savvastj/ml_playground/blob/master/try_skopt_bayescv.ipynb) is a notebook where I try out `RandomForestRegressor`, `Ridge`, and `Lasso`, but `cv_results` only returns information regarding the Random Forest's parameter space.  (Another strange behavior is that even though I set 50 evaluations for Random Forest, 56 were returned.)

And [here](https://github.com/savvastj/ml_playground/blob/master/adv_bayescv_skopt_example.ipynb) is a notebook containing the advanced example from the documentation.  The `cv_results` only contain evaluations for `LinearSVC`, but nothing for the `DecisionTreeClassifier` or `SVC`.

**Comment by betatim** [comment]
Thanks for filing the issue and all the details!

Do you also want to create a PR to fix this?

**Comment by betatim** [comment]
I think the bug is [here](https://github.com/scikit-optimize/scikit-optimize/blob/39966fd750c62e236e2a629f26ad5e7f6a548452/skopt/searchcv.py#L390) where we check if the names are a list or not. By default a `range()` is passed in which doesn't pass the check (ranges aren't lists :( )

**Comment by iaroslav-ai** [comment]
Hmm I think this can be solved [here](https://github.com/scikit-optimize/scikit-optimize/blob/39966fd750c62e236e2a629f26ad5e7f6a548452/skopt/searchcv.py#L280) 

I think this needs to be list(range ...)

Some time ago I looked at it, but then forgot about it :(

**Comment by iaroslav-ai** [comment]
fixed with #478
