### ISSUE TITLE
Can you post a working example of hyper-parameter tuning using the ask and tell API?

### ISSUE THREAD

**Issue by jkquijas** [scikit-optimize/scikit-optimize#481]
Not really an issue as much as it is a request, but I don't know where else to post. I've been trying like crazy but keep running into errors such as "predict() got an unexpected keyword argument 'return_mean_grad'". All I would like to see is a concrete example of hyper-parameter optimization using an Optimizer and the Ask and Tell API. And could you please elaborate on the "n_initial_points" Optimizer variable?

Thanks!

**Comment by betatim** [comment]
The [hyper-parameter optimization example](https://github.com/scikit-optimize/scikit-optimize/blob/master/examples/hyperparameter-optimization.ipynb) shows you how to unpack arguments in the objective function and pass them to the ML model you are trying to optimise.

There is also an [example notebook for the ask-and-tell](https://github.com/scikit-optimize/scikit-optimize/blob/master/examples/ask-and-tell.ipynb) interface which shows you how to call an objective function.

Finally you might be interested in using [BayesSearchCV as replacement for GridSearchCV](https://github.com/scikit-optimize/scikit-optimize/blob/master/examples/sklearn-gridsearchcv-replacement.ipynb).

**Comment by jkquijas** [comment]
@betatim Thank you very much for your response! At this stage, I need to work with a loop and keep iterating as long as I'm improving. I thought the Ask and Tell API was perfect for this, but I think the "n_initial_points" parameter is prevents from further Ask/Tells after 10 iterations (the default value assigned to the Optimizer object) and I get error message "predict() got an unexpected keyword argument 'return_mean_grad'.". 

As far as the BayesSearchCV goes, I cant even import that, with error message "ImportError: cannot import name 'BayesSearchCV'".

**Comment by iaroslav-ai** [comment]
Hi @jkquijas ,
It seems that you installed the `scikit-optimize` via `pip install scikit-optimize` or the like. Unfortunately, in the latest release of scikit-optimize BayesSearchCV is not yet included (but we intend to make a new release soon!)

The workaround for this would be to install the most recent version of `scikit-optimize` directly from the repository. If you use pip, you can try `pip install https://github.com/scikit-optimize/scikit-optimize/archive/master.zip`. If this does not work, you can try a bit more verbose installation in `development` section in the README of the repository.

If nothing works let us know!

**Comment by jkquijas** [comment]
@iaroslav-ai Thanks! I'll give it a shot. Great work by the way, you guys rock!

**Comment by jkquijas** [comment]
@iaroslav-ai I guess I should note that when I create a Real(min, max, prior="log-uniform") instance to go with my "space" list e.g. space = [Real(np.float(-3), np.float(3), prior="log-uniform"], I get the error " Domain error in arguments.". If I omit the prior argument and simply do space = [Real(np.float(-3), np.float(3)]. the error disappears. Any ideas as to why?

**Comment by jkquijas** [comment]
Thanks!!!

**Comment by iaroslav-ai** [comment]
Above ^ is happening when you specify `prior='log-uniform'`, otherwise it happens as you would expect. It is nice when you eg select value of `C` for SVM, as then small `C`'s are more explored (but I guess that was the general direction you had in mind anyway)

**Comment by jkquijas** [comment]
@iaroslav-ai yup, perfect use case. Thanks for clarifying to perform the exponentiation.

**Comment by jkquijas** [comment]
@iaroslav-ai I guess to get outta your hair, could you elaborate a little on what the  "n_initial_points" parameter means? It is clear the optimizer complains after  "n_initial_points" ask/tell operations. I'm just wondering why this is the case. As the documentation states:

"n_initial_points [int, default=10]: Number of evaluations of func with initialization points before approximating it with base_estimator. Points provided as x0 count as initialization points. If len(x0) < n_initial_points additional points are sampled at random."

**Comment by iaroslav-ai** [comment]
Initially algorithm selects a few points to evaluate completely at random, specifically `n_initial_points` much, and then starts to select points "more intelligently" - it was observed that this helps in general for the algorithm to converge better. When it comes to "more intelligent", there were some issues with scikit-learn 0.19, in particular with some things changing that we use from sklearn that caused exceptions. You can try `pip install scikit-learn==0.18.1` to see if things get fixed also.

**Comment by iaroslav-ai** [comment]
Hummmmm forget about the last part with installing sklearn anew - I was thinking about something else :)

**Comment by jkquijas** [comment]
Great, thanks for the insight!

**Comment by fingoldo** [comment]
pip install https://github.com/scikit-optimize/scikit-optimize/archive/master.zip not working on windows for an anaconda-featured python package ((
any updates on integration of BayesSearchCV?
