### ISSUE TITLE
Strange behavior on simple optimization

### ISSUE THREAD

**Issue by Arturus** [scikit-optimize/scikit-optimize#484]
I want to evaluate optimal batch size for neural network. This is a simple 1-D problem. Due to it's simplicity and resource constraints, I decided to use just 2 random starting points and 10 evaluation steps.
```python
from trainer import train
from skopt import gp_minimize
from skopt.space import Real

def target_func(args):
    batch_size, = args
    return train(batch_size=int(round(batch_size)))

result = gp_minimize(target_func, dimensions=[Real(32, 256, 'log-uniform')], 
    n_calls=10, n_random_starts=2, verbose=True)
```
This is what I got:

`result.x_iters`
[[72.12835966378664],
 [94.99318718035363],
 [255.92436139015661],
 [32.000000000000007],
 [255.8441387524108],
 [32.011208851151991],
 [32.001558793280289],
 [255.8364463786917],
 [32.000000000000007],
 [255.96525999004072]]

`result.func_vals`
array([ 0.35155323,  0.35302041,  0.35287269,  0.35368821,  0.35528216,
        0.35124254,  0.35215296,  0.35282516,  0.35198697,  0.35410159])

GP minimizer just jumps back and forth between start and end of dimension, not doing any useful work. 
Is this an expected behavior? If not, what I'm doing wrong?

**Comment by Arturus** [comment]
Complete dump of optimization result:

```
 fun: 0.3512425379506473
    func_vals: array([ 0.35155323,  0.35302041,  0.35287269,  0.35368821,  0.35528216,
        0.35124254,  0.35215296,  0.35282516,  0.35198697,  0.35410159])
       models: [GaussianProcessRegressor(alpha=0.0, copy_X_train=True,
             kernel=1**2 * Matern(length_scale=1, nu=2.5) + WhiteKernel(noise_level=1),
             n_restarts_optimizer=2, noise='gaussian', normalize_y=True,
             optimizer='fmin_l_bfgs_b',
             random_state=<mtrand.RandomState object at 0x7f9ff7dfafc0>), GaussianProcessRegressor(alpha=0.0, copy_X_train=True,
             kernel=1**2 * Matern(length_scale=1, nu=2.5) + WhiteKernel(noise_level=1),
             n_restarts_optimizer=2, noise='gaussian', normalize_y=True,
             optimizer='fmin_l_bfgs_b',
             random_state=<mtrand.RandomState object at 0x7f9ff7de4fc0>), GaussianProcessRegressor(alpha=0.0, copy_X_train=True,
             kernel=1**2 * Matern(length_scale=1, nu=2.5) + WhiteKernel(noise_level=1),
             n_restarts_optimizer=2, noise='gaussian', normalize_y=True,
             optimizer='fmin_l_bfgs_b',
             random_state=<mtrand.RandomState object at 0x7f9ff7e54678>), GaussianProcessRegressor(alpha=0.0, copy_X_train=True,
             kernel=1**2 * Matern(length_scale=1, nu=2.5) + WhiteKernel(noise_level=1),
             n_restarts_optimizer=2, noise='gaussian', normalize_y=True,
             optimizer='fmin_l_bfgs_b',
             random_state=<mtrand.RandomState object at 0x7f9ff7db3120>), GaussianProcessRegressor(alpha=0.0, copy_X_train=True,
             kernel=1**2 * Matern(length_scale=1, nu=2.5) + WhiteKernel(noise_level=1),
             n_restarts_optimizer=2, noise='gaussian', normalize_y=True,
             optimizer='fmin_l_bfgs_b',
             random_state=<mtrand.RandomState object at 0x7f9ff7f1d708>), GaussianProcessRegressor(alpha=0.0, copy_X_train=True,
             kernel=1**2 * Matern(length_scale=1, nu=2.5) + WhiteKernel(noise_level=1),
             n_restarts_optimizer=2, noise='gaussian', normalize_y=True,
             optimizer='fmin_l_bfgs_b',
             random_state=<mtrand.RandomState object at 0x7f9ff7de8d80>), GaussianProcessRegressor(alpha=0.0, copy_X_train=True,
             kernel=1**2 * Matern(length_scale=1, nu=2.5) + WhiteKernel(noise_level=1),
             n_restarts_optimizer=2, noise='gaussian', normalize_y=True,
             optimizer='fmin_l_bfgs_b',
             random_state=<mtrand.RandomState object at 0x7f9ff7dc1708>), GaussianProcessRegressor(alpha=0.0, copy_X_train=True,
             kernel=1**2 * Matern(length_scale=1, nu=2.5) + WhiteKernel(noise_level=1),
             n_restarts_optimizer=2, noise='gaussian', normalize_y=True,
             optimizer='fmin_l_bfgs_b',
             random_state=<mtrand.RandomState object at 0x7f9ff7da7948>)]
 random_state: <mtrand.RandomState object at 0x7f9ff7ea15e8>
        space: Space([Real(low=32, high=256, prior=log-uniform, transform=identity)])
        specs: {'args': {'n_jobs': 1, 'kappa': 1.96, 'xi': 0.01, 'n_restarts_optimizer': 5, 'n_points': 10000, 'callback': None, 'verbose': True, 'random_state': None, 'y0': None, 'x0': None, 'acq_optimizer': 'auto', 'acq_func': 'gp_hedge', 'n_random_starts': 2, 'n_calls': 10, 'base_estimator': GaussianProcessRegressor(alpha=0.0, copy_X_train=True,
             kernel=1**2 * Matern(length_scale=1, nu=2.5),
             n_restarts_optimizer=2, noise='gaussian', normalize_y=True,
             optimizer='fmin_l_bfgs_b',
             random_state=<mtrand.RandomState object at 0x7f9ff7ea15e8>), 'dimensions': [Real(low=32, high=256, prior=log-uniform, transform=identity)]}, 'function': 'base_minimize'}
            x: [32.011208851151991]
      x_iters: [[72.12835966378664], [94.99318718035363], [255.92436139015661], [32.000000000000007], [255.8441387524108], [32.011208851151991], [32.001558793280289], [255.8364463786917], [32.000000000000007], [255.96525999004072]]
```

**Comment by iaroslav-ai** [comment]
Hmm interesting.
Could you run it without `'log-uniform'` prior in `Real`? Also did you try to run it for more iterations?

If nothing helps, it would help if you could share the contents of trainer or some other similar problem where you encounter same behavior, so that we can take a look at it.

**Comment by iaroslav-ai** [comment]
Maybe the behavior would be different also on development version of the skopt, in case you installed stuff with pip - we have updated a few things since last update.

**Comment by Arturus** [comment]
Each iteration step takes ~30min, complete 10-step run is ~5 hrs on modern GPU. So I have limited resources for 'run it for more iterations'. Trainer is Tensorflow RNN model, it's too big and complex to be useful in debugging.
May be we can use some surrogate function? I also have results from many previous manual runs, can we use them?

BTW, I noticed similar skopt behavior (overly increased attention to a start and end of dimension) in hyperparams search for XGBoost models, if target function is 'flat' on some dimension, i.e. function value is almost independent from an argument.

I use development skopt version (installed 2 days ago from master branch)

**Comment by kiudee** [comment]
I have some explanation for this behavior. This arises because of the multi-modality of the marginal maximum likelihood in the presence of noise.
Take a look at these two plots I did for #415:
![](https://user-images.githubusercontent.com/564473/28624480-86c79412-7219-11e7-84e4-22cf62143497.png)
![](https://user-images.githubusercontent.com/564473/28624030-1839f90a-7218-11e7-9b4d-0b883d597ab5.png)

The function itself has almost no noise, but the gaussian process model achieves high marginal likelihood either by explaining the data as noise (second plot) and using a long lengthscale, or using a smaller lengthscale using less noise. This is an inherent limitation.

I can recommend taking a look at the [Gaussian Process Book](http://www.gaussianprocess.org/gpml/chapters/) especially page 116 in chapter 5, where this problem is discussed.

**Comment by Arturus** [comment]
Mm... I'm not a Gaussian process specialist, and don't want to be (sorry), I just want to optimize my little noisy function.
Can I use skopt as black-box optimizer for this task?

**Comment by kiudee** [comment]
There are several things you could try:
- Pre-specifying the level of noise to something close (or slightly smaller) to the true noise level. This causes the GP to use smaller length scales and it will explore more varied points. If you set the noise level to a very low level you will arrive at a purely random exploration.
- Increasing the number of random evaluations `n_random_starts`, which could be too expensive in your case.

**Comment by iaroslav-ai** [comment]
@kiudee , by pre - specifying the level of noise do you mean scaling the objective / subtracting mean from the objective so that variance of objective has a larger value? It does seem to be somewhat flat - ish.

You can also try using `forest_minimize` instead of `gp_minimize`, it is not based on gaussian process. If that has issues also, you can give `gbrt_minimize` a try.

If you wish to continue with `gp_minimize`, you can try setting value of `kappa` to something like `20` or larger. This should force the optimizer to explore the space.

**Comment by iaroslav-ai** [comment]
@kiudee thanks for a detailed explanation on the issue! We should look into it in more detail.

**Comment by Arturus** [comment]
Thanks! Could you explain exact meaning of 'noise level'? Is it variance between experiments with a same hyperparameters? On 10 steps evaluation, if 3 networks trained with same hyperparams for each step, I'll have 10 intra-step variances and mean intra-step variance for 10 steps. Should I use mean intra-step variance as noise level?

I can also increase n_random_starts, but what value is enough? Can you give some guidance?

**Comment by Arturus** [comment]
@iaroslav-ai thanks, I'll try forest_minimize too.

**Comment by kiudee** [comment]
`gp_minimize` has the parameter `noise` which can be set to a fixed constant noise level (instead of "gaussian" where the parameter is fit during optimization).
Yes, it is the global variance of the value you return to the optimizer (if you were to repeat the same experiment multiple times). Note, that slightly underestimating it is not problematic.

**Comment by Arturus** [comment]
What would be better for GP optimiser:
a) 10 steps + 3 evaluations per step to reduce noise and calculate variance
б) 30 independent noisy steps (passing some pre-calculated variance)?

**Comment by jkquijas** [comment]
@kiudee Thanks for the eye openers! Could you please give me some insight on the effect of noise in the function to be approximated with the GP? For example, I am trying to minimize the cross-validation prediction error for a learning model. Would the noise be the variance between n experiment (evaluation of the cv error given the SAME set of hyper-parameters)?

**Comment by betatim** [comment]
One thing I'd do for low dimensional problems to help debugging is plot the model and points at which it was evaluated. Similar to the figures @kiudee showed. This might help you spot whether the same thing happened to you.

(Maybe we should add a convenience function for this to `skopt.plots`, right now `plot_objective` struggles in 1D (I think))

**Comment by kejiashi** [comment]
@kiudee Just curious, do you think by choosing proper sampling methods (slice, Metropolis with tempering) from the posterior distribution will address this issue under GP setting?

**Comment by betatim** [comment]
Closing for the moment, feel free to reopen if you come back to this.
