### ISSUE TITLE
random_state not working?

### ISSUE THREAD

**Issue by echo66** [scikit-optimize/scikit-optimize#489]
Greetings! 

If you run the following code: 

``python
import numpy as np
from skopt import gp_minimize

def f(x):
    #print(x)
    return (np.sin(5 * x[0]) * (1 - np.tanh(x[0] ** 2)) *
            np.random.randn() * 0.1)

res1 = forest_minimize(f, [(-2.0, 2.0)], random_state=np.random.RandomState(1))
res2 = forest_minimize(f, [(-2.0, 2.0)], random_state=np.random.RandomState(1))

print(np.concatenate((res1.x_iters, res2.x_iters), axis=1))
``

You will notice that both columns are different. But I have set the same random state.

**Comment by glouppe** [comment]
Your function `f` depends on the Numpy global random state. You should freeze it as well to expect identical results.
