### ISSUE TITLE
base_minimize implementation

### ISSUE THREAD

**Issue by ThangPM** [scikit-optimize/scikit-optimize#493]
Hello everyone,

I'm Thang. I have read Bayesian Optimization's documents as well as its implementation. I see something wrong between them. The document said:

> The total number of evaluations, n_calls, are performed like the following. If x0 is provided but not y0, then the elements of x0 are first evaluated, followed by n_random_starts evaluations. Finally, n_calls - len(x0) - n_random_starts evaluations are made guided by the surrogate model. If x0 and y0 are both provided then n_random_starts evaluations are first made then n_calls - n_random_starts subsequent evaluations are made guided by the surrogate model.

but the implementation in base.py is like this:

```
n_init_func_calls = len(x0) if y0 is None else 0
n_total_init_calls = n_random_starts + n_init_func_calls

...

# Bayesian optimization loop
n_iterations = n_calls - n_init_func_calls
```

In my opinion, I think it should be like this: n_iterations = n_calls - n_total_init_calls. Could you have a check and correct me if I'm wrong. Thank you so much!

**Comment by betatim** [comment]
Hey, this has been an error where we have changed things recently. Which version of scikit-optmize are you looking at/using?

**Comment by ThangPM** [comment]
Hi, I have been using scikit-optimize version 0.3. If your team has fixed this problem for the new version. I will update the new one. Thank you!

**Comment by betatim** [comment]
Give the latest (v0.4) version a try and let us know what happens.

**Comment by ThangPM** [comment]
Hi, I'm tuning hyper parameters for my model using the latest version of scikit_optimize (0.4). I will let you know after a couple of days. I would like to confirm 1 thing. As I understand about the implementation of new version, number of calls to 'func' now doesn't depend on n_random_starts anymore, does it?

**Comment by ThangPM** [comment]
Hi Tim, I have checked the latest version 0.4. It works well now. Could you please answer my question on the previous comment? Thank you!

**Comment by betatim** [comment]
Your `func` should get called exactly `n_calls` times. If you increase `n_random_starts` then more of the `n_calls` will use a random point, however the total number of times that `func` is evaluated should never be different from `n_calls` (unless you stop early).

**Comment by ThangPM** [comment]
Thank you so much Tim, I got it now!

**Comment by betatim** [comment]
Glad to help out :)
