### ISSUE TITLE
Getting started examples produces a lot of UserWarnings

### ISSUE THREAD

**Issue by mikesmyk** [scikit-optimize/scikit-optimize#497]
First "Getting started" example in Readme.rst produces a lot of Warnings which may confuse new users, since they reference to some internal issue of gp_minimize().

Getting Started Example: 
```
def f(x):
    return (np.sin(5 * x[0]) * (1 - np.tanh(x[0] ** 2)) *
            np.random.randn() * 0.1)
res = gp_minimize(f, [(-2.0, 2.0)])
```
Warnings: 
``` 
.../skopt/optimizer/optimizer.py:366: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated " 
```

Proposal: 
Adapt example, so that these warnings do not occur.

**Comment by jusjusjus** [comment]
No more warnings after #511.
