### ISSUE TITLE
Circle CI fails randomly

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#498]
https://circleci.com/gh/scikit-optimize/scikit-optimize sometimes CircleCI goes red and sometimes not. Something to investigate.

**Comment by betatim** [comment]
https://circleci.com/gh/scikit-optimize/scikit-optimize/824 fails with `AttributeError: 'GaussianProcessRegressor' object has no attribute 'fant_predict'`

https://circleci.com/gh/scikit-optimize/scikit-optimize/827 fails with
```
from skopt.learning import ExtraTreesRegressor
from skopt import Optimizer

noise_level = 0.1

# Our 1D toy problem, this is the function we are trying to
# minimize
def objective(x, noise_level=noise_level):
    return np.sin(5 * x[0]) * (1 - np.tanh(x[0] ** 2)) + np.random.randn() * noise_level
------------------

SyntaxError: invalid syntax (gp.py, line 15)
```

and https://circleci.com/gh/scikit-optimize/scikit-optimize/826 with `LinAlgError: ("The kernel, 1**2 * RBF(length_scale=1), is not returning a positive definite matrix. Try gradually increasing the 'alpha' parameter of your GaussianProcessRegressor estimator.", '35-th leading minor not positive definite')`

**Comment by betatim** [comment]
https://circleci.com/gh/scikit-optimize/scikit-optimize/830 fails with `LinAlgError: ("The kernel, 1**2 * RBF(length_scale=1), is not returning a positive definite matrix. Try gradually increasing the 'alpha' parameter of your GaussianProcessRegressor estimator.", '36-th leading minor not positive definite')` as well.

**Comment by betatim** [comment]
Started looking into this.

**Comment by betatim** [comment]
Posted on the wrong issue, not working on this.

**Comment by iaroslav-ai** [comment]
This is related to this: #324

**Comment by betatim** [comment]
#544 might be a fix for this.

**Comment by betatim** [comment]
Haven't seen this happen for a while -> closing.
