### ISSUE TITLE
Assertion Error while testing test_optimizer.py

### ISSUE THREAD

**Issue by BlackTeaAndCoffee** [scikit-optimize/scikit-optimize#499]
Hi, 

when i ran the Test's i got an Assertion Error. The Error is at the end of this text.  I have the following python version
Python 3.6.1 :: Anaconda 4.4.0 (32-bit).

and i've installed the following packages:

alabaster==0.7.10
anaconda-client==1.6.3
anaconda-navigator==1.6.2
anaconda-project==0.6.0
asn1crypto==0.22.0
astroid==1.4.9
astropy==1.3.2
Babel==2.4.0
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
bitarray==0.8.1
blaze==0.10.1
bleach==1.5.0
bokeh==0.12.5
boto==2.46.1
Bottleneck==1.2.1
cffi==1.10.0
chardet==3.0.3
click==6.7
cloudpickle==0.2.2
clyent==1.2.2
colorama==0.3.9
conda==4.3.25
contextlib2==0.5.5
cryptography==1.8.1
cycler==0.10.0
Cython==0.25.2
cytoolz==0.8.2
dask==0.14.3
datashape==0.5.4
decorator==4.0.11
distributed==1.16.3
docutils==0.13.1
entrypoints==0.2.2
et-xmlfile==1.0.1
fastcache==1.0.2
Flask==0.12.2
Flask-Cors==3.0.2
gevent==1.2.1
greenlet==0.4.12
h5py==2.7.0
HeapDict==1.0.0
html5lib==0.999
idna==2.5
imagesize==0.7.1
ipykernel==4.6.1
ipython==5.3.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
isort==4.2.5
itsdangerous==0.24
jdcal==1.3
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
lazy-object-proxy==1.2.2
llvmlite==0.18.0
locket==0.2.0
lxml==3.7.3
MarkupSafe==0.23
matplotlib==2.0.2
mistune==0.7.4
mpmath==0.19
msgpack-python==0.4.8
multipledispatch==0.4.9
navigator-updater==0.1.0
nbconvert==5.1.1
nbformat==4.3.0
networkx==1.11
nltk==3.2.3
nose==1.3.7
notebook==5.0.0
numba==0.33.0
numexpr==2.6.2
numpy==1.12.1
numpydoc==0.6.0
odo==0.5.0
olefile==0.44
openpyxl==2.4.7
packaging==16.8
pandas==0.20.1
pandocfilters==1.4.1
partd==0.3.8
pathlib2==2.2.1
patsy==0.4.1
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.1.1
ply==3.10
prompt-toolkit==1.0.14
psutil==5.2.2
ptyprocess==0.5.1
py==1.4.33
pycosat==0.6.2
pycparser==2.17
pycrypto==2.6.1
pycurl==7.43.0
pyflakes==1.5.0
Pygments==2.2.0
pylint==1.6.4
pyodbc==4.0.16
pyOpenSSL==17.0.0
pyparsing==2.1.4
pytest==3.0.7
python-dateutil==2.6.0
pytz==2017.2
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.0
QtPy==1.2.1
requests==2.14.2
rope-py3k==0.9.4.post1
scikit-garden==0.1.3
scikit-image==0.13.0
scikit-learn==0.18.1
-e git+git@github.com:BlackTeaAndCoffee/scikit-optimize.git@0d52aca9ad354a1f9cad942d4a41730edffbb271#egg=scikit_optimize
scipy==0.19.0
seaborn==0.7.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
sortedcollections==0.5.3
sortedcontainers==1.5.7
Sphinx==1.5.6
spyder==3.1.4
SQLAlchemy==1.1.9
statsmodels==0.8.0
sympy==1.0
tables==3.3.0
tblib==1.3.2
terminado==0.6
testpath==0.3
toolz==0.8.2
tornado==4.5.1
traitlets==4.3.2
unicodecsv==0.14.1
virtualenv==15.1.0
wcwidth==0.1.7
Werkzeug==0.12.2
widgetsnbextension==2.0.0
wrapt==1.10.10
xlrd==1.0.0
XlsxWriter==0.9.6
xlwt==1.2.0
zict==0.1.2

```
________________________________________________________________ test_defaults_are_equivalent _________________________________________________________________________________

    def test_defaults_are_equivalent():
        # check that the defaults of Optimizer reproduce the defaults of
        # gp_minimize
        space = [(-5., 10.), (0., 15.)]
        opt = Optimizer(space, random_state=1)
    
        for n in range(15):
            x = opt.ask()
            res_opt = opt.tell(x, branin(x))
    
        res_min = gp_minimize(branin, space, n_calls=15, random_state=1)
    
        assert res_min.space == res_opt.space
        # tolerate small differences in the points sampled
>       assert np.allclose(res_min.x_iters, res_opt.x_iters, atol=1e-5)
E       assert False
E        +  where False = <function allclose at 0xb64c8ecc>([[1.2553300705386121, 10.804867401632373], [-4.9982843777398269, 4.5349885894775976], [-2.798661637743304, 1.385078921...3349359, 5.1834109056457169], [0.95151211346005038, 8.0822510100503564], [1.2879177160494235, 10.278292505951395], ...], [[1.2553300705386121, 10.804867401632373], [-4.9982843777398269, 4.5349885894775976], [-2.798661637743304, 1.385078921...3349359, 5.1834109056457169], [0.95151211346005038, 8.0822510100503564], [1.2879177160494235, 10.278292505951395], ...], atol=1e-05)
E        +    where <function allclose at 0xb64c8ecc> = np.allclose
E        +    and   [[1.2553300705386121, 10.804867401632373], [-4.9982843777398269, 4.5349885894775976], [-2.798661637743304, 1.385078921...3349359, 5.1834109056457169], [0.95151211346005038, 8.0822510100503564], [1.2879177160494235, 10.278292505951395], ...] =           fun: 0.50341434699834409\n    func_vals: array([  56.52874005,  172.66531087,  102.58290349,   28.8680646 ,\n ...624], [-1.7196703721825872, 9.277871209886758], [-3.2884466845220692, 12.677325208182735], [-4.1841820464590658, 15.0]].x_iters
E        +    and   [[1.2553300705386121, 10.804867401632373], [-4.9982843777398269, 4.5349885894775976], [-2.798661637743304, 1.385078921...3349359, 5.1834109056457169], [0.95151211346005038, 8.0822510100503564], [1.2879177160494235, 10.278292505951395], ...] =           fun: 0.50341439890679318\n    func_vals: array([  56.52874005,  172.66531087,  102.58290349,   28.8680646 ,\n ...624], [-1.719670454526022, 9.2778712199133473], [-3.2884467112417353, 12.677325427507068], [-4.1840688238414359, 15.0]].x_iters

skopt/tests/test_optimizer.py:215: AssertionError
```

**Comment by betatim** [comment]
I reckon this is due to some random number generator not being seeded properly or a rounding effect?

**Comment by betatim** [comment]
This problem also exists (and is worse!) for `forest_minimize`.

**Comment by mirca** [comment]
Is this an intermittent error? Everything is green with the current master over here...

**Comment by betatim** [comment]
I think it is related to how we seed the random number generators. I couldn't reproduce the failure locally but if you dig in a big you see that it is only because we get "lucky". I'll create a PR soon.
