### ISSUE TITLE
Referencing Scikit-Optimize in Paper

### ISSUE THREAD

**Issue by yngtodd** [scikit-optimize/scikit-optimize#507]
Hey everyone, 

We are currently writing up a paper for distributed hyperparameter optimization and have been using Scikit-Optimize (I love this library). We are attempting to finalize everything for AAAI on Monday, September 11. How should I reference the work? I know that you guys were working on a publication for open source software. Has that been submitted, by chance? Thanks!

**Comment by glouppe** [comment]
Hi,

Unfortunately we do not have yet any official way to cite scikit-optimize. 

@others: we could make a zenodo entry for the source code? that's better than nothing and this gets a proper DOI.

**Comment by betatim** [comment]
To make a zenodo DOI do we need to make a new release @glouppe? Or can we also "upload" an existing release?

**Comment by betatim** [comment]
Looks like we'd have to add every single contributor by hand if we do that :-/ 

Should we create a scikit-optimize entry on zenodo that has "The scikit-learn contributors" as author?

**Comment by betatim** [comment]
Could also create a new tag purely for zenodo a la https://zenodo.org/record/49911#.WbQJVRL-lE4

**Comment by iaroslav-ai** [comment]
Would be great to have this - I might need to cite scikit-optimize soon also. Creating new tag seems like the easiest way.

**Comment by betatim** [comment]
One thing to work out if we create a new tag: by default it will create a new upload to PyPI.

Can we tag the same revision again? Then re-uploading shouldn't be a problem right?

**Comment by yngtodd** [comment]
Hey everyone, any update on setting up the reference?

**Comment by betatim** [comment]
Unfortunately not. We will probably submit to zenodo for the next release.

**Comment by iaroslav-ai** [comment]
We got zenodo now:

https://doi.org/10.5281/zenodo.1170575

I close this. If anyone has any comments or wants to discuss some further publications, I would say lets open a new issue for that.
