### ISSUE TITLE
Understanding the behavior of minimization in optimizer

### ISSUE THREAD

**Issue by kejiashi** [scikit-optimize/scikit-optimize#521]
I recently looked into the `GP-Hedge` code and found something not quite obvious from the original algorithm presented. The confusing point is on the calculation of gains that we dynamically update, in order to signify the importance of the best arm chosen by specific problem settings.

TL;DR: (The [original commit](https://github.com/scikit-optimize/scikit-optimize/pull/306) (or file `Optimizer.py` [line 454](https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/optimizer/optimizer.py#L454)) subtracts the reward gained after acquiring a new point, which is not intuitive to me. I thought the best arm chosen shall be enhanced and following from the [original algorithm](https://arxiv.org/pdf/1009.5419.pdf) (algorithm 2 line 9), it should be a "+=". But changing it to "+=" pulls the results to [a wrong direction](https://github.com/kejiashi/optimization-dump-truck/blob/master/hedge_test.ipynb).
My suspicion was something even complicated. Maybe this is trying not to enhance the best arm but to diminish the effect of the least favorable arm?)

But it all comes to the minimization behavior and I guess I didn't understand this simple switch from the very beginning:

`next_x` is always selected by the minimization of the acquisition values. (Line [471](https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/optimizer/optimizer.py#L471) and [493](https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/optimizer/optimizer.py#L493)) But intuitively, shouldn't it be the maximum acquisition value being selected? (see Jasper's [code](https://github.com/JasperSnoek/spearmint/blob/master/spearmint/spearmint/chooser/GPEIOptChooser.py#L323)) Which part did I miss? (And why it's a "-=" at the `gp-hedge` gains calculation?)

**Comment by glouppe** [comment]
Not sure if this will answer your question, but we also have the convention of having defined the acquisition functions as functions to minimize. This is something confusing as papers/code on BO are not consistent in this regard.

**Comment by kejiashi** [comment]
Thanks, Gilles! It was once clear to me but some habitual paranoia 🤖made me think the maximization problem was computed all along and then the sign was flipped once for all before doing bfgs. And this is the exact example of some unclear logic from the very beginning to me haha. Thanks!
