### ISSUE TITLE
BayesSearchCV error in search space of integer values

### ISSUE THREAD

**Issue by kambeitz** [scikit-optimize/scikit-optimize#522]
I tried to adopt the example of BayesSearchCV to search a parameter space of integer values. For a small number of iterations (e.g. 5) the code runs without problems. But with higher number of iterations (e.g. 15) it casts an error:
TypeError: %d format: a number is required, not tuple

The code of the adopted example:
from skopt import BayesSearchCV
from sklearn.datasets import load_digits
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

X, y = load_digits(10, True)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, random_state=0)
clf = SVC()
my_param_svc = {'C': range(1,20)}
opt_svc = BayesSearchCV(clf,my_param_svc,n_iter=15)
opt_svc.fit(X_train, y_train)
print("val. score: %s" % opt_svc.best_score_)
print("test score: %s" % opt_svc.score(X_test, y_test))

**Comment by kambeitz** [comment]
Error message:

TypeErrorTraceback (most recent call last)
<ipython-input-79-4d1f8e25fbc1> in <module>()
      4 my_param_svc = {'C': range(1,20)}
      5 opt_svc = BayesSearchCV(clf,my_param_svc,n_iter=15)
----> 6 opt_svc.fit(X_train, y_train)
      7 print("val. score: %s" % opt_svc.best_score_)
      8 print("test score: %s" % opt_svc.score(X_test, y_test))

/opt/conda/lib/python2.7/site-packages/skopt/searchcv.pyc in fit(self, X, y, groups)
    723                 self.step(
    724                     X, y, space_id,
--> 725                     groups=groups, n_jobs=n_jobs_adjusted
    726                 )
    727                 n_iter -= n_jobs

/opt/conda/lib/python2.7/site-packages/skopt/searchcv.pyc in step(self, X, y, space_id, groups, n_jobs)
    641 
    642         # get parameter values to evaluate
--> 643         params = optimizer.ask(n_points=n_jobs)
    644         params_dict = [point_asdict(search_space, p) for p in params]
    645 

/opt/conda/lib/python2.7/site-packages/skopt/optimizer/optimizer.pyc in ask(self, n_points, strategy)
    337             else:
    338                 y_lie = np.max(opt.yi) if opt.yi else 0.0  # CL-max lie
--> 339             opt.tell(x, y_lie)  # lie to the optimizer
    340 
    341         self.cache_ = {(n_points, strategy): X}  # cache_ the result

/opt/conda/lib/python2.7/site-packages/skopt/optimizer/optimizer.pyc in tell(self, x, y, fit)
    448             with warnings.catch_warnings():
    449                 warnings.simplefilter("ignore")
--> 450                 est.fit(self.space.transform(self.Xi), self.yi)
    451 
    452             if hasattr(self, "next_xs_") and self.acq_func == "gp_hedge":

/opt/conda/lib/python2.7/site-packages/skopt/learning/gaussian_process/gpr.pyc in fit(self, X, y)
    193                 noise_level=self.noise, noise_level_bounds="fixed"
    194             )
--> 195         super(GaussianProcessRegressor, self).fit(X, y)
    196 
    197         self.noise_ = None

/opt/conda/lib/python2.7/site-packages/sklearn/gaussian_process/gpr.pyc in fit(self, X, y)
    215             optima = [(self._constrained_optimization(obj_func,
    216                                                       self.kernel_.theta,
--> 217                                                       self.kernel_.bounds))]
    218 
    219             # Additional runs are performed from log-uniform chosen initial

/opt/conda/lib/python2.7/site-packages/sklearn/gaussian_process/gpr.pyc in _constrained_optimization(self, obj_func, initial_theta, bounds)
    452         if self.optimizer == "fmin_l_bfgs_b":
    453             theta_opt, func_min, convergence_dict = \
--> 454                 fmin_l_bfgs_b(obj_func, initial_theta, bounds=bounds)
    455             if convergence_dict["warnflag"] != 0:
    456                 warnings.warn("fmin_l_bfgs_b terminated abnormally with the "

/opt/conda/lib/python2.7/site-packages/scipy/optimize/lbfgsb.pyc in fmin_l_bfgs_b(func, x0, fprime, args, approx_grad, bounds, m, factr, pgtol, epsilon, iprint, maxfun, maxiter, disp, callback, maxls)
    191 
    192     res = _minimize_lbfgsb(fun, x0, args=args, jac=jac, bounds=bounds,
--> 193                            **opts)
    194     d = {'grad': res['jac'],
    195          'task': res['message'],

/opt/conda/lib/python2.7/site-packages/scipy/optimize/lbfgsb.pyc in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, **unknown_options)
    326             # until the completion of the current minimization iteration.
    327             # Overwrite f and g:
--> 328             f, g = func_and_grad(x)
    329         elif task_str.startswith(b'NEW_X'):
    330             # new iteration

/opt/conda/lib/python2.7/site-packages/scipy/optimize/lbfgsb.pyc in func_and_grad(x)
    276     else:
    277         def func_and_grad(x):
--> 278             f = fun(x, *args)
    279             g = jac(x, *args)
    280             return f, g

/opt/conda/lib/python2.7/site-packages/scipy/optimize/optimize.pyc in function_wrapper(*wrapper_args)
    290     def function_wrapper(*wrapper_args):
    291         ncalls[0] += 1
--> 292         return function(*(wrapper_args + args))
    293 
    294     return ncalls, function_wrapper

/opt/conda/lib/python2.7/site-packages/scipy/optimize/optimize.pyc in __call__(self, x, *args)
     61     def __call__(self, x, *args):
     62         self.x = numpy.asarray(x).copy()
---> 63         fg = self.fun(x, *args)
     64         self.jac = fg[1]
     65         return fg[0]

/opt/conda/lib/python2.7/site-packages/sklearn/gaussian_process/gpr.pyc in obj_func(theta, eval_gradient)
    207                 if eval_gradient:
    208                     lml, grad = self.log_marginal_likelihood(
--> 209                         theta, eval_gradient=True)
    210                     return -lml, -grad
    211                 else:

/opt/conda/lib/python2.7/site-packages/sklearn/gaussian_process/gpr.pyc in log_marginal_likelihood(self, theta, eval_gradient)
    410 
    411         if eval_gradient:
--> 412             K, K_gradient = kernel(self.X_train_, eval_gradient=True)
    413         else:
    414             K = kernel(self.X_train_)

/opt/conda/lib/python2.7/site-packages/sklearn/gaussian_process/kernels.pyc in __call__(self, X, Y, eval_gradient)
    677         """
    678         if eval_gradient:
--> 679             K1, K1_gradient = self.k1(X, Y, eval_gradient=True)
    680             K2, K2_gradient = self.k2(X, Y, eval_gradient=True)
    681             return K1 + K2, np.dstack((K1_gradient, K2_gradient))

/opt/conda/lib/python2.7/site-packages/sklearn/gaussian_process/kernels.pyc in __call__(self, X, Y, eval_gradient)
    752         if eval_gradient:
    753             K1, K1_gradient = self.k1(X, Y, eval_gradient=True)
--> 754             K2, K2_gradient = self.k2(X, Y, eval_gradient=True)
    755             return K1 * K2, np.dstack((K1_gradient * K2[:, :, np.newaxis],
    756                                        K2_gradient * K1[:, :, np.newaxis]))

/opt/conda/lib/python2.7/site-packages/skopt/learning/gaussian_process/kernels.pyc in __call__(self, X, Y, eval_gradient)
    389             raise ValueError(
    390                 "Expected X to have %d features, got %d" %
--> 391                 (X.shape, len(length_scale)))
    392 
    393         n_samples, n_dim = X.shape

TypeError: %d format: a number is required, not tuple

**Comment by glouppe** [comment]
> `my_param_svc = {'C': range(1,20)}`

Parameters should not be specified with lists, but with interval of allowed values.

Can you try instead `my_param_svc = {'C': (1, 20)}` ?

**Comment by betatim** [comment]
I'll close this for now. Feel free to reopen if the error is still there.
