### ISSUE TITLE
missing minimum scipy version in requirements

### ISSUE THREAD

**Issue by andreh7** [scikit-optimize/scikit-optimize#530]
`scikit-optimize` seems not to have any requirement on the `scipy` version it depends on:

`pip install scipy==0.13.3`
`pip install scikit-optimize`

works but when importing `skopt` I get:

```
>>> import skopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../anaconda/envs/test/lib/python2.7/site-packages/skopt/__init__.py", line 54, in <module>
    from . import optimizer
  File ".../anaconda/envs/test/lib/python2.7/site-packages/skopt/optimizer/__init__.py", line 1, in <module>
    from .base import base_minimize
  File ".../anaconda/envs/test/lib/python2.7/site-packages/skopt/optimizer/base.py", line 16, in <module>
    from .optimizer import Optimizer
  File ".../anaconda/envs/test/lib/python2.7/site-packages/skopt/optimizer/optimizer.py", line 20, in <module>
    from ..utils import check_x_in_space
  File ".../anaconda/envs/test/lib/python2.7/site-packages/skopt/utils.py", line 4, in <module>
    from scipy.optimize import OptimizeResult
ImportError: cannot import name OptimizeResult
```

The `scikit-optimize` version installed by pip is 0.4 .

Googling around I found that also other projects have this problem, see e.g. https://github.com/lmfit/lmfit-py/commit/956f29c6df462bcc80529671cece8f49598b9b69#diff-78c72422c390b5018fb25e5402cd89a2R16 

On the other hand, when doing the following instead (on a newly initialized python environment):

```
pip install scipy==0.14.0
pip install scikit-optimize
```

importing `skopt` works without problem.

I'm not an expert in packaging python code but I suspect that adding `>=0.14.0` after `scipy` in `requirements.txt` could solve this problem ?

(the above tests were made with python 2.7, I noticed this problem earlier today while downloading dependencies by hand, working behind a firewall with no http proxy)

**Comment by betatim** [comment]
The right place to put this requirement would be in `setup.py`. That is where `pip` and friends look. The `requirements.txt` is more for people wanting to run the "dev" version..

Do you know what the minimum version of scipy is that scikit-learn works with? So far I had assumed that because we depend on a new-is version of scikit-learn we would automatically get a "new enough" version of scipy as well.

**Comment by andreh7** [comment]
Good question, the minimal scikit-learn version (0.18) required by scikit-optimize seems not to require anything.  Doing (again on a fresh environment) `pip install scikit-learn==0.18` I get:

```
Collecting scikit-learn==0.18
  Using cached scikit_learn-0.18-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: scikit-learn
Successfully installed scikit-learn-0.18
```

but it does not even install `numpy` (let alone `scipy`) and as a consequence importing `sklearn` gives me an exception complaining about missing `numpy`.

`pip show scikit-learn` says:

```
Name: scikit-learn
Version: 0.18
...
Location: .../anaconda/envs/test/lib/python2.7/site-packages
Requires:
```
so nothing in the 'Requires' field.

I'll check if there is an issue open about this in scikit-learn because even in the latest version I get with pip (0.19.0) the problem is still there. 

Doing `pip show scikit-optimize` I see the dependencies from `setup.py` in the Requires field (but not the version numbers) so this is a valid way of getting the list of dependencies.

**Comment by andreh7** [comment]
I just saw on http://scikit-learn.org/stable/install.html that the way to get the dependencies of scikit-learn installed is to do install `scikit-learn[alldeps]`. 

Doing

```
pip install 'scikit-learn[alldeps]==0.18'
```

on a fresh environment I see:

```
Collecting scikit-learn[alldeps]==0.18
  Using cached scikit_learn-0.18-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting numpy>=1.6.1; extra == "alldeps" (from scikit-learn[alldeps]==0.18)
  Using cached numpy-1.13.3-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting scipy>=0.9; extra == "alldeps" (from scikit-learn[alldeps]==0.18)
  Using cached scipy-0.19.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: numpy, scipy, scikit-learn
Successfully installed numpy-1.13.3 scikit-learn-0.18 scipy-0.19.1
```

So the minimal scikit-learn version required by `scikit-learn[alldeps]==0.18` is 0.9 which is below 0.14. In the above example I get a newer version but this is not always guaranteed.

---

With `scikit-learn[alldeps]` I actually get another error on import related to importing something from `sklearn` (probably implying that the minimum `scikit-learn` version required should be higher). Should I report this here or open a separate issue ?

**Comment by betatim** [comment]
> With scikit-learn[alldeps] 0.18 I actually get another error on `import skopt` related to importing something from `sklearn` (probably implying that the minimum `scikit-learn` version required should be higher). Should I report this here or open a separate issue ?

New issue is probably best.

**Comment by betatim** [comment]
`scikit-learn` does not directly depend on `numpy` and `scipy` because of something related to how `setup.py` works (this might be knowledge left over from a pre-historic python world though).

Interesting to see that the dependency calls for >=0.9 but 0.19 gets installed. I wonder why. Naively I'd assume that `pip` will always try to install the lowest possible version???

In principle I have no problem with adding some requirement directly in `skopt`, from a practical point of view, the less we have to "hardcode" the less we have to maintain things :) So if "in practice" installing sklearn>=0.18 gets the user the right version of the other dependencies I'd be tempted to leave things as they are. Maybe mention in the documentation what the real minimums are. Mostly because downloading "by hand" the packages for work behind a firewall is "super rare". But yeah, I don't have a strong opinion either way.

**Comment by andreh7** [comment]
> Interesting to see that the dependency calls for >=0.9 but 0.19 gets installed. I wonder why. Naively I'd assume that pip will always try to install the lowest possible version??? 

Actually, I would expect pip to installs the latest (and greatest) version of a package which is compatible with the requirements and which it can find in the repository or cache (if not already installed).

> In principle I have no problem with adding some requirement directly in skopt, from a practical point of view, the less we have to "hardcode" the less we have to maintain things :) So if "in practice" installing sklearn>=0.18 gets the user the right version of the other dependencies I'd be tempted to leave things as they are. Maybe mention in the documentation what the real minimums are. 

I have no strong opinion on this ... (note however that mentioning the minimum level in the documentation also requires some maintenance :-) )

> Mostly because downloading "by hand" the packages for work behind a firewall is "super rare". But yeah, I don't have a strong opinion either way.

yes, I agree that this is an edge case. Once I found out the minimum needed version of numpy I thought it was a useful opportunity to make the requirements of scikit-optimize more accurate.

**Comment by betatim** [comment]
I suggest you create a PR modifying `setup.py` to include the requirement and we see if someone else has a strong opinion either way. If no one is violently opposed we merge it :)

**Comment by Juanlu001** [comment]
> scikit-learn does not directly depend on numpy and scipy because of something related to how setup.py works (this might be knowledge left over from a pre-historic python world though).

Probably because it used to be difficult to specify build time requirements. The landscape is going to change very soon with the release of pip 10, which implements [PEP 518](https://www.python.org/dev/peps/pep-0518/) (the last bit left is https://github.com/pypa/pip/pull/4764)

**Comment by andreh7** [comment]
I added the requirement for `scipy` in the above pull request. Let me know if you think also `requirements.txt` should be changed.
