### ISSUE TITLE
scikit-optimize memory error: DLL load failed

### ISSUE THREAD

**Issue by bscully** [scikit-optimize/scikit-optimize#534]
I've noticed strange behavior with scikit-optimize sharing libraries...  I can only run one job that references skopt at a time.
If I run two processes at the same time, the 1st will run and the 2nd will get errors like "DLL load failed: Invalid access to memory location" or "cannot import name _tree "

I then have to restart my IDE (eclipse Neon which is java based).  
Then I can call a single job successfully.

I'm using python2.7 64bit on windows7.  Latest skopt version, 0.4.

Could be my configuration, just throwing this out there.

**Comment by stefanocereda** [comment]
I've been running 6 parallel instances of skopt for a month without any problem, have you tried launching them out of the IDE?

**Comment by bscully** [comment]
I can no longer replicate the issue in my IDE…  Yesterday I could.
I have two jobs running, both using several cores.
Guess all is well, false alaram.

**Comment by betatim** [comment]
I'll close this for now. Good to hear it sorted itself out. Do re-open this if it comes back. There isn't a huge amount of windows experience in the `skopt` development team so quite possible that things are broken and no one notices :-/
