### ISSUE TITLE
List of predefined sklearn hyperparameter spaces?

### ISSUE THREAD

**Issue by jkleint** [scikit-optimize/scikit-optimize#536]
Is there a list of hyperparameter search spaces for common scikit-learn models (for use with BayesSearchCV) already defined somewhere?  Would that be useful?

**Comment by betatim** [comment]
I don't think that exists anywhere yet. Not sure if this is the right library to place this or not.

I think there was some discussion within scikit-learn to make it easier to discover all the hyper-parameters of a estimator and their limits. Maybe we could add a function to scikit-optimize that works something like: `space = create_space_for(my_sklearn_estimator_instance)`?

**Comment by jkleint** [comment]
OK.  One thing is that to be most useful, you want prior probability distributions over the hyperparams, and each optimization library has its own way of specifying them (PDFs, sampling functions, string names).  Plus people will want to tweak the ranges and priors for their own problems.  I was thinking a data-driven approach, just a dict mapping sklearn estimator names to parameter space dicts.  Then of course it's easy to add a convenience function.

**Comment by betatim** [comment]
If people want to modify "many" things about the search space ... then what good is it to provide a default one? Power users will probably want to customise "all the things", in which case I think they should build their own space from the ground up. Then there are the large number of users who "just want a good space" for them having a function that returns a search space that is good enough for 80% of users would be useful already I think. I would leave it to the user to then tweak the space further by replacing some of the dimension objects or some other way.

Not quite sure what you mean with "data driven".

IMHO a function that takes as input an estimator instance is the way to go. That way we can handle pipelines and such.

---

Should we make a new issue to discuss other priors to add?

**Comment by jkleint** [comment]
Sorry I wasn't super clear.  I'm proposing something like this:

```
SKLEARN_SPACES = {
    'DecisionTreeClassifier': {
        'criterion': ('gini', 'entropy'),
        'min_samples_split': Real(1e-7, 1e-1, "log-uniform"),
        'min_samples_leaf': Real(1e-7, 1e-1, "log-uniform"),
    },
    'LinearRegression': {
        'fit_intercept': (True, False),
        'normalize': (True, False),
    },

    # ...
}


def create_space_for(estimator):
    return SKLEARN_SPACES[estimator.__class__.__name__]
```

All I meant by being data-driven and useful for people wanting to tweak their spaces is that it's easy to copy and paste from this to tailor your own space.

I realized skopt `Dimension`s are sklearn-compatible, which is dash cunning, as people can also use these with sklearn's `RandomizedSearchCV`.

**Comment by betatim** [comment]
I'd be -1 on making something that people copy&paste from. At least as part of scikit-optimize code. Maybe more appropriate as a documentation?

Still think that maintaining a list of parameters and their valid values/ranges is more of a job for scikit-learn than us. There are a lot of estimators in sklearn that we know nothing about so it is hard to provide any good ranges/limits for them.

I'd be excited about something that introspects an estimator to deduce hyper-parameters and their values and spits out a `Space` that scikit-optimize understands.

Maybe @amueller has an opinion/insight on current thinking in sklearn regarding making estimators introspect-able.

**Comment by iaroslav-ai** [comment]
Sounds like a combination of [searchgrid](https://pypi.python.org/pypi/searchgrid) + BayesSearchCV + [search spaces from papers like this](https://arxiv.org/pdf/1708.05070.pdf) could be a good solution. But then scikit - optimize is "Sequential model-based optimization with a `scipy.optimize` interface", so having predefined parameter spaces would be a bit of a stretch. But I am also open to suggestions on this.

**Comment by betatim** [comment]
I will close this for now. Think we should wait and see what scikit-learn adds in terms of introspecting models to deduce search-able parameters and then revisit this.
