### ISSUE TITLE
BayesSearchCV docs refer to `surrogate` parameter which doesn't exist

### ISSUE THREAD

**Issue by jkleint** [scikit-optimize/scikit-optimize#537]
The [BayesSearchCV docstring](https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/searchcv.py#L71) refers to a `surrogate` parameter, but the constructor does not actually have one.  I'm not really sure what it means, but it seems like it's trying to allow you to specify GP or random forests etc., which would be nice.  It would also be great if the docs specified the possible values.

> surrogate : string or skopt surrogate, default='auto'
Surrogate to use for optimization of score of estimator.  By default skopt.learning.GaussianProcessRegressor() is used

**Comment by betatim** [comment]
Correct that docstring is out of date.

To change the behaviour of the optimiser used in the search you can pass in keyword arguments for [`skopt.Optimizer`](https://github.com/scikit-optimize/scikit-optimize/blob/39528092868fcb24c598ff2dcd9f90b1b55a1d81/skopt/optimizer/optimizer.py#L29) as `optimizer_kwargs` when constructing `BayesSearchCV`. However this isn't mentioned in the docstring :-(

Would you like to make a PR to remove the old and add a new docstring?

**Comment by glouppe** [comment]
Fixed in #542
