### ISSUE TITLE
printing minimization result with categorical variable with more than 7 categories fails

### ISSUE THREAD

**Issue by andreh7** [scikit-optimize/scikit-optimize#539]
I tried this (the stack trace below is with the current head 39528092868fcb24c598ff2dcd9f90b1b55a1d81 but I originally saw the problem with skopt 0.4):

```
import numpy as np
from skopt import dummy_minimize
from skopt.space import Categorical

def f(x):
    print "evaluating at",x
    return np.random.randn()

res = dummy_minimize(f,
                    [
                        Categorical([1,2,3,4,5,6,7,8])
                    ])

print res
```
which fails on the print statement with the following stack trace:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../anaconda/envs/test/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 125, in __repr__
    for k, v in sorted(self.items())])
  File ".../anaconda/envs/test/lib/python2.7/site-packages/skopt/space/space.py", line 529, in __repr__
    return "Space([{}])".format(',\n       '.join(map(str, dims)))
  File ".../anaconda/envs/test/lib/python2.7/site-packages/skopt/space/space.py", line 434, in __repr__
    cats = self.categories[:3] + [_Ellipsis()] + self.categories[-3:]
TypeError: can only concatenate tuple (not "list") to tuple
```

when I remove the last element from the list (resulting in a list with just seven elements) given to `Categorical()`, the above code works without problems. 

Is this expected ?

**Comment by andreh7** [comment]
I think I found the origin of the problem

* `self.categories` is initialized to be a tuple in class `Categorical` here: 
https://github.com/scikit-optimize/scikit-optimize/blob/39528092868fcb24c598ff2dcd9f90b1b55a1d81/skopt/space/space.py#L400
* `__repr__` of this class then tries to concatenate parts of `self.categories` with a list just containing an ellipsis in this part: https://github.com/scikit-optimize/scikit-optimize/blob/39528092868fcb24c598ff2dcd9f90b1b55a1d81/skopt/space/space.py#L432-L441

A quick solution would be to use `(_Ellipsis(),)` instead of `[_Ellipsis()]` . If there are no concerns with this solution, I can create a pull request.

**Comment by betatim** [comment]
Looks like a good solution to me. PR welcome especially if you add a test to stop this from coming back 😄

**Comment by andreh7** [comment]
I prepared a test and fix for printing the actual categorical values.

For the prior however, it's not fully clear how to proceed. 

1. there are two prior fields in class `Categorical`, `self.prior` and `self.prior_`. Is this expected ? It looks to me like `self.prior_` is used for equality testing and for drawing samples while `self.prior` is used for printing ?
1. The `categories` argument to the constructor of `Categorical` is converted to a tuple while `prior` is not. In order for the same fix applied to `categories` to work in `__repr__()` for the prior, `self.prior` should also be assigned `tuple(prior)` (unless it is None). Would that be ok or would there be any side effects ? (running `python -m pytest skopt/tests/` with such a fix does not show any failed tests)

**Comment by betatim** [comment]
I think we should remove `self.prior` and only use `self.prior_` everywhere.

What do you think of converting `self.prior_` into a numpy array when it is passed in as argument? That would make it consistent with the case of `prior=None`?

**Comment by andreh7** [comment]
Here is a quick comparison how other classes in `skopt/space/space.py` handle priors:

* class `Integer`:
  * no support for non-uniform priors 
* class `Real`:
  * takes a string argument (`"uniform"` or `"log-uniform"`)
  * implements log-uniform prior via log transformation
  * has a field `self.prior` (without underscore) containing the name of the prior
  * `__repr__()` always includes the name of the prior
* class `Categorical`
  * takes an array of probabilities or `None` which implies a uniform prior
  * implements priors via passing the probabilities to `rv_discrete()` which is created in the constructor
  * has two fields which are used as follows outside the constructor: `self.prior_` used in `__eq__()`, `self.prior` used in `__repr__()`
  * `__repr__()` includes `None` for the uniform prior or the probabilities of the prior otherwise

I start to believe that the purpose of keeping the prior both as values and as `None` for uniform priors was that one can have the following at the same time:
1. have `None` as prior in the string returned by `__repr__()` for uniform priors
1. `Categorical(["a", "b"], prior = (0.5,0.5)) == Categorical(["a", "b"])` holds

* If we want to drop 1. (i.e. have probabilities also printed in the representation string for uniform prior), one would remove `self.prior`.
* If we drop 2. we would remove the `self.prior_` (i.e. only `Categorical` instances created with `prior = None` would be equal to each other).
* If we want to keep both, an alternative would be to rename `self.prior_` e.g. to `self.prior_probs`, `self.prior_dist` or similar (the `rv_discrete` object seems not to support an equality test based on its contents)

**Comment by andreh7** [comment]
I guess what is missing to finalize pull request #543 is to decide which case should be implemented as discussed in the previous comment ?

I guess @betatim originally proposed in https://github.com/scikit-optimize/scikit-optimize/issues/539#issuecomment-338334456 to go with the option mentioned in the first bullet of the group of three bullets at the end of the previous comment (i.e. print numerical probabilities also for flat priors). Should I implement that and update the pull request accordingly ?

**Comment by betatim** [comment]
From my lack of commenting you can tell I am also not sure what the best choice is. So yes do go ahead and implement what you think is best :) Maybe Unsure + unsure = awesome 😄 

The guiding principle I would use is that `__repr__` should (as much as possible) allow a user to copy the output and paste it into a REPL and get back the same object. (Which would actually suggest we shouldn't limit the length of the list printed ... but that is maybe a new discussion to have).
