### ISSUE TITLE
gp_minimize returning an unfitted model

### ISSUE THREAD

**Issue by stefanocereda** [scikit-optimize/scikit-optimize#541]
Hi, I'm trying to use the result of an optimization but I'm having some troubles:

```
from skopt import gp_minimize
from skopt.benchmarks import branin

res = gp_minimize(branin, [[-5.0, 10.0], [0.0, 15.0]], n_calls=30)

print(res['func_vals'])
array([  25.82288522,   19.5302793 ,   20.79391584,    9.87835052,
         24.07558727,   17.9179268 ,   12.28497796,   39.83631147,
         38.11394849,   15.68917092,    2.10746792,   38.44188029,
          0.48294598,    7.31549116,    0.49938498,    0.44291265,
          0.41328953,    0.39888325,    0.412161  ,   10.96088904,
        145.87219088,   11.14185081,   61.70714764,  151.11842322,
         17.50829952,    0.40651265,    0.89005077,    1.17823266,
         20.71841413,    0.85490043])

res['models'][-1].predict(res['x_iters'])
array([ 23.22715012,  23.22715608,  23.22715639,  23.22715608,
        23.22715608,  23.22715608,  23.2271579 ,  23.0104279 ,
        62.39224524,  23.22715673,  23.2271568 ,  23.22715608,
        23.22716299,  23.22715608,  23.22716505,  23.22716353,
        23.22716482,  23.22716682,  23.2271648 ,  23.22715608,
        23.22715608,  23.22715608,  23.22715608,  23.22715608,
        23.22715608,  23.22717269,  23.22717295,  23.22728434,
        23.22715608,  23.22715608])

res['models'][-1].fit(res['x_iters'], res['func_vals'])
GaussianProcessRegressor(alpha=0.0, copy_X_train=True,
             kernel=1**2 * Matern(length_scale=[1, 1], nu=2.5) + WhiteKernel(noise_level=1) + WhiteKernel(noise_level=1),
             n_restarts_optimizer=2, noise='gaussian', normalize_y=True,
             optimizer='fmin_l_bfgs_b', random_state=1041222458)

res['models'][-1].predict(res['x_iters'])
array([  25.82289496,   19.53027717,   20.79391119,    9.87835271,
         24.07558619,   17.91792666,   12.28497975,   39.83630716,
         38.11394809,   15.68916964,    2.10747397,   38.44188234,
          0.48293487,    7.31549115,    0.49934552,    0.44294522,
          0.41331881,    0.39884435,    0.4121544 ,   10.96088734,
        145.87218826,   11.14185085,   61.70714631,  151.11841845,
         17.50829956,    0.40653706,    0.8900521 ,    1.1782371 ,
         20.71841319,    0.85490364])
```

first problem: the returned model is totally unable to predict data, like it's not been fitted
second problem: when explicitly fitting the model the predictions are correct, but there are two WhiteKernel instead of just one.

I think that I can fix this by myself, but am I correct in assuming that this should not be the expected behavior?

**Comment by stefanocereda** [comment]
There is also another inconsistency, if I manually check the kernel it reports: 
```
res['models'][-1].kernel_
31.6**2 * Matern(length_scale=[4.71, 10], nu=2.5) + WhiteKernel(noise_level=1e-05) + WhiteKernel(noise_level=0)
```
Which actually contains the tuned hyperparameters, but this is not what is reported by the code above, which reports the default hyperparameters by accessing .kernel instead of .kernel_

**Comment by betatim** [comment]
Any ideas @iaroslav-ai or @MechCoder ?

**Comment by iaroslav-ai** [comment]
Seems that with kernels this because of [this line](https://github.com/scikit-optimize/scikit-optimize/blob/12e0fdc276911cccfb4645abc87991aa96ec19b7/skopt/learning/gaussian_process/gpr.py#L190) in `fit` method. It probably should be 

```python
white_present, white_param = _param_for_white_kernel_in_Sum(self.kernel)
if not white_present:
    self.kernel = self.kernel + WhiteKernel()
```

Otherwise then the white noise kernel is duplicated.

**Comment by iaroslav-ai** [comment]
What do you guys think? If you agree that this is a solution, I would propose @stefanocereda make a quick PR, as you discovered this inconsistency.

**Comment by betatim** [comment]
Not sure I understand. We should be checking if there already is a `WhiteKernel` in `self.kernel` before adding a new one?

**Comment by iaroslav-ai** [comment]
Exactly. It seems like one noise kernel in a sum should be enough

**Comment by betatim** [comment]
Right now I am not sure we need to change anything. Some code:
```python
from skopt import gp_minimize
from skopt.benchmarks import branin

res = gp_minimize(branin, [[-5.0, 10.0], [0.0, 15.0]], n_calls=30)
m =res.models[-1]
print(m)
#GaussianProcessRegressor(alpha=1e-10, copy_X_train=True,
#             kernel=1**2 * Matern(length_scale=[1, 1], nu=2.5) + WhiteKernel(noise_level=1),
#             n_restarts_optimizer=2, noise='gaussian', normalize_y=True,
#             optimizer='fmin_l_bfgs_b', random_state=402991284)
#
# however ...
print(m.fit(res['x_iters'], res['func_vals']))
#GaussianProcessRegressor(alpha=1e-10, copy_X_train=True,
#             kernel=1**2 * Matern(length_scale=[1, 1], nu=2.5) + WhiteKernel(noise_level=1) + WhiteKernel(noise_level=1),
#             n_restarts_optimizer=2, noise='gaussian', normalize_y=True,
#             optimizer='fmin_l_bfgs_b', random_state=402991284)
```

so this only happens if you call `fit` on a model returned by `gp_minimize`. Don't think we support calling `fit` on an already fitted model. The reason we return the model is purely for inspection.

If you do call `fit` again this is quite confusing though. What seems to have lead @stefanocereda to call `fit` again is that the predictions by the model weren't making sense, which is because the model was fitted on the transformed space. So maybe providing a utility function for making predictions (commonly done for plotting etc) would be the right thing to do here (and prevent others from falling into this trap). What do you guys think?

**Comment by betatim** [comment]
This is what I see:
```python
res = gp_minimize(branin, [[-5.0, 10.0], [0.0, 15.0]], n_calls=30)
m = res.models[-1]
print(m)
#GaussianProcessRegressor(alpha=1e-10, copy_X_train=True,
#             kernel=1**2 * Matern(length_scale=[1, 1], nu=2.5) + WhiteKernel(noise_level=1),
#             n_restarts_optimizer=2, noise='gaussian', normalize_y=True,
#             optimizer='fmin_l_bfgs_b', random_state=1843164483)

print(m.kernel_)
#31.6**2 * Matern(length_scale=[0.243, 0.554], nu=2.5) + WhiteKernel(noise_level=0)
```

So only one `WhiteKernel` in both cases. The kernel you see printed out when you look at `m` is the kernel that was passed into the GPR. When you look at `m.kernel_` you see the "fitted" kernel. This is a python convention that scikit-learn follows: The `repr()` of an object let's you recreate that object. If you want to learn more about this read: http://scikit-learn.org/stable/developers/contributing.html#instantiation and around that part of the docs

**Comment by stefanocereda** [comment]
Oh I see!
Just one last question, do you know where I could access the noise level as fitted when using noise='gaussian' ?

I mean like this:
```
def noisy_branin(x):
    return branin(x) + np.random.normal(scale=100.0)

res = gp_minimize(branin, [[-5.0, 5.0], [0.0, 10.0]], noise='gaussian', n_calls=20)
```

I think what I'm looking for should be in `res.models[-1].kernel_.get_params()['k2__noise_level']` but it always report a value of exactly 0.

I've also looked into `res.models[-1].kernel_.theta` which contains `array([-3.0941779 , -4.60517019, -4.60517019,        -inf])`

But I'm really stuck in how to interpret those values.

**Comment by betatim** [comment]
http://scikit-learn.org/stable/auto_examples/gaussian_process/plot_gpr_noisy.html#sphx-glr-auto-examples-gaussian-process-plot-gpr-noisy-py I've not tried it but it seems like this example does what you want to do. So `res.models[-1].kernel_` should give you what you want.

Have you plotted the fitted GP and the points? It could be that what happens to you is like in the sklearn example (all variation get's absorbed in the "wiggleyness" of the kernel and not the noise).

**Comment by betatim** [comment]
Closing this for now as I *think* the original error is solved. Please feel free to re-open or make a new issue if that isn't right.
