### ISSUE TITLE
Ask-and-tell multiple points not deterministic

### ISSUE THREAD

**Issue by bittremieux** [scikit-optimize/scikit-optimize#545]
Using the ask-and-tell interface to ask for multiple points (for parallel evaluation) is non-deterministic, despite setting the random seed.

Example:
```
>>> import skopt
>>> skopt.Optimizer([(0.0, 5.0)], random_state=1).ask(5)
[[2.707898160060175], [4.3822876798093082], [3.6706805391186785], [0.10235924648321017], [2.2488553198028733]]
>>> skopt.Optimizer([(0.0, 5.0)], random_state=1).ask(5)
[[2.8123972865299902], [3.7319628632954411], [3.042796810385529], [2.4034677898678654], [4.4109295334943255]]
>>> skopt.Optimizer([(0.0, 5.0)], random_state=1).ask(5)
[[0.1094463465747242], [3.2154313374727224], [4.829937388347056], [0.67742817927032362], [1.0110608925921929]]
```

This is rather annoying because I have a (very) long running process. I tried to resume it by storing the intermediate results, but the new random points for each instance prevent me from doing so.

When using the `gp_minize` interface, before I parallelized the scikit-optimize routine, the points at which the function was evaluated were deterministic after having set the random seed.

**Comment by bittremieux** [comment]
Wait, now I say that a test was added for this in yesterday's commit 98b91f3. The issue doesn't seem to be resolved though I think?

**Comment by betatim** [comment]
Could you try again with `master`? For me it seems to work as expected with 12e0fdc276911 which includes the commit you pointed at.

**Comment by bittremieux** [comment]
Yep, that seems to have done the trick. Thanks.
