### ISSUE TITLE
bayessearchcv: adding fixed class weight or other kwargs

### ISSUE THREAD

**Issue by eamonnmag** [scikit-optimize/scikit-optimize#546]
It doesn't seem possible to fix the class weight parameter for a RandomForest for example. This is particularly important since without an adjusted class_weight, whatever that search finds will ultimately be more wrong than useful in my instance.

**Comment by betatim** [comment]
Do you have some code as an example?

For `BayesSearchCV` you pass in a estimator object, so you can construct that object however you want including passing arguments to the constructor I think:
```
rf = RandomForestClassifier(class_weight='auto')
bayes_cv = skopt.BayesSearchCV(rf)
...

**Comment by eamonnmag** [comment]
Ah, that worked. Before I was passing in

```
opt = BayesSearchCV( RandomForestClassifier(class_weight={0:0.05, 1:0.95}), { 'max_features': Integer(4,12), 'max_depth': Integer(2,10), 'criterion': Categorical(['entropy', 'gini']), 'n_estimators': Categorical([50, 100, 250]) }, n_iter=8, n_jobs=2, verbose=1)
opt.fit(X_train, y_train)
print(opt.score(X_test, y_test))
```

and it failed. But passing in the instantiation instead works fine :)

**Comment by betatim** [comment]
That is interesting because as far as python is concerned there should be no difference between:
```
rf = RandomForestClassifier()
BayesSearchCV(rf, ...)
# and this
BayesSearchCV(RandomForestClassifier(), ...)
```
