### ISSUE TITLE
Inlining scikit-garden code instead of dependency

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#548]
We currently depend on `scikit-garden` which is a bit tricky to install as it requires `numpy` to be already installed before you install scikit-garden. Users sometimes trip over this, we have a special install instruction and making a [binder](//mybinder.org) that uses scikit-optimize is tricky (you can't just list scikit-garden in the `requirements.txt`).

What makes scikit-garden tricky to install is its use of cython which is only needed for the mondrian forest part (I think). My suggestion would be to move the code that we use back into scikit-optimize in the same place we had it before and stop depending on scikit-garden. An alternative would be for someone to actively maintain scikit-garden and invest the time in fixing issues like this.

We re-asses this when we make use of mondrian forests in scikit-optimize at which point we can also contribute to the maintenance burden. Right now it seems like we shoulder ourselves with a lot of tedious maintenance for no benefit because we don't use the mondrian forests.

What are your opinions around this? In particular @MechCoder as you are one of the main scikit-garden maintainers.

**Comment by glouppe** [comment]
> We re-asses this when we make use of mondrian forests in scikit-optimize at which point we can also contribute to the maintenance burden.

Good point, since we do not use mondrian forests.

I am +1 for backporting code and making everyone else life easier, until the situation improves for scikit-garden.

**Comment by iaroslav-ai** [comment]
I am also +1 for backporting. Would speed up and simplify installation a bit also.
