### ISSUE TITLE
CV fit method should return self just like GridSearchCV in Sci-kit learn

### ISSUE THREAD

**Issue by KevinLiao159** [scikit-optimize/scikit-optimize#550]
In BayesSearchCV class, fit method does Not return self. It's inconsistent with the way sci-kit learn is built.
https://github.com/scikit-optimize/scikit-optimize/blob/b3cc7f6897c604988ab0a9e983adcd3cb11c301e/skopt/searchcv.py#L680
Here is fit method of GridSearchCV in sklearn. 
https://github.com/scikit-learn/scikit-learn/blob/8e599c68fb06967313d0e76a053062158cd90312/sklearn/model_selection/_search.py#L749

**Comment by glouppe** [comment]
Indeed, woops. Can you submit a fix?

**Comment by KevinLiao159** [comment]
Yes!

**Comment by betatim** [comment]
This hasn't been fixed yet, so reopening.

**Comment by KevinLiao159** [comment]
@betatim Just want to follow on the issue. Has any progress been made in this issue?

**Comment by betatim** [comment]
-> #551 is the PR that will address this
