### ISSUE TITLE
BayesSearchCV is not compatible with sklearn

### ISSUE THREAD

**Issue by fcharras** [scikit-optimize/scikit-optimize#552]
Doing anything in the __init__ method of a sklearn estimator will most of the time break his compatibility with sklearn's clone, get_params and set_params, or the ability to fit it several times. It is in fact the case here, it would break if used in a Pipeline or other meta-objects in sklearn.

I've drafted a fix there: https://github.com/scikit-optimize/scikit-optimize/pull/551

Also included 'return self' in the fit, for https://github.com/scikit-optimize/scikit-optimize/issues/550

**Comment by fcharras** [comment]
Also, search_spaces cannot be passed as dictionaries, because those are not hashable, and this again will break clone() and set_params.

One way instanciate estimators with those kind of objects, is by passing them as tuples: `my_param = tuple( [ (key1, value1), (key2, value2) ] )`  and then, inside the function it is safe to transform it to a dict: `self.my_param_ = dict(my_param)`

**Comment by pgeez** [comment]
@fcharras this would help fix #550 as well!

**Comment by fcharras** [comment]
I think this should be closed ?
Fixed by https://github.com/scikit-optimize/scikit-optimize/pull/551
