### ISSUE TITLE
Noise doesn't seem to be used in Gaussian Process Regressor?

### ISSUE THREAD

**Issue by SoManyUsernamesTaken** [scikit-optimize/scikit-optimize#559]
I could be wrong, but I was browsing through the source code and as far as I can tell, noise is never used in Gaussian Process Regressors unless the kernel is set by the user. Specifically, in the code for `GaussianProcessRegressor`:
```
        if self.kernel is None:
            self.kernel = ConstantKernel(1.0, constant_value_bounds="fixed") \
                          * RBF(1.0, length_scale_bounds="fixed")
        elif self.noise == "gaussian":
            self.kernel = self.kernel + WhiteKernel()
        elif self.noise:
            self.kernel = self.kernel + WhiteKernel(
                noise_level=self.noise, noise_level_bounds="fixed"
            )
```

This means that if the kernel is `None` (which is the default behaviour) then the noise argument is ignored.

This occurs here:
https://github.com/scikit-optimize/scikit-optimize/blob/be5f87aab8d61d8bee123340715716bfd9506a3c/skopt/learning/gaussian_process/gpr.py#L186

To fix this, I believe the code should be modified to:

```
        if self.kernel is None:
            self.kernel = ConstantKernel(1.0, constant_value_bounds="fixed") \
                          * RBF(1.0, length_scale_bounds="fixed")
        if self.noise == "gaussian":
            self.kernel = self.kernel + WhiteKernel()
        elif self.noise:
            self.kernel = self.kernel + WhiteKernel(
                noise_level=self.noise, noise_level_bounds="fixed"
            )
```

**Comment by SoManyUsernamesTaken** [comment]
To further investigate, I tried the following code. All 

```
import numpy as np
from skopt.learning import GaussianProcessRegressor

X = np.random.normal(size=[100,2])
Y = np.random.normal(size=[100])

g_none = GaussianProcessRegressor(noise=None) # default
g_none.fit(X,Y)
print(g_none.kernel)
print(g_none.predict(X[0:1], return_cov = True))

g_gaussian = GaussianProcessRegressor(noise='gaussian')
g_gaussian.fit(X,Y)
print(g_gaussian.kernel)
print(g_gaussian.predict(X[0:1], return_cov = True))

g_const = GaussianProcessRegressor(noise=1)
g_const.fit(X,Y)
print(g_const.kernel)
print(g_const.predict(X[0:1], return_cov = True))
```

All use the same kernel, and all return the same predictions with 0 (!) predicted covariance

**Comment by betatim** [comment]
Would you like to submit a PR to fix this? Struggling to see where your two code samples in https://github.com/scikit-optimize/scikit-optimize/issues/559#issue-275146585 are different, but I agree with your diagnosis about `kernel=None` and ignoring the noise.

**Comment by SoManyUsernamesTaken** [comment]
I'll submit a PR; the difference is that the 2nd conditional statement should be an `if` rather than an `elif`
