### ISSUE TITLE
Set OMP_NUM_THREADS to 1 to avoid high system cpu usage

### ISSUE THREAD

**Issue by stefanocereda** [scikit-optimize/scikit-optimize#563]
I've been experiencing a really high system cpu usage with skopt, preventing me to practically run multiple skopt instances in parallel.
Even for a simple branin optimization I had every core up to 100% usage (with n_jobs=1) and most of the consumption was system.

This simple code:
```
from skopt import gp_minimize
from skopt.benchmarks import branin

r = gp_minimize(branin, [[-10.0, 5.0],[-5.0,15.0]], n_jobs=1)
```
already shows the problem:
```
time python test.py
real    2m18,329s
user    2m41,741s
sys     3m48,756s
```

However, if we reduce the number of threads for openmp to one, the system time goes down:
```
time OMP_NUM_THREADS=1 python test.py
real    1m48,608s
user    1m46,486s
sys     0m2,080s
```

openmp should be used by blas, which I think skopt just use to handle the GP matrix, but I've never seen the benefit of multithreaded blas using skopt (even with many points and many dimensions) so I think that everybody should benefit from this

**Comment by betatim** [comment]
I think it is something numpy does, so I think they should provide a way to turn it on/off for users to decide. I don't think as a project we should meddle with the settings a user chose. We should document that this happens and point people to the right bit of documentation to influence the behaviour of numpy.

**Comment by bjodah** [comment]
@stefanocereda are you perhaps using openblas with numpy? I've noticed that openblas tries to fire up threads even for small matrices in its "level 3" blas/lapack functions (at least for `gbtrf`).

**Comment by glouppe** [comment]
I agree we should not change this value ourselves. This is clearly an issue with Numpy and its dependencies.

**Comment by stefanocereda** [comment]
Yes, I'm using openblas, I will try other libraries in the next weeks.
I too agree that skopt should not change this setting on its own, I was thnking about a note in the documentation stating that this is the recommended setting.

**Comment by stefanocereda** [comment]
I've tried to use intel mkl instead of openblas. Interestingly, openblas is the winner (I'm using an intel i5-6200U with 2 physical cores and 4 threads thanks to hyperthreading)

The tested code is simply:
```
from skopt import gp_minimize
from skopt.benchmarks import branin
gp_minimize(branin, [[-5.0, 10.0],[0.0,15.0]], verbose=False)
```

Intel MKL (default 2 cores)
```
real    1m23,733s
user    2m29,051s
sys     0m2,912s
```

Intel MKL with MKL_NUM_THREADS=1
```
real    1m31,155s
user    1m29,165s
sys     0m1,976s
```

Intel MKL with MKL_NUM_THREADS=4 (it still spawns just 2 threads, I think MKL is doing some kind of optimization here and just cap the number of threads to the number of cores)
```
real    1m22,847s
user    2m23,357s
sys     0m3,023s
```


OPENBLAS (default 4 cores)
```
real    1m43,049s
user    2m6,550s
sys     2m51,066s
```

OPENBLAS with OMP_NUM_THREADS=2
```
real    1m24,110s
user    1m31,603s
sys     0m47,043s
```

OPENBLAS with OMP_NUM_THREADS=1
```
real    1m15,711s
user    1m13,608s
sys     0m2,092s
```

My conclusion is that the two libraries are equivalent, the only important thing is to reduce the number of threads to the number of cores you have.

**Comment by betatim** [comment]
Closing for now. Feel free to reopen if there is something to be done in scikit-optimize.
