### ISSUE TITLE
plot_* functions with BayesSearchCV Result?

### ISSUE THREAD

**Issue by galtay** [scikit-optimize/scikit-optimize#566]
Given that I have the results of a call to the `fit` method of `BayesSearchCV`, is there something from that object I can pass to the plotting functions (plot_convergence, plot_objective, ...)?  

```
bscv = BayesSearchCV(...).fit(X, y)
plot_objective(???)
```

**Comment by betatim** [comment]
Currently no. We don't attach/store the result returned whe ncalling `optimizer.tell(..)` in `BayesSearchCV`. I can't think of a reason why not to do that though, so we should.

Do you want to open a PR? I would create a `skopt_result_` variable in `BayesSearchCV` which gets set to the latest result. One thing to take care of is when there are multiple search spaces and optimizers. And maybe a better name for the variable.

**Comment by galtay** [comment]
Great library!  Don't have time at the moment.  Might pick it up over the holiday break.  Will let you know.

**Comment by christianblust** [comment]
Any news on this feature? What would be the alternative to get the plots for bayesian hyper parameter tuning? Just following the approach described in https://github.com/scikit-optimize/scikit-optimize/blob/master/examples/hyperparameter-optimization.ipynb?

**Comment by betatim** [comment]
No one has had time to work on this. Would be a good first contribution though.
