### ISSUE TITLE
warm_start for gp_minimize?

### ISSUE THREAD

**Issue by yitang** [scikit-optimize/scikit-optimize#567]
Hi, 

I wonder if we could force `gp_minimize` to start with a set of good parameters first and then continue the Bayesian optimisation? 

Thanks,

**Comment by betatim** [comment]
The `x0` and `y0` parameters of all the minimize functions allows you to do exactly this: https://github.com/scikit-optimize/scikit-optimize/blob/c7e7fb76057371ea5c380c08114f49cd5ad3d9fb/skopt/optimizer/gp.py#L123-L139

**Comment by yitang** [comment]
That's fully useful thank you very much!
