### ISSUE TITLE
125 out of 300 trials are duplicated

### ISSUE THREAD

**Issue by yitang** [scikit-optimize/scikit-optimize#568]
HI all,

I'm trying to skopt and I think it's great. I tried to run it for tuning hyper parameters but I found there are 125 out of 300 trials are duplicated, and I wonder why this could happen? the parameter space are continuous, something like [Real(1e-3, 1e3), Real(2, 2000), ... etc]. 

gp_minimize converged after 54 trials, and around 175 trials, it seems to start have 124 parameters that has been tried before, and this seems happened in a row. what's the reason behind this?

I examined the sampled parameter space and it looks like 90% of the parameters are sampled near the boundary of the space. to my surprise, the minimal it found is early the boundary, should this be the reason? also, there could be other optimal minimal that are not in the boundary, and why gp_minize doesn't explore there? 

if indeed the optimal is on the very boundary of the space, is there an way to avoid re-evaluation? something like either 1) skip and continue, or 2) retrieve the score from previous results? 

Thanks, 

Yi

**Comment by kejiashi** [comment]
Have friends also met such kind of issue in real case. Could you share more details on the gp_minimize parameters? Like the acquisition function, optimizer (bfgs or sampling) and more...?

**Comment by yitang** [comment]
I used the default parameters.

**Comment by kejiashi** [comment]
Excuse me for not being too familiar with the real-world using situations. I think the core developers of this community may have a better sense of this issue.

How long would a single run in your case take? If your single run does not take long, could you try to alter the search space or switch to sampling (`acq_optimizer="sampling"`) and see if the same situation still happens? Moreover, would other optimizers other than gp perform the same as well?

**Comment by yitang** [comment]
Hi, I will try and report back.

**Comment by betatim** [comment]
What happens is that indeed the minimizer will keep placing samples close to where it thinks the minimum is. Unfortunately there is nothing yet built in to the library that forces the minimizer to explore a new point, this is completely controlled by the acquisition function.

The thinking behind evaluating a (very) close point repeatedly is that the objective is noisy so we get more information by doing this. You could check out the `DeltaXStopper` that will stop the minimisation procedure when too many points are close to each other. Here the idea is that the optimisation has "converged" if you repeatedly evaluate (very) close points.

**Comment by betatim** [comment]
Closing this for now. Feel free to reopen when you come back/have more news.
