### ISSUE TITLE
ImportError: cannot import name MaskedArray

### ISSUE THREAD

**Issue by pavelkomarov** [scikit-optimize/scikit-optimize#569]
I got scikit-optimize from your pypi release [here](https://pypi.python.org/pypi/scikit-optimize), where it says I need scikit-learn >= 0.18. "I'm in luck." thought I, for 0.18 I have. But trying to import skopt I get an error that MaskedArray can not be imported from sklearn.utils.fixes, and trying to import that class from there myself also yields an error. *Does scikit-optimize actually have a dependency on a later version of sklearn?*

**Comment by iaroslav-ai** [comment]
Hi @pavelkomarov 
`MaskedArray` is present in both 0.18 and 0.19 releases of sklearn.utils.fixes:
[https://github.com/scikit-learn/scikit-learn/blob/0.18.X/sklearn/utils/fixes.py](https://github.com/scikit-learn/scikit-learn/blob/0.18.X/sklearn/utils/fixes.py)
[https://github.com/scikit-learn/scikit-learn/blob/0.19.X/sklearn/utils/fixes.py](https://github.com/scikit-learn/scikit-learn/blob/0.19.X/sklearn/utils/fixes.py)
I also cannot reproduce your import error on my system. Are you sure you are on the latest sklearn?

**Comment by pavelkomarov** [comment]
I am sure I have sklearn version 0.18, and I am sure `from sklearn.utils.fixes import MaskedArray` returns an `ImportError`. I am on numpy 1.11.1. I will try updating it and see what happens. There is that `if np_version < (1, 12, 0): class MaskedArray(np.ma.MaskedArray):` definition that makes me think `MaskedArray` might be unnecessary with an updated version of numpy.

**Comment by iaroslav-ai** [comment]
Agreed, that part looks suspicious. Let me know how it goes.

**Comment by pavelkomarov** [comment]
Nope, that didn't fix it.

**Comment by pavelkomarov** [comment]
I went deep in to my packages and found that fixes.py actually *doesn't* have a MaskedArray in 18.0, at least not in the version someone installed here. I will get someone with permissions to edit the source and try to get the latest version of sklearn approved for my project.

**Comment by mirca** [comment]
With ``sklearn 0.18.2``:
```
>>> import sklearn
>>> sklearn.__version__
'0.18.2'
>>> from sklearn.utils.fixes import MaskedArray
```

**Comment by pavelkomarov** [comment]
Yeah, it exists in later versions. I'm having to get the software safety people to review 19.1 so we can just update system-wide.

**Comment by betatim** [comment]
@pavelkomarov would you like to make a PR to update `setup.py` to require `>=0.18.2`?

**Comment by pavelkomarov** [comment]
I suppose I could. I'd love to be a contributor.

**Comment by betatim** [comment]
Still planning on doing this? Would be a good first PR.

**Comment by pavelkomarov** [comment]
I am. I've just didn't actually make it a priority yet. I did read about the PR process yesterday and found it's exactly what I would expect.

**Comment by pgg1610** [comment]
I am using Scikit-Learn version 0.23.0 with scikit-opt version 0.7.4. When calling for `BayesSearchCV` I do get the import error mentioned in the issue title: 
ImportError: cannot import name 'MaskedArray'

**Comment by rene-rex** [comment]
Yep, same here. It seems sklearn moved MaskedArray once again.

**Comment by konsti-papa** [comment]
Same Problem here with BayesSearchCV...

**Comment by cpoptic** [comment]
Can confirm.  The recent sklearn 0.23 update broke the `MaskedArray` from `sklearn.utils.fixes`

**Comment by basnijholt** [comment]
This currently breaks all the tests in Adaptive [(see this CI report.)](https://dev.azure.com/python-adaptive/adaptive/_build/results?buildId=1301&view=logs&jobId=9515b949-fbf9-5070-9840-81f94d1a3ef0&j=9515b949-fbf9-5070-9840-81f94d1a3ef0&t=dfd82db4-e802-5370-d4e2-1ff6d408e2d5)

**Comment by epx-dan** [comment]
scikit-learn=0.23.0 & scikit-optimize=0.7.4 will raise error `ImportError: cannot import name 'MaskedArray'`
upgrade to scikit-learn=0.23.1 will resolve it. However, I have another error caused by some other reasons with scikit-optimize: `TypeError: object.__init__() takes no parameters` when I use BayesSearchCV on scikit-survival CoxPH.

**Comment by timonmerk** [comment]
Just want to mention here, that this error still exists with sklearn version 1.0 and skopt version 0.8.1

So it would be necessary install sktop development version 0.9.dev0

**Comment by janezlapajne** [comment]
Can someone tell me which versions should I install then. I just want this to work :)

**Comment by timonmerk** [comment]
@janezlapajne Just install the development version 0.9.dev0:
```
git clone https://github.com/scikit-optimize/scikit-optimize.git
cd scikit-optimize
pip install -e.
```

**Comment by janezlapajne** [comment]
Thank you, that worked. I installed new virtual environment with python 3.9 and followed your steps.

**Comment by mmehdig** [comment]
I installed the latest release before `1.0`, it worked.
`pip install scikit-learn==0.24.2`

**Comment by tryingsomestuff** [comment]
forcing  `pip3 install scikit-learn==0.24 numpy==1.19.1 chess-tuning-tools` is a work-around.
