### ISSUE TITLE
Release v 0.5

### ISSUE THREAD

**Issue by iaroslav-ai** [scikit-optimize/scikit-optimize#578]
Checklist:

 https://github.com/scikit-optimize/scikit-optimize/milestone/5

**Comment by Hvass-Labs** [comment]
I could really use a fix to issue #576 so I can finish my tutorial on skopt with TensorFlow and Keras.

**Comment by betatim** [comment]
These are all the issues currently assigned to the 0.5 milestone: https://github.com/scikit-optimize/scikit-optimize/milestone/5

**Comment by glouppe** [comment]
Shall we also bump scikit-learn to 0.19?

**Comment by iaroslav-ai** [comment]
I would like to make a release very soon to get zenodo DOI for skopt. I can make a release myself, I just need your ok on this. I would personally postpone other issues to 0.6.

**Comment by betatim** [comment]
Can you setup the machinery for creating the zenodo entry?

**Comment by betatim** [comment]
How about we give #574 a chance to get merged too. I think it is ready to go, just waiting for @chschroeder to agree.

#610 would also be a nice quick win ;)

**Comment by boccaFF** [comment]
Sorry to barge in if inappropriate, but these are the steps needed to create the zenodo entry: [Making Your Code Citable](https://guides.github.com/activities/citable-code/).

From what I understood, it is just a login and clicks from the repo owner.

**Comment by iaroslav-ai** [comment]
@boccaFF :+1: !
Indeed seems to be quite simple - just create a new release on github, and then zenodo [will take care of all the zipping and doi creating](https://zenodo.org/account/settings/github/).

**Comment by iaroslav-ai** [comment]
#574 should be included in proper 0.5 release.

**Comment by betatim** [comment]
Need to bump the versionS mentioned in the README. conda-forge package for v0.4 is now available. We can probably go directly to v0.5 if we make the release and a PR to the https://github.com/conda-forge/scikit-optimize-feedstock repo at the same time.

**Comment by betatim** [comment]
Also, release time?

**Comment by betatim** [comment]
@iaroslav-ai  can you make the v0.5 release as well?

**Comment by betatim** [comment]
README needs updating, PR incoming.

**Comment by iaroslav-ai** [comment]
I will double check if there is anything that we missed for 0.5 and then release!

**Comment by iaroslav-ai** [comment]
I am fine with the current state of things. I will make a new release in 12 hours (morning in Germany) to give room for any last minute fixes.

**Comment by iaroslav-ai** [comment]
Ok, creating a release now :)

**Comment by iaroslav-ai** [comment]
Yay! :tada: :tada: :tada:
