### ISSUE TITLE
gp_minimize and company can not take points as dictionaries

### ISSUE THREAD

**Issue by pavelkomarov** [scikit-optimize/scikit-optimize#583]
I had an issue a few days ago (#581) where I wondered whether I could use `BaseEstimator`'s `set_params`-like syntax when defining spaces and points with `BayesSearchCV`. That is `paramName` or `subObject__subObjectParamName` as keys to a dictionary-defined space. It turns out you can, so hooray.

However, I realized I can not actually use `BayesSearchCV` because my data is too large to fit in memory, so there is no way to call `.fit(data)`. As a workaround, I have defined my own objective function which handles batch-reads and does its own cross validation and returns a score. But now I am finding out that the `X_minimize` functions only take lists as their `dimensions` parameter, which is wildly inconvenient because it means I can't just call `estimator.set_params(**point)` inside my objective function, and all the spaces I defined based on dictionaries can't work.

I suggest updating all `X_minimize` functions to support points and spaces defined as dictionaries rather than requiring lists. The list-solution seems to me an outdated one.

**Comment by pavelkomarov** [comment]
I did manage to find a hack to work around this issue, in case anyone else cares (and so I can't forget before I have a chance to implement it):
1. Use the Run object I defined to store, instead of the dictionary-defined space, the alphabetically-sorted keys and the result of skopt's `utils.dimensions_aslist(space)` separately.
2. Pass the listified values from the dictionary as the space to `X_minimize` with the `Run.objectiveFn` as the function to minimize.
3. In `Run`'s `objectiveFn` use the saved, alphabetized keys and the point passed by `base_minimize` on line 225 or 248 to reconstruct the dictionary, which is possible because dimensions are sorted by alphabetized key, and then use this dictionary-defined space to call `estimator.set_params(**dict)`.

Phew.

**Comment by betatim** [comment]
Does https://github.com/scikit-optimize/scikit-optimize/blob/6deff296237422c8b60a5dadb1336dc5e1684c93/skopt/utils.py#L381 not work for you?

We decided to follow the interface of `scipy.optimize` which does not require objective functions to have named arguments. Maybe one way to make it more convenient is to provide a wrapper for objective functions that do support named arguments, something like:
```python
def objective(x=0, y=3., z=0.3):
  pass

def with_named_args(func, space):
  def f(*args):
    return func(point_asdict(*args, space))
  return f

gp_minimize(with_named_args(objective, space), space,...)
```

**Comment by pavelkomarov** [comment]
`point_asdict` should do what I want, I suppose. I was aware of it but didn't connect the dots. So so long as I keep the original search space in my `Run`, I should be able to reconstruct the dictionary form without resorting to anything aside from your code.

I'm not saying you should *require* `X_minimize` to take the dictionary form of the space, but it would be nice if it were supported so I didn't have to worry about taking all the values out of the space to pass as a parameter and then re-joining points from that space with keys later.

**Comment by betatim** [comment]
I am not sure what you mean with "dictionary form of the space". I thought what you wanted to do is have `*_minimize` call the objective function with named arguments (like `objective(a=2, b=3.1)`) instead of the current convention (`objective(2, 3.1)`).

What interface do you propose for switching the calling convention of the `*_minimize` functions? My best idea is what I posted [here](https://github.com/scikit-optimize/scikit-optimize/issues/583#issuecomment-353243932).

**Comment by pavelkomarov** [comment]
The dictionary form of the space is as defined [here as `param_grid`](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) and [here as `param_distributions`](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#sklearn.model_selection.RandomizedSearchCV) (minus the actual distributions part). 

Right now the objective just gets some point defined with a list of values. I would rather it recieve that point as a dictionary of parameter names mapping to values, because the keys are useful and important. Sure, you can work around not having them as you suggested, but it's annoying and unnecessary. All you have to do is extend `base_minimizer` to treat dictionaries as well as lists, and then you can keep the calling convention/interface the same.

I have implemented a version that can take dictionaries, but I wasn't worrying about also handling list-form spaces at the time, so it's not backwards compatible and all that. But when I find the time I'll have to combine them and submit a pull request so you can see it.

**Comment by betatim** [comment]
Ok, so if I understand what you want to do: you want to specify the search space differently not change how the objective function is called?

**Comment by betatim** [comment]
The example I gave in https://github.com/scikit-optimize/scikit-optimize/issues/583#issuecomment-353243932 is actually wrong, but we could still build a adaptor similar to hwat I sketched that passes a single argument to the objective which looks like `dict(lr=0.01, n_trees=100, foo=2)`

**Comment by pavelkomarov** [comment]
Right, the objective still just gets the one parameter, but that parameter could be a dictionary or a point, depending on what the user passes as `dimensions` to `*_minimize()`. Really there are just a few guts in `base_minimize` that need to be changed, some conditionals that treat `dimensions` differently if it's a dictionary, whereas right now it errors if the space is not a list ([line 179](https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/optimizer/base.py))

**Comment by betatim** [comment]
If you make a PR we can discuss a concrete proposal. I'd be -0 on adding a new way of specifying a search space that relies on inferring what the user meant. We support naming dimensions so we can generate a dictionary for calling the objective that way. The bit to work out is a user friendly way to then decide how to call the objective.

https://github.com/scikit-optimize/scikit-optimize/blob/6deff296237422c8b60a5dadb1336dc5e1684c93/skopt/optimizer/base.py#L179-L180 is there because internally we use an instance of `skopt.Space` which requires a list of `Dimension` objects.

**Comment by betatim** [comment]
#590 is a proposal for allowing objective functions to receive named arguments.

**Comment by pavelkomarov** [comment]
I followed #590 through to #592 and added a comment at the bottom stating why I do not believe that PR solves this issue.

**Comment by betatim** [comment]
Let's close this for now and keep #514 which is about the same topic. This issue has a lot of back-and-forth in it till we worked out what we were both talking about, #514 is cleaner -> easier to work on.

**Comment by pavelkomarov** [comment]
#514 wants a translation utility, which would work, but I'd rather *_minimize() just natively support ParameterGrid formats as I've detailed here. That way users don't have to call some wonky function to adapt a space to some other format, "wonky" because having many different requisite formats for the space is confusing. Do you have a preference for a utility? The only reason I could think you might is it wouldn't require a modification to the base_minimize code, which could cause tests to fail. But I'm always in favor of really cleaning things up and unifying early instead of allowing code to balloon for every new feature.

**Comment by betatim** [comment]
As I described in one of the other threads on this topic I think trying to have only one way of specifying a search space won't work as there are so many different ways people expect to specify them. Based on their background (scikit-learn, hyperopt, scipy, etc). So we will need to provide ways to convert spaces from one to the other.

In addition for at least the next two releases we would have to support the current way (A) and the dicts only way (B) in parallel. Issuing a warning to users of the (A) way until it is removed. As a scikit-optimizer who is happy with the current way, switching to one that is easier for scikit-learn'ers is not really a win. (Ask me again when I am wearing my keras out-of-core learning user hat...)

---

Thinking a bit into the future, we've been wondering about a good format for specifying conditional search spaces. So a space where some dimensions only exist when a certain dimension has a particular value. From watching a similar discussion in scikit-learn about how to do that I'm not sooo sure that having the constraint of having to name all dimensions (the keys in the dict) and fitting things into a dict-like object is ideal. My hope is that we can wait a bit longer and learn from others who implement something similar. My feeling would be that we block the option of "wait and see" if we now make a breaking change, with deprecation cycle. We'd have to wait till that is gone to then make another breaking change.
