### ISSUE TITLE
Rounding error causes 'ask' to produce points that are outside the bounds of the space.

### ISSUE THREAD

**Issue by jonathanng** [scikit-optimize/scikit-optimize#586]
Running this code:

```
import skopt
opt = skopt.Optimizer(dimensions=[skopt.space.Real(low=.0001, high=.2, prior="log-uniform")])
opt.ask(n_points=20)
```
produces this error:

> ~/Development/lib/scikit-optimize/skopt/optimizer/optimizer.py in ask(self, n_points, strategy)
>     331         X = []
>     332         for i in range(n_points):
> --> 333             x = opt.ask()
>     334             X.append(x)
>     335             if strategy == "cl_min":
> 
> ~/Development/lib/scikit-optimize/skopt/optimizer/optimizer.py in ask(self, n_points, strategy)
>     303         """
>     304         if n_points is None:
> --> 305             return self._ask()
>     306 
>     307         supported_strategies = ["cl_min", "cl_mean", "cl_max"]
> 
> ~/Development/lib/scikit-optimize/skopt/optimizer/optimizer.py in _ask(self)
>     364             next_x = self._next_x
>     365             min_delta_x = min([self.space.distance(next_x, xi)
> --> 366                                for xi in self.Xi])
>     367             if abs(min_delta_x) <= 1e-8:
>     368                 warnings.warn("The objective has been evaluated "
> 
> ~/Development/lib/scikit-optimize/skopt/optimizer/optimizer.py in <listcomp>(.0)
>     364             next_x = self._next_x
>     365             min_delta_x = min([self.space.distance(next_x, xi)
> --> 366                                for xi in self.Xi])
>     367             if abs(min_delta_x) <= 1e-8:
>     368                 warnings.warn("The objective has been evaluated "
> 
> ~/Development/lib/scikit-optimize/skopt/space/space.py in distance(self, point_a, point_b)
>     719         distance = 0.
>     720         for a, b, dim in zip(point_a, point_b, self.dimensions):
> --> 721             distance += dim.distance(a, b)
>     722 
>     723         return distance
> 
> ~/Development/lib/scikit-optimize/skopt/space/space.py in distance(self, a, b)
>     280         if not (a in self and b in self):
>     281             raise RuntimeError("Can only compute distance for values within "
> --> 282                                "the space, not %s and %s." % (a, b))
>     283         return abs(a - b)
>     284 
> 
> RuntimeError: Can only compute distance for values within the space, not 0.2 and 0.00029275611954.

After close inspection, it looks like there is some sort of rounding error:

```
> /home/jng/Development/lib/scikit-optimize/skopt/space/space.py(282)distance()
    280         if not (a in self and b in self):
    281             raise RuntimeError("Can only compute distance for values within "
--> 282                                "the space, not %s and %s." % (a, b))
    283         return abs(a - b)
    284 

ipdb> !a
0.20000000000000004
```

**Comment by betatim** [comment]
This is related https://github.com/scikit-optimize/scikit-optimize/issues/470#issuecomment-325718171
