### ISSUE TITLE
Compute distance with one point normalized

### ISSUE THREAD

**Issue by chschroeder** [scikit-optimize/scikit-optimize#589]
**Setting:**
* I have a space with only categorical variables (most of them containing integers admittedly)
* ask and tell API is used with an gp optimizer

The first `n_initial_points`-many points are evaluated as expected. After that i get the following error:

```
 [ ... ] 
  File "/usr/local/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 333, in ask
    x = opt.ask()
  File "/usr/local/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 305, in ask
    return self._ask()
  File "/usr/local/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 366, in _ask
    for xi in self.Xi])
  File "/usr/local/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 366, in <listcomp>
    for xi in self.Xi])
  File "/usr/local/lib/python3.6/site-packages/skopt/space/space.py", line 721, in distance
    distance += dim.distance(a, b)
  File "/usr/local/lib/python3.6/site-packages/skopt/space/space.py", line 492, in distance
    " the space, not {} and {}.".format(a, b))
RuntimeError: Can only compute distance for values within the space, not 1.0 and 1750.
```

1.0 is not a reasonable value for this parameter (and far outside the bounds of the parameter space of that variable). Seems like one dimension is normalized and the other is not.

I am aware that using categoricals is probably not the most elegant way here. But this should work, shouldn't it?

When i have mixed variable types the categoricals seem to work fine. With Integers i often have the problem that the points to be evaluted quickly focus in the extreme values of the range. Is there maybe another way to solve this?

**Comment by betatim** [comment]
Tried to reproduce the error with this snippet:
```python
cat1 = space.Categorical([2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
cat2 = space.Categorical([2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

opt = skopt.Optimizer([cat1, cat2])
for n in range(15):
    x = opt.ask()
    print(n, x)
    opt.tell(x, 12*n)
```

which leads to the following error and traceback, which is different from yours:
```
/srv/venv/lib/python3.5/site-packages/sklearn/gaussian_process/kernels.py in __call__(self, X, Y, eval_gradient)
    677         """
    678         if eval_gradient:
--> 679             K1, K1_gradient = self.k1(X, Y, eval_gradient=True)
    680             K2, K2_gradient = self.k2(X, Y, eval_gradient=True)
    681             return K1 + K2, np.dstack((K1_gradient, K2_gradient))

/srv/venv/lib/python3.5/site-packages/sklearn/gaussian_process/kernels.py in __call__(self, X, Y, eval_gradient)
    752         if eval_gradient:
    753             K1, K1_gradient = self.k1(X, Y, eval_gradient=True)
--> 754             K2, K2_gradient = self.k2(X, Y, eval_gradient=True)
    755             return K1 * K2, np.dstack((K1_gradient * K2[:, :, np.newaxis],
    756                                        K2_gradient * K1[:, :, np.newaxis]))

~/skopt/learning/gaussian_process/kernels.py in __call__(self, X, Y, eval_gradient)
    389             raise ValueError(
    390                 "Expected X to have %d features, got %d" %
--> 391                 (X.shape, len(length_scale)))
    392 
    393         n_samples, n_dim = X.shape

TypeError: %d format: a number is required, not tuple
```

So there are at least two things wrong here ;) Could you post a snippet that reproduces your error?

Note: adding a third `Real` dimension stops the exception from occurring in my case.

**Comment by chschroeder** [comment]
I'm sorry, i should have started with the example.

```
from numpy import linalg

from skopt import Optimizer
from skopt.learning import GaussianProcessRegressor
from skopt.space import Categorical


space = [Categorical([1, 2, 3]), Categorical([4, 5, 6])]


opt = Optimizer(space,
                base_estimator=GaussianProcessRegressor(alpha=1e-7),
                acq_optimizer='lbfgs',
                n_initial_points=10)

for i in range(15):
    next_x = opt.ask(n_points=4)
    opt.tell(next_x, [linalg.norm(x) for x in next_x])
```

The key to reproducing the error is setting `acq_optimizer='lbfgs'`. I tried to keep the example minimal but in my own project i use `n_restarts_optimizer`. That's why i needed `acq_optimizer` set to 'lbfgs'.

Adding an additional real dimension is what i did as well :smile:  Seems to work but i cannot tell if and how it will affect the optimization.

**Comment by betatim** [comment]
Workaround: what happens if you use a tree based surrogate instead of a GP? I think this but has to do with our special casing of purely categorical models for GPs. Trees are more natural at handling spaces that have discontinuities in them.

@MechCoder any ideas why this happens?

**Comment by betatim** [comment]
One things I just remembered: if you want to use BFGS as optimiser for your acquisition function you need to be able to compute derivatives which (I think) we don't do for categorical dimensions.

**Comment by chschroeder** [comment]
Using a tree based surrogate means setting base_estimator to 'ET', 'RF' or 'GBRT', right?
This seems to work well so far :+1:. Do you have any recommendations on which tree based surrogate to use?

The fact with the derivates is really good to know. But this also means that what i am doing should not work. So i probably have built a computationally inefficient random search.

Nevertheless, this sound like i should use a tree based approach here. Thank you for your help!

**Comment by betatim** [comment]
In the abstract it is hard to give any advice, I'd try RF, then ET then GBRT. RFs seem to work well most of the time. GBRT let you tease out a bit more performance but probably also need more data (ask&tell pairs).

---

Let's keep this issue open. There are at least two things that need doing:
* create sensible error message for the case of categorical space + user selected BFGS optimizer
* fix the bug that my snippet provokes
