### ISSUE TITLE
TSP - Travelling Salesman Problem

### ISSUE THREAD

**Issue by Borda** [scikit-optimize/scikit-optimize#605]
Hello, may I have about Traveling Salesman Problem, whether it can be solved by this package and if not would you welcome such contribution? Thanks

**Comment by betatim** [comment]
I don't know of anyone who has used sequential model based optimisation for the TSP. What specifically would need contributing?

**Comment by Borda** [comment]
Oki, it seems that I misunderstood the sequential model-based optimisation, I thought that this package would be related to any "general" optimisation...

**Comment by betatim** [comment]
Doesn't seem like anyone here has any experience with bayesian optimisation + TSP. I think for TSP there are better approaches than bayesian optimisation (algorithms that find approximate solutions).

There is nothing stopping you from minimising an arbitrary cost function with skopt though so you could give it a try.

I will close this for the moment. Feel free to re-open if you find out something.
