### ISSUE TITLE
cannot import plot_histogram from skopt

### ISSUE THREAD

**Issue by MyAusweis** [scikit-optimize/scikit-optimize#606]
ImportError                               Traceback (most recent call last)
<ipython-input-3-f80479148da1> in <module>()
      4 from skopt.plots import plot_convergence
      5 from skopt.plots import plot_objective, plot_evaluations
----> 6 from skopt.plots import plot_histogram, plot_objective_2D
      7 from skopt.utils import use_named_args

ImportError: cannot import name plot_histogram

**Comment by chschroeder** [comment]
Take a look at the [current plots.py](https://github.com/scikit-optimize/scikit-optimize/blob/2f04b5b948d8b0a42c0343b6c48ac014f5dc68d1/skopt/plots.py), this function does not exist (yet). The plot_histogram function is part of a recent PR #579, which is not merged yet.

**Comment by betatim** [comment]
@chschroeder is right. Closing for now.

**Comment by chaine09** [comment]
how do you solve this?

**Comment by palashkulsh** [comment]
facing the same for both plot_histogram and plot_objective_2D even when using 0.8.dev0 package version.

![image](https://user-images.githubusercontent.com/5735087/82728664-83d3fd80-9d0f-11ea-8e4c-ae56554e9451.png)
