### ISSUE TITLE
Please, consider issuing a doi via Zenodo

### ISSUE THREAD

**Issue by boccaFF** [scikit-optimize/scikit-optimize#607]
Given the [integration with Zenodo](https://help.github.com/articles/referencing-and-citing-content/), please consider issuing a doi for scikit-optimize so it can be used to be referenced.

**Comment by iaroslav-ai** [comment]
@boccaFF I agree with you. Would be really good to have skopt citable - I also needed to cite it, and will need. Lets see what others say.

**Comment by iaroslav-ai** [comment]
#578

**Comment by iaroslav-ai** [comment]
Done! :tada: 
See the README.rst
