### ISSUE TITLE
Optimizer appears not transform Integer dimensions properly

### ISSUE THREAD

**Issue by pavelkomarov** [scikit-optimize/scikit-optimize#614]
Here is my example:

    from skopt import Optimizer
    from skopt.utils import dimensions_aslist
    from skopt.space import Integer, Categorical, Real

    DTR = {
        'criterion': Categorical(['mse']),
        'max_depth': Integer(2,100)
    }

    listified_space = dimensions_aslist(DTR)
    acq_optimizer_kwargs = {'n_points': 20, 'n_restarts_optimizer': 5, 'n_jobs': 3}
    acq_func_kwargs = {'xi': 0.01, 'kappa': 1.96}

    optimizer = Optimizer(listified_space, base_estimator='gp', n_initial_points=10,
        acq_func='EI', acq_optimizer='lbfgs', random_state=None,
        acq_optimizer_kwargs=acq_optimizer_kwargs, acq_func_kwargs=acq_fun_kwargs)

    rand_xs = []
    for n in range(10):
        rand_xs.append(optimizer.ask())

    rand_ys = [1,2,3,4,5,6,7,8,9,10]

    print rand_xs
    print rand_ys

    optimizer.tell(rand_xs, rand_ys)

Printing inside the Optimizer just before line 450 `self.Xi` and `self.yi` reprints `rand_xs` and `rand_ys`, so great: The optimizer understands what I told it. But then before it fits it goes and transforms the X. Printing `self.space.transform(self.Xi)` I see a 10x2 array full of zeroes.

Holding one of those dimensions in the transformed space as zero makes sense because all input points have 'mse' as the split criterion. But the other is a number that varies on a range, so why doesn't the transformed space reflect that fact? When the GaussianProcessRegressor is fit, it will fit to all y using just this same [0,0] point as the x, which is not useful.

Is there a good reason for this? For most objective functions there should be a relationship between Integer inputs and  Are you normalizing by integer division here?

**Comment by betatim** [comment]
`Real` and `Integer` dimensions are normalised to unit range using https://github.com/scikit-optimize/scikit-optimize/blob/20e46a7163658043d2fa9d790d128bff08ec3f85/skopt/space/transformers.py#L95 In python2 `3/2==1` unless you import from `__future__` as is done at the top of `transformers.py`.

When I run your snippet I get:
```
(Pdb) self.space.transform(self.Xi)
array([[ 0.        ,  0.79591837],
       [ 0.        ,  0.35714286]])
```
so I can't reproduce it at the moment. I use python 3 and you?

**Comment by pavelkomarov** [comment]
I am in Python 2.7

**Comment by iaroslav-ai** [comment]
I also cannot reproduce, on python 2.7:
```python
from skopt import Optimizer
from skopt.utils import dimensions_aslist
from skopt.space import Integer, Categorical, Real

DTR = {
    'criterion': Categorical(['mse']),
    'max_depth': Integer(2,100)
}

listified_space = dimensions_aslist(DTR)
acq_optimizer_kwargs = {'n_points': 20, 'n_restarts_optimizer': 5, 'n_jobs': 3}
acq_func_kwargs = {'xi': 0.01, 'kappa': 1.96}

optimizer = Optimizer(listified_space, base_estimator='gp', n_initial_points=10,
    acq_func='EI', acq_optimizer='lbfgs', random_state=None,
    acq_optimizer_kwargs=acq_optimizer_kwargs)

rand_xs = []
for n in range(10):
    rand_xs.append(optimizer.ask())

rand_ys = [1,2,3,4,5,6,7,8,9,10]

print rand_xs
print rand_ys

optimizer.tell(rand_xs, rand_ys)

print(optimizer.space.transform(rand_xs))
```

This prints 
```bash
[['mse', 78], ['mse', 32], ['mse', 84], ['mse', 67], ['mse', 42], ['mse', 49], ['mse', 28], ['mse', 54], ['mse', 8], ['mse', 56]]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[0.         0.7755102 ]
 [0.         0.30612245]
 [0.         0.83673469]
 [0.         0.66326531]
 [0.         0.40816327]
 [0.         0.47959184]
 [0.         0.26530612]
 [0.         0.53061224]
 [0.         0.06122449]
 [0.         0.55102041]]
```

So something you would expect. Could this be related to specific version of python used, say some python 2.7.x? @pavelkomarov , do you reproduce the issue with the code above?

**Comment by pavelkomarov** [comment]
I still see the problem in skopt 0.4, but if I run the above in 0.5.1 I get the sensible answer. Somewhere along the line this got fixed.
