### ISSUE TITLE
Add expected_minimum to plots

### ISSUE THREAD

**Issue by jonathanng** [scikit-optimize/scikit-optimize#619]
This might be helpful especially in the case of there being a lot of noise.

**Comment by jonathanng** [comment]
I just found out expected_minimum doesn't work with categories.

**Comment by iaroslav-ai** [comment]
Hi @jonathanng ,
What exactly do you mean by `expected_minimum`? Do you mean something like model fit to the convergence curve, so that it can be used to estimate what the minimum value will be, and do the early stopping?

**Comment by iaroslav-ai** [comment]
I apologize - I added the comment a bit hastely. I found that we have already `expected_minimum` :)

**Comment by iaroslav-ai** [comment]
That is a good point @jonathanng about categorical dimensions - if added that would be a bit restricted then. 

What do others think?

**Comment by holgern** [comment]
Implemented in 0.7.2
