### ISSUE TITLE
Determining best estimator for optimizer

### ISSUE THREAD

**Issue by jonathanng** [scikit-optimize/scikit-optimize#620]
I was wondering how people choose their base estimator for their optmizers. Using the below method, I find that gbrt does the best in terms of MSE for my particular data. In fact, gp does very poorly.

Is there something I'm missing? Is there a scenario where it would still make sense to use gp?

Regardless, I'm happy to add this in pull request if people think it would be helpful.

```python
def score_estimators(X, y):

    n_dims = X.shape[1]

    cov_amplitude = skopt.learning.gaussian_process.kernels.ConstantKernel(1.0, (0.01, 1000.0))
    other_kernel  = skopt.learning.gaussian_process.kernels.Matern(
        length_scale=np.ones(n_dims),
        length_scale_bounds=[(0.01, 100)] * n_dims, nu=2.5)

    estimators = {
        'gp':   skopt.learning.GaussianProcessRegressor(
            kernel               = cov_amplitude * other_kernel,
            normalize_y          = True,
            noise                = "gaussian",
            n_restarts_optimizer = 2),
        'rf':   skopt.learning.RandomForestRegressor(n_estimators=100, min_samples_leaf=3),
        'et':   skopt.learning.ExtraTreesRegressor(n_estimators=100, min_samples_leaf=3),
        'gbrt': skopt.learning.GradientBoostingQuantileRegressor(
            base_estimator=sklearn.ensemble.GradientBoostingRegressor(n_estimators=30, loss="quantile"))
    }

    return {name: np.mean(sklearn.model_selection.cross_val_score(
            estimator = estimator,
            X         = X,
            y         = y,
            scoring   = make_scorer(mean_squared_error, False),
            cv        = 5,
            n_jobs    = -1))
            for name, estimator in estimators.items()}
```

**Comment by iaroslav-ai** [comment]
@jonathanng that is a curious behavior. It might be that MSE of the surrogate is not really correlated with the overall performance of the optimization algorithm though. Consider for instance these results of evaluation of skopt:

https://github.com/iaroslav-ai/scikit-optimize-benchmarks

There, on a set of popular optimization tasks, gaussian process based methods in fact allow to achieve the best minima values (but I do not have the MSE of estimators for the data there though).

I think you bring a very interesting question though when asking how to select the estimator for a particular task. Right now this is left to gut feeling of the user. Could you evaluate if the MSE estimation of MSE correlates with the overall quality of the minima found by the algorithm (if it is feasible)?

**Comment by jonathanng** [comment]
This is interesting. Thank you.

I agree MSE is probably poorly correlated with optimization performance. However, in terms of plotting such as `plot_objective`, I think having a good MSE probably works best.

I'll go ahead and close this.

**Comment by betatim** [comment]
I think "gut feeling" is the top feature for choosing the surrogate model. Another thing that you hear people say is that for categorical spaces or spaces with irrelevant dimensions tree based methods "do better". The reasoning is similar to how RFs can deal with categories and irrelevant features for classification/regression. However with tree based models you can't put in any human knowledge via priors/covariance functions which would give support to using GPs.

One thing that would be interesting is a meta-surrogate that switches from a GP to a tree based model after a certain number of evaluations. Or you treat the choice of surrogate model like a bandit problem (similar to how the GPhedge option works for acquisition functions). Would be good to do some literature review on this, someone must have thought of this before.
