### ISSUE TITLE
Evaluate one point with all threads in BayesSearchCV 

### ISSUE THREAD

**Issue by rene-rex** [scikit-optimize/scikit-optimize#623]
Hello

I am using BayesSearchCV to find hyper parameters for an expensive ML problem. However, I don't get why `n_jobs` is at the same time the number of points to asked from the optimizer and the number of parallel threads in the joblib call. Is it possible to have something like `n_points=1, n_jobs=10, cv=10`? Thus, only one point is evaluated each step and the CV uses all threads.

**Comment by iaroslav-ai** [comment]
Thanks @rene-rex for pointing this out! That would be a nice feature to have a finer control over the parallelism. This is kinda on the edge of being a bug even. 

@rene-rex if you would open a PR with `n_points` argument that would be appreciated :) Alternatively, I can take a look later.

**Comment by rene-rex** [comment]
@iaroslav-ai Can do! I will open a PR this week. However, I may need some help regarding proper tests.

**Comment by iaroslav-ai** [comment]
Thanks again @rene-rex  :) Forgot to close this issue.
