### ISSUE TITLE
Confusion around colour coding in documentation

### ISSUE THREAD

**Issue by bstemper** [scikit-optimize/scikit-optimize#624]
The colour coding used in the contour plots seems confusing to me. Looking at the documentation https://scikit-optimize.github.io/notebooks/visualizing-results.html , this plot here
![graph run](https://scikit-optimize.github.io/notebooks/visualizing-results_files/visualizing-results_5_0.png)
suggests that low values (and hence minima) correspond to dark colour and high values to light colours. Just a bit further down, the following image
![graph run](https://scikit-optimize.github.io/notebooks/visualizing-results_files/visualizing-results_9_0.png)
describes the search of the algorithm for these minima where clearly low values seem to correspond to light colours. 

Maybe the colour coding should be mentioned in the documentation and the partial dependence plots possibly annotated just like in the image above for further clarification.

**Comment by betatim** [comment]
Good point. Do you want to make a PR updating the example notebook to use an inverted colour map?
