### ISSUE TITLE
PyPi still has 0.5rc1 instead of 0.5

### ISSUE THREAD

**Issue by ukaratay** [scikit-optimize/scikit-optimize#633]
The last package uploaded to PyPi has timestamp of 2018-01-23 and the latest release on GitHub has 2018-02-04.

Can you guys update the PyPi package?

**Comment by betatim** [comment]
Thanks for spotting this. Turns out when we released 0.5rc1 the tag in `setup.py` was set to 0.5 not 0.5rc1 so when we did cut v0.5 the upload to PyPI failed because there is already a release with v0.5.

I will make a v0.5.1 release later today to replace the old one.
