### ISSUE TITLE
Tests are slow! (episode II)

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#64]
The current build takes more than 15mn, this is very long, given that we dont have so much code yet... We should really try to trim some of the tests.

**Comment by MechCoder** [comment]
Or make the code faster ;)

**Comment by MechCoder** [comment]
But I tend to go with the easier approach, which is trimming the tests.

**Comment by betatim** [comment]
It takes roughly 6minutes to install stuff. Do we really need to use `conda`? There are wheels for `numpy` and such so we could pip install it.

@glouppe did you set the number of iterations in `test_gp_minimize` to the minimum number of iterations needed or just some (big) number for which it works? We could think about reducing them to a number very close to the minimum needed to make the test pass. It would have the added benefit that we would notice quickly when we make the optimiser worse as it would suddenly fail the tests. The risk is that we make innocent changes and start getting false positives.

**Comment by glouppe** [comment]
> It takes roughly 6minutes to install stuff. Do we really need to use conda? There are wheels for numpy and such so we could pip install it.

We could, but the bottleneck is rather the compilation of scikit-learn 0.18-dev. 

> did you set the number of iterations in test_gp_minimize to the minimum number of iterations needed or just some (big) number for which it works? We could think about reducing them to a number very close to the minimum needed to make the test pass. It would have the added benefit that we would notice quickly when we make the optimiser worse as it would suddenly fail the tests. The risk is that we make innocent changes and start getting false positives.

I did not fiddle much. These numbers could certainly be reduced.

**Comment by betatim** [comment]
https://github.com/minrk/wheelhouse has a `scikit-learn` wheel too. If there is something missing we could fork that repo and put in what we need.

I've been using this for everware like so:

```
# In .travis.yml
before_install:
  - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install: 
  - export PIP_OPTIONS="-f ~/travis-wheels/wheelhouse"
  # or
  - pip install -f travis-wheels/wheelhouse -r dev-requirements.txt .
```

(reviewing the setup now to try and document it I wonder if this actually works, so might need a bit of brain power ...)

**Comment by MechCoder** [comment]
I am not an expert in this, but if it reduces the build time feel free to rewrite the `.yml`

**Comment by MechCoder** [comment]
The `lbfgs` solver seems to take some time. We need to limit the number of iterations of the inner lbfgs loop.

**Comment by glouppe** [comment]
Closing this, we can reopen later if needed.
