### ISSUE TITLE
Migrate the docs to sphinx

### ISSUE THREAD

**Issue by chschroeder** [scikit-optimize/scikit-optimize#640]
This is an umbrella issue to track the status of migrating the docs to sphinx. Originally started in #431 by @betatim, we will try now to split this in multiple smaller PRs and break as little as possible in the meantime.

**Scope**
* [ ] *Tooling and prerequisites* (#641): Cherry pick as much as possible from betatim's existing setup.
  * [x] Building the documentation and creating a html version should behave correctly.
  * [x] Include the napoleon plugin so that we can stay with the Numpy docstring style.
  * [ ] Have the first examples show up correctly in the new sphinx docs (to verify that everything is set up correctly).
* [ ] *Migrate the existing docs*
  * *TODO: Divide the task in reasonable chunks and keep track of them here* 
* [ ] Misc
  * [ ] Add citing information (Zenodo DOI)
  * [ ] Update copyright year information (currently "(c) 2017")

**Comment by glouppe** [comment]
Thanks for working on this :)

**Comment by chschroeder** [comment]
No need to thank me, i didn't do much yet ;).

**Comment by holgern** [comment]
Done
