### ISSUE TITLE
Doc: generate examples gallery

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#65]
Would be nice to generate examples upon deployment to build a nice gallery. This would require some changes to `ci_scripts/deploy.sh` and to the templates, but nothing impossible.

**Comment by glouppe** [comment]
What would you think of using notebooks instead of python scripts for the examples? This would allow to give more detailed explanations in a literate programming style (instead of a big chunk of doc + a big chunk of python code).

We are currently using this solution for another package. Notebooks are pushed on github and then automatically shipped with the static documentation (see http://diana-hep.org/carl/ for the documentation and https://github.com/diana-hep/carl/tree/master/examples for the notebooks).

**Comment by MechCoder** [comment]
That's a great idea. I can work on the IPython notebooks over the weekend.

**Comment by betatim** [comment]
👍 from me too. While we are at it we should investigate `thebe` + `tmpnb` so we can make them runnable from the docs. (We might not have much content yet, but we will have the coolest docs in town!)

**Comment by glouppe** [comment]
Fixed as #100. Next step is to actually write the notebooks :)

The python scripts in `examples` should be replaced accordingly.
