### ISSUE TITLE
retrieve minimum location and plot results from the Optimizer class

### ISSUE THREAD

**Issue by aleva85** [scikit-optimize/scikit-optimize#657]
Hi guys,

apologies for this basic question. 

minimizing a function using gp_minimize() returns an object that contains the minimum location, value, etc. However, to design an interactive experiment I like the ask() and tell() approach of the Optimizer class. what is the best way to retrieve the minimum when performing the optimization this way (as in your ask and tell notebook)?

Also, are there any plotting functionalities for the Optimizer class? like the plot_objective() and plot_evaluations() for the output of *_minimize() functions.

thanks a lot and congratulations for this project!

**Comment by jwcarr** [comment]
This initially confused me too. The tell method returns the result object you're looking for:

`result = opt.tell(blah, blah)`

You can then pass `result` to the plotting functions as normal.

**Comment by aleva85** [comment]
thanks for the quick reply!

**Comment by iaroslav-ai** [comment]
Yup that is the way to do it. Thanks @jwcarr !
I close this, let me know if the suggestion does not work.
