### ISSUE TITLE
When I install scikit-optimize, "No matching distribution found for scikit-optimize"

### ISSUE THREAD

**Issue by jiangniao26** [scikit-optimize/scikit-optimize#662]
I do `pip install scikit-optimize`, but it shows that,

Collecting scikit-optimize

  Could not fetch URL https://pypi.python.org/simple/scikit-optimize/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping
  Could not find a version that satisfies the requirement scikit-optimize (from versions: )
No matching distribution found for scikit-optimize

How can I deal with this problem?

**Comment by iaroslav-ai** [comment]
Hello @jiangniao26 ,
Just tried in Ubuntu 16.04 container with python2.7 and pip v8.1.1, installation seems to work. Could you share more details about your system, in particular `pip` and `python` versions, and OS that you use?

**Comment by jiangniao26** [comment]
Thanks @iaroslav-ai. It works now.
