### ISSUE TITLE
All cores being used even with `n_jobs=1`

### ISSUE THREAD

**Issue by Nikoleta-v3** [scikit-optimize/scikit-optimize#680]
Hello, thank you very much for this project. I am currently using it for some game theoretic research. 

When running the example for Bayesian optimisation from the tutorial: https://scikit-optimize.github.io/notebooks/bayesian-optimization.html 

```
import numpy as np

noise_level = 0.1

def f(x, noise_level=noise_level):
    return np.sin(5 * x[0]) * (1 - np.tanh(x[0] ** 2)) + np.random.randn() * noise_level

from skopt import gp_minimize

res = gp_minimize(f,                  # the function to minimize
                  [(-2.0, 2.0)],      # the bounds on each dimension of x
                  acq_func="EI",      # the acquisition function
                  n_calls=15,         # the number of evaluations of f 
                  n_random_starts=5,  # the number of random initialization points
                  noise=0.1**2,       # the noise level (optional)
                  random_state=123) 
```
**All my cores are being used.** This happens even when calling with `n_jobs=1`. Here is a screenshot showing the code and all 64 cores on a machine being used.

![screenshot from 2018-05-16 12-29-32](https://user-images.githubusercontent.com/19708408/40114698-cea265d6-5905-11e8-9157-a0e6e0334e6e.png)

I have looked at the source code myself, including several print statements. The `n_jobs` value does not seem to be changing but I have been unable to identify the problem.

**Comment by drvinceknight** [comment]
I have reproduced this same error, here's a screen grab on my machine:

![all_cores_skopt](https://user-images.githubusercontent.com/2131546/40115033-ff58d966-5906-11e8-854c-c30ee832814b.png)

**Comment by betatim** [comment]
Could you check if this is the same issue as in https://github.com/scikit-optimize/scikit-optimize/issues/563?

If not we need to do some digging/debugging.

**Comment by Nikoleta-v3** [comment]
Hey @betatim. It appears to be the same issue as #563. Thank you for your reply, I am closing this.
