### ISSUE TITLE
BayesSearchCV returns a TypeError when starting a search on the 9th (0 indexed) subspace 

### ISSUE THREAD

**Issue by DNeems** [scikit-optimize/scikit-optimize#683]
TypeError: ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

search = {
    'model': [RGFClassifier(loss = 'Log' ,n_jobs = 1,verbose = False, max_leaf = 2,n_estimators= 5)],
    'model__learning_rate': Real(0.0001, 1, prior = 'uniform'),
    'model__l2': Real( 1e-30, 10,prior = 'uniform'),
    'model__algorithm': Categorical(["RGF","RGF_Opt"], transform = 'identity'),
    'model__min_samples_leaf' : Integer(2, 20,transform = 'identity'),
    'model__opt_interval' : Integer(50, 500, transform = 'identity')

    }

opt = BayesSearchCV(
    pipe,
    search_spaces = search, 
    n_iter = 250,
    verbose = 1,
    cv = list(ps.split())
     # (parameter space, # of evaluations)
)
Z = opt.fit(Input_Full_X,y)

Some debugging shows the error comes from this line "dists = pdist(X / length_scale, metric='euclidean') in /usr/local/lib/python3.6/site-packages/sklearn/gaussian_process/kernels.py

And its caused by this row  'model__algorithm': Categorical(["RGF","RGF_Opt"], transform = 'identity') in the search space having the transform = 'identity' , 'OneHot' does work.  

This may not be a bug but better documentation around this error might be nice

**Comment by iaroslav-ai** [comment]
@DNeems thanks for reporting this!

**Comment by holgern** [comment]
Is fixed in version 0.7
