### ISSUE TITLE
Pass parameter from BayesSearchCV fit function to original algorithm fit function 

### ISSUE THREAD

**Issue by Marc0935** [scikit-optimize/scikit-optimize#689]
I applied skopt BayesSearchCV function to optimize hyper parameters for lightGBM algorithm. 

In the sklearn wrapper of lightGBM algorithm, learn rate decay for each iteration can only be achieved using callbacks function in the fit function of the algorithm.

My question is how I can pass parameter/callback function from BayesSearchCV fit function to original algorithm fit function?

Or there is another way to tackle the question?

**Comment by betatim** [comment]
The API of `BayesSearchCV` is guided by the `GridSearchCV` classes in scikit-learn. Do you know what they do for passing arbitrary parameters through?

I am not that familiar with lightGBM, can you point us to an example for what you want to do? Maybe understanding the use case a bit better helps with figuring out a nice way to do this.

**Comment by Marc0935** [comment]
I have no idea how GridSearchCV passing parameters. 

I will just use the following dummy codes for explanation:

Normally, I will implement learn rate decay in lightgbm as follows:

import lightgbm as lgb
Model=lgb.LGBMClassifier(**param, objective='binary')
Model.fit(X, Y, eval_metric=['auc'], callbacks=[lgb.reset_parameter(learning_rate=LR_List)]) 
##LR_List is a list that contains reduced learn rate.

I would like to tune the hyper parameters for the algorithm using BayesSearchCV. I wish to know how I can pass the callbacks from BayesSearchCV fit function back to algorithm fit function.

**Comment by betatim** [comment]
You can't currently pass arbitrary parameter to `BayesSearchCV.fit()` that get forwarded to your model's `fit()` method.

**Comment by Marc0935** [comment]
OK, good to know!

Do we have a workaround for this question? If not, feel free to close the case.

Thanks!

**Comment by iaroslav-ai** [comment]
Hi @Marc0935 ,
it seems like `fit_params` property of `BayesSearchCV` might do the trick. Can it help or are you looking for something else?

**Comment by Marc0935** [comment]
Hi @iaroslav-ai 
Thanks for your suggestion! I will try it and give you the feedback.

**Comment by Marc0935** [comment]
Hi @iaroslav-ai 
I have tried to pass the setting via fit_params. I think that fit_params passes setting to BayesSearchCV .fit function but not to the original algorithm fit. Do you have a way to pass setting to the original algorithm fit from BayesSearchCV?

**Comment by M-e-r-c-u-r-y** [comment]
@Marc0935 I've used BayesSearchCV to search and find best parameters for a Keras NN.

The general way is as described in the pseudo code below:

`bayes_search = BayesSearchCV(#model,parameter search space here)
#Extract best parameters
best_params = bayes_search.best_params_
clf = model(**best_params)
clf.fit(X,y)`

You can look at In[9] and In[10] for a more actual code
[Neural Network Classifier using Bayesian Search.ipynb](https://github.com/M-e-r-c-u-r-y/Machine-Learning/blob/master/Kaggle/Titanic/Neural%20Network%20Classifier%20using%20Bayesian%20Search.ipynb)

I hope this helps :)

**Comment by Marc0935** [comment]
@M-e-r-c-u-r-y @iaroslav-ai 
Thanks for your help! I have found an alternative approach to solve this problem by rewriting my script using another wrapper for LGBM

**Comment by KrunalDatascience** [comment]
@Marc0935 : Hi can you please share the wrapper code?
