### ISSUE TITLE
Parameter names in callback results in BayesSearchCV

### ISSUE THREAD

**Issue by ibackus** [scikit-optimize/scikit-optimize#698]
I'm trying to use a callback function to echo out results after each iteration when optimizing with `BayesSearchCV`, using the callback API, including hyper parameter values and names.

I'm able to get the results `dict`, but I can't keep track of the hyper parameter values since the results `dict` only contains the parameter values, not the parameter names.  I've tried inferring the parameter names from the search space, `results['space'].dimensions`, in the results, but this fails because the `name` attribute of the dimensions does not seem to be preserved except for `Categorical` dimensions.  For `Real` and `Integer` types, the name is reported as `None`.  This is a problem since the parameters get re-ordered.

Maybe I'm going about this wrong, but is there a way to pass the hyper parameter names and values to a callback function in `BayesSearchCV.fit`?

**Comment by iaroslav-ai** [comment]
Hello @ibackus ,
Here is one example how you can echo out the hyperparameter values tried:
```python
from skopt import BayesSearchCV
from skopt.utils import point_asdict

from sklearn.datasets import load_iris
from sklearn.svm import SVC

X, y = load_iris(True)

search_space = {
    'C': (0.1, 10.0)
}

model = BayesSearchCV(
    estimator=SVC(), search_spaces=search_space
)

def cb(v):
    last_point = v.x_iters[-1]
    p = point_asdict(search_space, last_point)
    print(p)

model.fit(X, y, callback=cb)
```
Beware that above will work with search space being a dictionary, but not a list of dictionaries. 

Another way would be to inherit a class that is used as an estimator, and override a `set_params` method, which is used by BayesSearchCV to output the parameters. This should work also with search over multiple spaces, defined by the list of dictionaries. Here is how that would look like:

```python
from skopt import BayesSearchCV
from skopt.utils import point_asdict

from sklearn.datasets import load_iris
from sklearn.svm import SVC

X, y = load_iris(True)

search_space = {
    'C': (0.1, 10.0)
}

class MySVC(SVC):
    def __init__(self, C=0.1):
        super().__init__(C)

    def set_params(self, **params):
        print(params)
        super().set_params(**params)

model = BayesSearchCV(
    estimator=MySVC(), search_spaces=search_space
)

model.fit(X, y)
```
This requires you to modify the estimator though.

**Comment by ibackus** [comment]
Thanks for the response, this is just what I was looking for. 

I have used your second solution (overriding `set_params`), but that is not ideal for many use cases.

Your first solution works perfectly for me, I was not aware of `point_asdict`.  Thank you!

**Comment by iaroslav-ai** [comment]
Ok then :)

**Comment by richy1996** [comment]
Few more things I've ran into when trying to use a list of dictionaries to search over, you can use a more general version of Iaroslav's 2nd approach like
```python
X, y = load_iris(return_X_y=True)

search_space = {
    'C': (0.1, 10.0)
}

class MySVC(SVC):
    def set_params(self, **params):
        print(params)
        return super().set_params(**params)

model = BayesSearchCV(
    estimator=MySVC(),
    search_spaces=search_space
)
```

However when you pass ```n_jobs=-1```, I couldn't get it to print until the end. So with help from chatgpt I arrived at
```python
search_spaces = [
    {'C': (0.1, 10.0)},
    {'C': (0.01, 1.0)}
]

def cb(v):
    # Iterate over search spaces to find the correct space for the current point
    for space in search_spaces:
        try:
            p = point_asdict(space, v.x_iters[-1])
            print(p)
            break
        except ValueError:
            continue

model = BayesSearchCV(
    estimator=SVC(),
    search_spaces=search_spaces,
    n_jobs=-1  # Use all available cores in parallel
)
```
which seems to work for lists of dictionaries as well.

A version that works for the 3rd option in search_spaces, list of tuples
```python
def cb(v):
    # Iterate over search spaces to find the correct space for the current point
    for space, _ in search_spaces:
        try:
            p = point_asdict(space, v.x_iters[-1])
            print(p)
            break
        except ValueError:
            continue
```

Finally a general version to handle all 3 cases
```python
def generalized_callback(v):
    """
    Callback function to print the parameters being evaluated.
    Handles dictionaries, lists of dictionaries, and lists of tuples.
    """
    # If search_spaces is a dictionary
    if isinstance(search_spaces, dict):
        spaces = [search_spaces]
    # If search_spaces is a list of dictionaries or tuples
    else:
        spaces = [space if isinstance(space, dict) else space[0] for space in search_spaces]
    
    # Iterate over the spaces to find the correct space for the current point
    for space in spaces:
        try:
            p = point_asdict(space, v.x_iters[-1])
            print(p)
            break
        except ValueError:
            continue
```
