### ISSUE TITLE
CheckpointSaver

### ISSUE THREAD

**Issue by MotoRZR** [scikit-optimize/scikit-optimize#701]
Has it been removed?  On import I get a not found error.

**Comment by dlf57** [comment]
I was able to remedy this by cloning and ```pip install -e.```. It is not ideal but it does allow for importing CheckpointSaver if you need it.

**Comment by tritemio** [comment]
`CheckpointSaver` is available only in the latest version on master, post 0.5.2.

If you installed scikit-optimize with pip you can upgrade to the latest master with

```
pip install git+https://github.com/scikit-optimize/scikit-optimize/ --upgrade
```

**Comment by MotoRZR** [comment]
Thanks!
