### ISSUE TITLE
Categorical dimensions with identity transform converts [True,False] to [1.0, 0.0]

### ISSUE THREAD

**Issue by thomasahle** [scikit-optimize/scikit-optimize#702]
I have a dimension with the type
```
    Categorical([True, False], transform='identity')
```
During the first 10 iterations (the random ones)`opt.ask()` returns either `True` or `False` on this dimension. However once it starts actually using gaussian optimization, the variable changes to `1.0` or `0.0`.

This doesn't actually break anything in my code since 1.0 and 0.0 have the right truth values in python, but it still seems surprising and unintended.

I use `scikit-optimize==0.5.2` with Python 3.6.5.

**Comment by holgern** [comment]
True is now converted to True for the identity transformer (since 0.7)
