### ISSUE TITLE
Citing scikit-optimize

### ISSUE THREAD

**Issue by tritemio** [scikit-optimize/scikit-optimize#705]
I am using scikit-optimize in an upcoming paper. What would be the preferred citation style for this library?

**Comment by betatim** [comment]
Please cite https://zenodo.org/record/1207017

**Comment by tritemio** [comment]
Perfect, I will.

**Comment by Delphi89** [comment]
Hi,

At the recommended page I found: 

Cite as
Tim Head, MechCoder, Gilles Louppe, Iaroslav Shcherbatyi, fcharras, Zé Vinícius, … Alexander Fabisch. (2018, March 25). scikit-optimize/scikit-optimize: v0.5.2 (Version v0.5.2). Zenodo. http://doi.org/10.5281/zenodo.1207017

Please be aware some conferences and IEEE standard for articles do not accept web links.
Any idea on how to use the above for a standard citation?

**Comment by xolotl90** [comment]
Is it possible to update the zenodo entry? I see some contributors in the insights that are not listed in the old entry (which is from 2018).
