### ISSUE TITLE
Wrong iteration number after loading CheckPointSaver object

### ISSUE THREAD

**Issue by anhnt1** [scikit-optimize/scikit-optimize#707]
Hi,
I ran 2 iterations and got an object from CheckPointSaver, I then load the object and run the program again. skopt starts with iteration number 2, not 3. 
I want to know it is intended behaviour or not? 
Thanks,
Tuan

**Comment by iaroslav-ai** [comment]
Hi @anhnt1 , thanks for letting us know. Could you share a code example which works differently from what you would expect?

I have tried similar scenario as yours with the code below:
```python
from skopt import dump, load
from skopt.callbacks import CheckpointSaver
from skopt import gp_minimize
import os

extra_args = {}

fpath = 'checkpoint.bin'
if os.path.exists(fpath):
    res = load(fpath)
    extra_args = {'x0': res.x_iters, 'y0': res.func_vals}

iteration = [0]

def dummy_objective(x):
    iteration[0] += 1
    print("Iteration #", iteration[0])
    if iteration[0] == 5:
        raise BaseException('Something went wrong')
    return 0

gp_minimize(
    func=dummy_objective,
    dimensions=[(0.0, 10.0), (0.0, 10.0)],
    callback=CheckpointSaver(fpath, store_objective=False),
    **extra_args
)
```
This seems to work as expected - skopt runs every time for 5 iterations.

**Comment by anhnt1** [comment]
Hi @iaroslav-ai ,

Not sure that I understand the doc correctly. In the following code, I want to run a dummy function 10 iterations, stop it, load the object, continue to run it with 5 iterations (15-10=5, using the previous results). It does not work as I expected.

Thanks,
Tuan

```ruby
from skopt import dump, load
from skopt.callbacks import CheckpointSaver
from skopt import gp_minimize
import os


fpath = '/tmp/checkpoint.bin'

def dummy_objective(x):
    return x[0] + x[1]

gp_minimize(
    func=dummy_objective,
    dimensions=[(0.0, 10.0), (0.0, 10.0)],
    callback=CheckpointSaver(fpath, store_objective=False),
    n_calls=10, verbose=True, random_state=123
)

res = load(fpath)
x0 = res.x_iters
y0 = res.func_vals

gp_minimize(
    func=dummy_objective,
    dimensions=[(0.0, 10.0), (0.0, 10.0)],
    callback=CheckpointSaver(fpath, store_objective=False),
    n_calls=15,
    x0=x0,
    y0=y0, verbose=True, n_random_starts=0, random_state=123
)
```

**Comment by iaroslav-ai** [comment]
Ah, I see. The reason is because the size of `x0`, `y0` is not subtracted from the total number of iterations `n_calls` that the algorithm will be run. The right way would be to subtract the length of `x0` from the `n_calls` in the second case.
It is assumed that `x0`, `y0` might not only come from some prior runs, but from other sources, like manual evaluation. Hence these are considered more of a 'prior knowledge', or 'warm start' for an algorithm. 
Maybe a better doc would be a solution.

**Comment by anhnt1** [comment]
I see. The doc now is ok for me. Another issue: if you run the small doc I wrote above, you will notice that the result of iteration 10 (the final iteration of the first gp_min) and the result of iteration 1 of the second gp_min are the same. I run it several times, and always observe this issue. Is it intended or not?

**Comment by anhnt1** [comment]
Hi,
Have you got any clues about the relation between n_restarts_optimizer, n_random_starts and the number of params of a objective function?
Thansk,
Tuan
