### ISSUE TITLE
Integer dimension with log-uniform as prior

### ISSUE THREAD

**Issue by DavidS3141** [scikit-optimize/scikit-optimize#712]
I could not find a issue addressing this, so here it goes.

I use this wonderful tool for hyper parameter tuning of neural networks. One common parameter is for e.g. the batch size, good values go usually from 32 to the order of 1000 depending on the project and the size of the dataset, as well as some other minor things. This is a parameter which should be probed logarithmically, so a prior log-uniform key like the one for Reals would make a lot of sense.

Right now I am emulating this by using actually a Real batch_size and inside my neural network casting it to an integer, as well as manually caching results for the same batch size (and the other parameters, which happens rarely I admit).

Is there a design reason I am not seeing, why this functionality was left out for the Integer class?

**Comment by holgern** [comment]
Solved in 0.7
