### ISSUE TITLE
Get rid of hardcoded strings in cook_estimator

### ISSUE THREAD

**Issue by KOLANICH** [scikit-optimize/scikit-optimize#713]
https://github.com/scikit-optimize/scikit-optimize/blob/b350fa880a4326f913d070b8803d63b477cff024/skopt/utils.py#L315
https://github.com/scikit-optimize/scikit-optimize/blob/b350fa880a4326f913d070b8803d63b477cff024/skopt/utils.py#L338
https://github.com/scikit-optimize/scikit-optimize/blob/b350fa880a4326f913d070b8803d63b477cff024/skopt/utils.py#L341
https://github.com/scikit-optimize/scikit-optimize/blob/b350fa880a4326f913d070b8803d63b477cff024/skopt/utils.py#L344
https://github.com/scikit-optimize/scikit-optimize/blob/b350fa880a4326f913d070b8803d63b477cff024/skopt/utils.py#L348

Hardcoded strings disallow registering an esimator easily. Also hardcoded strings disallow autocomplete. We should get rid of passing strins entirely, instead pass objects.

**Comment by betatim** [comment]
This API follows the scikit-learn convention that you can provide string names for some commonly used options. You can already pass in your own regressor instance if you want to use a different one or want to use (say) a GP but with different hyper-parameters.

**Comment by KOLANICH** [comment]
>This API follows the scikit-learn convention that you can provide string names for some commonly used options.

I guess then

```python
if isinstance(a, str),
   a=getattr(..., a)
```

should do the trick.

>You can already pass in your own regressor instance if you want to use a different one or want to use (say) a GP but with different hyper-parameters.

I have already realized, but thank you anyway.

**Comment by betatim** [comment]
```
if isinstance(base_estimator, str),
   base_estimator=getattr(..., base_estimator)
```

Will not work because the shortcut names are not equal to the class names. This is on purpose.

**Comment by KOLANICH** [comment]
>This is on purpose.

What is it?

**Comment by holgern** [comment]
The cook_estimator returns only builtin estimators, it is easily possible to create an own minize function with a new estimator
