### ISSUE TITLE
Nested resampling using skopt

### ISSUE THREAD

**Issue by aminevsaziz** [scikit-optimize/scikit-optimize#725]
Can anyone provide some help on how to perform nested CV with Skopt(let's suppose it's 5cv inner and 5 cv in the outer). Also the hyperparameters are tuned in inner loop and tested against the outer .... And finally how to use the final model to predict over set of dataset.

**Comment by iaroslav-ai** [comment]
@aminevsaziz feel free to reopen if this still does not solve your issue.

**Comment by hnikana** [comment]
@iaroslav-ai How do you use gp_minimize and give the search space . 
the search space is made from two part : reg (clf) parametes and fit parameters . 
`python`
    def f_2_min(model, model_conf , fit_conf):
        model.set_params(model_conf)
        scores =vcross_val_score(model,X_train,y, cv=3, scoring='f1_micro' , fit_params=fit_conf)
        return -np.mean(scores)
