### ISSUE TITLE
How to pass parameter to the estimator's fit() method

### ISSUE THREAD

**Issue by jy03189211** [scikit-optimize/scikit-optimize#728]
for model such as  xgboost or lightboost

the parameters like:
```
eval_sets
early_stopping_round
```

are for the `fit` or `train` method only instead of class constructor `LGBMRegressor`
so the `BayesSearchCV` does not accept them as parameter, how can I set a value for early stopping rounds then?

**Comment by arash-stripe** [comment]
There's functionality for passing in parameters that are used in the fit() method through the 'fit_params' parameter in `BayesSearchCV`.

e.g.
```
BayesSearchCV(
            estimator=estimator,
            search_spaces=search_spaces,
            fit_params={
                'eval_set': [(data.X_test.values, data.y_test.values)],
                'eval_metric': 'logloss',
                'early_stopping_rounds': 10,
                'verbose': False
            },
            scoring=self.get_scoring_function(),
            n_iter=NUM_ITERATIONS,
            cv=self.get_predefined_split(),
            return_train_score=True
        )
```

**Comment by iaroslav-ai** [comment]
Thank you @arash-stripe for a great explanation! Closing this, but @jy03189211 if you still have questions feel free to reopen.
