### ISSUE TITLE
Minimize a function which is a function of the gaussian process?

### ISSUE THREAD

**Issue by samlaf** [scikit-optimize/scikit-optimize#732]
I am trying to minimize a function f(x).
I have a prior on this function g(x), with assumption that the difference diff(x) = f(x)-g(x) is a simple function (low order polynomial) which should be easier to learn than f(x), so I want to build the GP on the difference.
But, I want the sampled points to minimize f(x) (diff(x) + g(x)) instead of diff(x). Is this possible?

Essentially I would want the function that acq_func is using to be different from the GP function.

**Comment by iaroslav-ai** [comment]
This should be feasible, but I do not see an easy way. If you / someone else is looking into this, the first step would be to clone the repo, and try to extend 
https://github.com/scikit-optimize/scikit-optimize/blob/68e6d41d81703a6695bbdf6c7d151fc6adb2b7c6/skopt/learning/gaussian_process/gpr.py#L39
To see if you can implement a surrogate that corresponds to your assumptions. Then work from there on how to integrate it with the rest of optimization functionality in skopt.

**Comment by samlaf** [comment]
I ended up using GPy instead. I think the easiest way would be to allow scikit-optimize to have mean functions (which I believe is not possible at the moment?). Anyway I won't be working on this, sorry. You can close this.
