### ISSUE TITLE
support for probability distribution/weights vector as input for optimisation

### ISSUE THREAD

**Issue by eamonnmag** [scikit-optimize/scikit-optimize#734]
Is there a way of providing a set of weights, that should add up to 1 for example as a parameter to some optimisation function?

If the weights are provided independently, there is of course no way of guaranteeing they add up to 1. 

e.g. 0.2, 0.5, 0.3 would be provided as one set of parameters to a function, as would 0.1, 0.2, 0.7.  

I currently pass through 2 Real parameters and a random set of 1000 dirichlet distributions as categories.

This is obviously not very good for optimisation since I can only switch categories, not modify individual weights.

**Comment by betatim** [comment]
You want weights for the different choices in a `Categorical` dimension? If yes check out the 'prior' argument https://github.com/scikit-optimize/scikit-optimize/blob/692c21d35f4ebfb054171a3e1986a6f248da1b83/skopt/space/space.py#L391-L412

**Comment by eamonnmag** [comment]
So let's see. Imagine I have a function

```
def optimize(p1, p2, w_section1, w_section2, w_section3):
    # w1, w2, and w3 must add up to 1. 
    s1 = calc(p1, p2, 'section1')
    s2 = calc(p1, p2, 'section2')
    s3 = calc(p1, p2, 'section3')

    x = s1*w_section1+s2*w_section2+s3*w_section3/
         w_section1 + w_section2 + w_section3
    return 1-x
```

I don't think (imo) that Categorical with weights is the correct approach, but I could be wrong. 

I want to optimise on w_section1, w_section2, and w_section3 as well as p1 and p2 to discover the optimal weights. But if w_section1 is moved from 0.6 to 0.7, then w_section2 and w_section3 are modified to reduce their combined weight by 0.1 also.

**Comment by betatim** [comment]
Aha!

I think of that as a constraint problem, not sure if that is the right jargon though. Short answer: no there is no way to do that in scikit-optimize out of the box.

What I'd do is (taking your example above):
```python
def optimize(p1, p2, w_section1, w_section2):
    # w1, w2, and w3 must add up to 1. 
    s1 = calc(p1, p2, 'section1')
    s2 = calc(p1, p2, 'section2')
    s3 = calc(p1, p2, 'section3')

    # assuming w_section1 and w_section2 are Real(0, 1.)s
    if w_section1 + w_section2 > 1.
        return 100  # some really big number to signal "illegal combination"
    w_section3 = 1 - w_section1 - w_section2

    x = s1*w_section1+s2*w_section2+s3*w_section3/
         w_section1 + w_section2 + w_section3
    return 1-x
```
it is a bit of a bodge :-/

**Comment by eamonnmag** [comment]
This works, I was hoping that it would be something that was built in but not super obvious from the documentation, but this covers my need :)

Thanks Tim!
