### ISSUE TITLE
How can I parallelize a `gp_minimize` over several GPUs? 

### ISSUE THREAD

**Issue by frederikfaye** [scikit-optimize/scikit-optimize#737]
I have eight GPUs at my disposal for doing a hyperparameter search for a neural network, but for i/o reasons, I would like to not divide minibatches between them. 

Until now, I've made eight separate, but identical `gp_minimize` calls, one for each GPU. This creates eight distinct `res.models` objects. However, it would clearly be better if all eight GPUs could contribute to create a single `res`, with a single `models` object (that would then have eight times the information available to make a decision about where to sample next). 

How can I make this possible? Ideas for hacks and quick fixes are appreciated if no canonical way exists.

**Comment by betatim** [comment]
I would use https://scikit-optimize.github.io/#skopt.Optimizer directly (this is the workhorse behind `gp_minize`) and `ask()` for eight points, evaluate each on one of your GPUs and iterate that way.

**Comment by frederikfaye** [comment]
Thanks for the suggestion, this seems to be exactly what I was looking for.

However, I'm a bit unsure of the implementation. `ask()` samples from one's search space, but how do I actually give the score found from evaluating a sampled point to my `Optimizer` instance? A minimal example would be awesome.

**Comment by betatim** [comment]
Check out the docstrings for the `Optimizer` class. `ask()` gives you points to evaluate and `tell()` let's you give them back to the optimizer (with the result of evaluating them). You could also look at the code of `base_minimize()` which is what `gp_minimize` uses as all our minimize functions use `Optimzier`.

https://github.com/scikit-optimize/scikit-optimize/blob/master/examples/ask-and-tell.ipynb is a minimal example.

**Comment by frederikfaye** [comment]
@betatim Nice, that got me started, thank you! 

How can I keep track of dimension names when using `tell()`? For `gp_minimize` I simply used `utils.use_named_args` - is this (or something similar) possible in this scenario as well?

**Comment by imayachita** [comment]
Hi @frederikfaye @betatim,
Thanks for the code example for GPU parallelization. However, I have a couple of questions:
(1) How can I change the objective function to be able to accept multiple parameters?
(2) In the case of using this to find the best hyperparameters set, I would also like to have fixed hyperparameters as the objective function parameters?

Thank you very much
