### ISSUE TITLE
Space names not preserved by gp_minimize

### ISSUE THREAD

**Issue by david-waterworth** [scikit-optimize/scikit-optimize#742]
I'm using `@use_named_args` with `gp_minimize`. The `Space` object returned by `gp_minimize` doesn't appear to preserve the names. i.e. in the code below, the named args are correctly passed to the objective function, but the `Space` object contained in the returned result has None for names. I'm trying to construct a dict of the original parameter names and the optimal values. I want to match names and x from res as I want to recreate `best_params` as `**kwargs` from a dump file.

```
space = [Integer(250, 2000, name='n_estimators')]

@use_named_args(space)
def objective(n_estimators):
    print(f'score: {n_estimators}')
    return n_estimators

res = gp_minimize(objective, space, n_calls=10, random_state=0)
print(f'best_score: {res.fun}')
        
best_params = dict(zip((s.name for s in res.space),res.x))
print(best_params)  # fails due to names not preserved

print([s.name for s in res.space])
```

**Comment by alois-bissuel** [comment]
I think this might be fixed by #668, but alas it is not included in the latest release.
See #754.
