### ISSUE TITLE
Cannot pass Space to gp_minimize

### ISSUE THREAD

**Issue by david-waterworth** [scikit-optimize/scikit-optimize#743]
gp_minimise fails if you pass a `Space` as the `space` argument with the error below. 

> ~/.pyenv/versions/3.7.1/envs/jupyter-3.7.1/lib/python3.7/site-packages/skopt/utils.py in wrapper(x)
>     623             # Ensure the number of dimensions match
>     624             # the number of parameters in the list x.
> --> 625             if len(x) != len(dimensions):
>     626                 msg = "Mismatch in number of search-space dimensions. " \
>     627                       "len(dimensions)=={} and len(x)=={}"
> 
> TypeError: object of type 'Space' has no len()

It expects a list which is internally converted to a `Space`. I wanted to check outside of gp_minimise if the starting x0 was inside the space rather than catch the exception, i.e. 

```
if x0 in Space(space):
    print('x0 is not in space')
```
as the exception is a generic `ValueError`. Ideally it would be a specific exception i..e. `NotInSpaceError`

**Comment by stefanocereda** [comment]
This code works for me:
```
D = [[-5.0, 10.0], [0.0, 15.0]]
space = skopt.utils.normalize_dimensions(D)
skopt.gp_minimize(skopt.benchmarks.branin, space)
```
Can you provide a full example?

**Comment by iaroslav-ai** [comment]
Hi @david-waterworth, let us know if you still have an issue. I close this for now as the issue seems stale, but feel free to reopen!
