### ISSUE TITLE
error for tune logistic regression

### ISSUE THREAD

**Issue by developpeur-windev-php-python** [scikit-optimize/scikit-optimize#749]
Hi,

I try to run this code
opt = BayesSearchCV(
    LogisticRegression(),
    {
       'penalty':['l1', 'l2'],
             'C': np.logspace(-4, 4, 20),
    },
    n_iter=32
)

opt.fit(X_train, y_train)

print("val. score: %s" % opt.best_score_)
print("test score: %s" % opt.score(X_test, y_test))

But i have always this error

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-596e1e806cc5> in <module>
     15 
     16 
---> 17 opt.fit(X_train, y_train)
     18 
     19 print("val. score: %s" % opt.best_score_)

e:\Anaconda3\lib\site-packages\skopt\searchcv.py in fit(self, X, y, groups, callback)
    652                 optim_result = self._step(
    653                     X, y, search_space, optimizer,
--> 654                     groups=groups, n_points=n_points_adjusted
    655                 )
    656                 n_iter -= n_points

e:\Anaconda3\lib\site-packages\skopt\searchcv.py in _step(self, X, y, search_space, optimizer, groups, n_points)
    539 
    540         # get parameter values to evaluate
--> 541         params = optimizer.ask(n_points=n_points)
    542         params_dict = [point_asdict(search_space, p) for p in params]
    543 

e:\Anaconda3\lib\site-packages\skopt\optimizer\optimizer.py in ask(self, n_points, strategy)
    370                 opt._tell(x, (y_lie, t_lie))
    371             else:
--> 372                 opt._tell(x, y_lie)
    373 
    374         self.cache_ = {(n_points, strategy): X}  # cache_ the result

e:\Anaconda3\lib\site-packages\skopt\optimizer\optimizer.py in _tell(self, x, y, fit)
    484             with warnings.catch_warnings():
    485                 warnings.simplefilter("ignore")
--> 486                 est.fit(self.space.transform(self.Xi), self.yi)
    487 
    488             if hasattr(self, "next_xs_") and self.acq_func == "gp_hedge":

e:\Anaconda3\lib\site-packages\skopt\learning\gaussian_process\gpr.py in fit(self, X, y)
    193                 noise_level=self.noise, noise_level_bounds="fixed"
    194             )
--> 195         super(GaussianProcessRegressor, self).fit(X, y)
    196 
    197         self.noise_ = None

~\AppData\Roaming\Python\Python36\site-packages\sklearn\gaussian_process\gpr.py in fit(self, X, y)
    230             optima = [(self._constrained_optimization(obj_func,
    231                                                       self.kernel_.theta,
--> 232                                                       self.kernel_.bounds))]
    233 
    234             # Additional runs are performed from log-uniform chosen initial

~\AppData\Roaming\Python\Python36\site-packages\sklearn\gaussian_process\gpr.py in _constrained_optimization(self, obj_func, initial_theta, bounds)
    474         if self.optimizer == "fmin_l_bfgs_b":
    475             theta_opt, func_min, convergence_dict = \
--> 476                 fmin_l_bfgs_b(obj_func, initial_theta, bounds=bounds)
    477             if convergence_dict["warnflag"] != 0:
    478                 warnings.warn("fmin_l_bfgs_b terminated abnormally with the "

e:\Anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py in fmin_l_bfgs_b(func, x0, fprime, args, approx_grad, bounds, m, factr, pgtol, epsilon, iprint, maxfun, maxiter, disp, callback, maxls)
    197 
    198     res = _minimize_lbfgsb(fun, x0, args=args, jac=jac, bounds=bounds,
--> 199                            **opts)
    200     d = {'grad': res['jac'],
    201          'task': res['message'],

e:\Anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, **unknown_options)
    333             # until the completion of the current minimization iteration.
    334             # Overwrite f and g:
--> 335             f, g = func_and_grad(x)
    336         elif task_str.startswith(b'NEW_X'):
    337             # new iteration

e:\Anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py in func_and_grad(x)
    283     else:
    284         def func_and_grad(x):
--> 285             f = fun(x, *args)
    286             g = jac(x, *args)
    287             return f, g

e:\Anaconda3\lib\site-packages\scipy\optimize\optimize.py in function_wrapper(*wrapper_args)
    298     def function_wrapper(*wrapper_args):
    299         ncalls[0] += 1
--> 300         return function(*(wrapper_args + args))
    301 
    302     return ncalls, function_wrapper

e:\Anaconda3\lib\site-packages\scipy\optimize\optimize.py in __call__(self, x, *args)
     61     def __call__(self, x, *args):
     62         self.x = numpy.asarray(x).copy()
---> 63         fg = self.fun(x, *args)
     64         self.jac = fg[1]
     65         return fg[0]

~\AppData\Roaming\Python\Python36\site-packages\sklearn\gaussian_process\gpr.py in obj_func(theta, eval_gradient)
    222                 if eval_gradient:
    223                     lml, grad = self.log_marginal_likelihood(
--> 224                         theta, eval_gradient=True)
    225                     return -lml, -grad
    226                 else:

~\AppData\Roaming\Python\Python36\site-packages\sklearn\gaussian_process\gpr.py in log_marginal_likelihood(self, theta, eval_gradient)
    432 
    433         if eval_gradient:
--> 434             K, K_gradient = kernel(self.X_train_, eval_gradient=True)
    435         else:
    436             K = kernel(self.X_train_)

~\AppData\Roaming\Python\Python36\site-packages\sklearn\gaussian_process\kernels.py in __call__(self, X, Y, eval_gradient)
    688         """
    689         if eval_gradient:
--> 690             K1, K1_gradient = self.k1(X, Y, eval_gradient=True)
    691             K2, K2_gradient = self.k2(X, Y, eval_gradient=True)
    692             return K1 + K2, np.dstack((K1_gradient, K2_gradient))

~\AppData\Roaming\Python\Python36\site-packages\sklearn\gaussian_process\kernels.py in __call__(self, X, Y, eval_gradient)
    763         if eval_gradient:
    764             K1, K1_gradient = self.k1(X, Y, eval_gradient=True)
--> 765             K2, K2_gradient = self.k2(X, Y, eval_gradient=True)
    766             return K1 * K2, np.dstack((K1_gradient * K2[:, :, np.newaxis],
    767                                        K2_gradient * K1[:, :, np.newaxis]))

e:\Anaconda3\lib\site-packages\skopt\learning\gaussian_process\kernels.py in __call__(self, X, Y, eval_gradient)
    389             raise ValueError(
    390                 "Expected X to have %d features, got %d" %
--> 391                 (X.shape, len(length_scale)))
    392 
    393         n_samples, n_dim = X.shape

TypeError: %d format: a number is required, not tuple

Thank you for your help

**Comment by iaroslav-ai** [comment]
Hi @developpeur-windev-php-python ,
you get an exception because you specify parameters of dimensions similar to `GridSearchCV`, where you provide a list of values for a dimension. In `skopt`, you need to provide a dimension interval / feasible values instead; So in your case it would be `Real(1e-4, 1e+4, 'log-uniform')`. See here more:

https://github.com/scikit-optimize/scikit-optimize/blob/master/examples/sklearn-gridsearchcv-replacement.ipynb

Feel free to reopen / comment if you still have issues.
