### ISSUE TITLE
Plot a learning curve from a skopt/BayesSearchCV search is not working

### ISSUE THREAD

**Issue by CBrauer** [scikit-optimize/scikit-optimize#751]
I'm having trouble plotting a learning curve from a skopt optimization. Here is what I tried:

```
from matplotlib import pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

from skopt.space import Real, Integer, Categorical
from skopt import BayesSearchCV
from skopt.plots import plot_convergence

rf = RandomForestRegressor(random_state =7, n_jobs=4)

def RunSKOpt():  
    hyper_parameters =  {"n_estimators":      (5, 500),
                         "max_depth":         Categorical([3, None]),
                         "min_samples_split": (2, 10),
                         "min_samples_leaf":  (1, 10)
                        }

    search = BayesSearchCV(rf,
                           hyper_parameters,
                           n_iter = 5,
                           n_jobs = 4,
                           cv = 10,
                           verbose = 1,
                           return_train_score = True
    )
    return search

X, y = load_iris(True)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, random_state=0)
search = RunSKOpt()
search.fit(X_train, y_train)

plot_convergence(search)
plt.show()
```

The convergence plot is empty.

Charles

**Comment by stefanocereda** [comment]
plot_convergence works on the results of gp_minimize (and similar), not on BayesSearchCV.
It's easier if you rewrite your code to use gp_minimize if you want that plot.
Moreover, BayesSearchCV lets you conduct a parallel search, I wouldn't be sure on how to plot its convergence.

**Comment by iaroslav-ai** [comment]
Hi @CBrauer, @stefanocereda  is right - `BayesSearchCV` was not intended for convergence plotting. You could however use the `cv_results_` property of the *SearchCV, convert it to pandas (should be just creating dataframe out of the `cv_results_` property) and then visualizing estimator performances for different iterations. The property is similar to those of GridSearchCV:
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

**Comment by iaroslav-ai** [comment]
I close this for now, but if a proposed option does not work, feel free to reopen!
