### ISSUE TITLE
New release of skopt ?

### ISSUE THREAD

**Issue by alois-bissuel** [scikit-optimize/scikit-optimize#754]
Hi,

It's been more than a year since skopt has not been released, and I am especilly interested in getting the commits from #668 without needing to package skopt locally.
I do not know whether all the additions to skopt since the last release are sufficient enough to warrant a new release.

Cheers,

**Comment by iaroslav-ai** [comment]
Hi @alois-bissuel,
indeed, it would be good to make a new revision! I am on it now.

**Comment by iaroslav-ai** [comment]
This is not done yet - there seem to be an issue with automated deployment to PyPI. Will investigate over next few days.

**Comment by alois-bissuel** [comment]
Thanks!

**Comment by alois-bissuel** [comment]
Any news on this ?

**Comment by swayson** [comment]
Also curious to know, what is the plan to get v0.6.0 on PyPi

**Comment by betatim** [comment]
Congratulations to @holgern for making this happen!!
