### ISSUE TITLE
name clash with scikits.optimization?

### ISSUE THREAD

**Issue by amueller** [scikit-optimize/scikit-optimize#76]
I'm not sure if the name is great because a scikits.optimization exists....

**Comment by MechCoder** [comment]
Is there any official process to get something registered as a scikit?

**Comment by glouppe** [comment]
Not sure what is the best way to go :s 

@mbrucher is in charge of `scikits.optimization`, maybe he has an opinion?

**Comment by mbrucher** [comment]
Is the objective of the scikit general purpose optimization (create "simple" conjugate optimizer for instance, Nelder Mead...) or specific algorithms?
It's true that I haven't had the time to work on the scikit for a while (understatement), but as I'm moving back to data science in fall, I may work on it and improve it as well.

**Comment by betatim** [comment]
Not sure I fully understand your question. There is `scipy.optimize`, `scikits.optimization` and `scikit-optimize` (this library). This library concerns it self with sequential model-based optimization (using a `scipy.optimize` like interface) -> finding the minimum of a noisy, expensive to evaluate, black-box function for which no gradients are available.

**Comment by betatim** [comment]
If you do revive `scikits.optimization` we should probably rename (at least one of the libraries).

**Comment by mbrucher** [comment]
So the library is more constrained than a general purpose optimization library.
I agree that the fact that you are using the same API could be a reason for keeping the optimize name. The fact that you are limiting yourself to a specific subset of global optimization routines would be a cause for you to change the library name if scikits.optimization is to be revived :/ Perhaps with a play on the algorithms you are implementing?

**Comment by MechCoder** [comment]
Here are some idea:

scikit-sqlearn (sequential learning)
scikit-sqopt (sequentail optimization)
scikit-blox (black box optimization)
scikit-hyperlearn
scikit-modopt

**Comment by MechCoder** [comment]
Also:

scikit-modelopt
scikit-seqlearn
scikit-seqopt

**Comment by betatim** [comment]
None of them get me really excited 😢 `scikit-minimize`? also not that great a name

**Comment by amueller** [comment]
why not ``scikit-smbo``? The method is called smbo after all, right?

**Comment by MechCoder** [comment]
Cmon @amueller Naming a library after what it does? Said no developer ever

**Comment by betatim** [comment]
`scikit-simba` or `scikit-samba` because it sounds nearly like SMBO but is pronounceable. With this: bon weekenk :)

**Comment by MechCoder** [comment]
scikit-simba sounds ok to me. (With a snake around a lion as logo ;) )

**Comment by betatim** [comment]
<img src="https://media.giphy.com/media/zkSFsZpQMZuG4/giphy.gif" />

**Comment by raghavrv** [comment]
+simba for `scikit-simba` :P

**Comment by betatim** [comment]
For now we will keep the name as we can't really find a good alternative. I think there isn't a huge potential for confusion. If `scikits.optimization` becomes more actively maintained again we re-open this issue. This isn't to silence anyone, just don't want to get stuck in the "forever pondering" loop.
