### ISSUE TITLE
Class Optimizer does not have x0 argument

### ISSUE THREAD

**Issue by yangju2011** [scikit-optimize/scikit-optimize#761]
Although gp_minimize has 'x0', 'y0' for warm start, the class Optimizer does not have 'x0' for warm start. 
When passing x0, receiving the following error
`__init__() got an unexpected keyword argument 'x0'`

**Comment by sqbl** [comment]
Dear yangju2011,

Instead of building prior knowledge in via x0, you can just do opt.tell(X,y) after building the optimizer. 

Best,
Søren

**Comment by yangju2011** [comment]
Oh I see. Thanks!
