### ISSUE TITLE
Bug report on BayesSearchCV

### ISSUE THREAD

**Issue by v-borges** [scikit-optimize/scikit-optimize#762]
Steps to reproduce: 
```
from skopt import BayesSearchCV
from sklearn.datasets import load_digits
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

X, y = load_digits(10, True)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, test_size=.25, random_state=0)

# log-uniform: understand as search over p = exp(x) by varying x
opt = BayesSearchCV(
    SVC(),
    {
        'C': (1e-6, 1e+6, 'log-uniform'),  
        'gamma': (1e-6, 1e+1, 'log-uniform'),
        'degree': (1, 8),  # integer valued parameter
        'kernel': ['linear', 'poly', 'rbf'],  # categorical parameter
    },
    n_iter=32,
    cv=3
)
```
got this error:
```
Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\skopt\searchcv.py", line 288, in __init__
    return_train_score=return_train_score)
TypeError: __init__() got an unexpected keyword argument 'fit_params'
```
Tested on linux and windows. Got same error.

Reason of the bug: `scikit-learn 0.21.0`
How to solve: `pip install scikit-learn==0.20.3`

**Comment by YannDubs** [comment]
I get the same error.

this is due to the depreciation of `self.fit_params` to the constructor of `BaseSearchCV` in scikit-learn 0.21.0 ( https://github.com/scikit-learn/scikit-learn/commit/#13519 ). 

A simple way to solve it is simply to remove `fit_params = fit_params` in `super(BayesSearchCV, self).__init__(...)` and add `self.fit_params = fit_params`. That's what I did for now.

Not sure if this is the best way to do (`skopt` might want to also remove `fit_params` to be consistent)  with sklearn), but it's a good way of using the latest version of scikit-learn.

@iaroslav-ai might be worth solving this before putting v0.6 on pip.

**Comment by LaymounaLhoulwa** [comment]
HEllo @YannDubs , I use colab google and I have the same problem.  But I can't edit  SearchCV file for applying your solution. It is available just for read-only. How Can I make the modification??

**Comment by underscrew** [comment]
@LaymounaLhoulwa , you can import and override class methods by inheritance, like [this](https://www.tutorialspoint.com/How-to-override-class-methods-in-Python)

**Comment by LaymounaLhoulwa** [comment]
thanks a lot @escherba for your reply, It is helpful

**Comment by darenr** [comment]
any progress on fixing this to make `scikit-optimize` compatible with the latest `scikit-learn`?

**Comment by escherba** [comment]
@darenr I presume we are waiting for this: https://github.com/scikit-optimize/scikit-optimize/pull/772

**Comment by dmvieira** [comment]
But you should restrict version of sklearn to scikit-learn==0.20.3 waiting for sklearn fix

**Comment by Gonzalo933** [comment]
Is there an ETA for this issue? the PR seems ready to merge

**Comment by PaulConyngham** [comment]
> @darenr I presume we are waiting for this: #772

please affecting us here too

**Comment by darenr** [comment]
I forked the project, fixed this issue and cherry picked some upstream pull
requests too

https://github.com/darenr/scikit-optimize

I'll continue to pull in any upstream changes that improve this project.

**Comment by exiledtothetropics** [comment]
Hi, I am experiencing a similar problem. 

- Am working in an Ubuntu environment 
- `scikit-learn==0.20.3`
- `-e git://github.com/YannDubs/scikit-optimize.git@d8a5aefe7d472b7c7b929ef9135d71a263af7717#egg=scikit_optimize`

The last two bullet points are based on the discussion above. Thoughts on how to handle this problem?

**Comment by oli5679** [comment]
I'm also experiencing this bug!

**Comment by XT-Tahoe** [comment]
> I get the same error.
> 
> this is due to the depreciation of `self.fit_params` to the constructor of `BaseSearchCV` in scikit-learn 0.21.0 ( https://github.com/scikit-learn/scikit-learn/commit/#13519 ).
> 
> A simple way to solve it is simply to remove `fit_params = fit_params` in `super(BayesSearchCV, self).__init__(...)` and add `self.fit_params = fit_params`. That's what I did for now, if you're just doing a few tests you can use my fork for now (only changed this problem): `pip install -e git://github.com/YannDubs/scikit-optimize.git#egg=scikit-optimize` (and then uninstall it once this is solved on the main branch, as mine will not be updated).
> 
> Not sure if this is the best way to do (`skopt` might want to also remove `fit_params` to be consistent) with sklearn), but it's a good way of using the latest version of scikit-learn.
> 
> @iaroslav-ai might be worth solving this before putting v0.6 on pip (+ it's only 2 lines to change).



> I get the same error.
> 
> this is due to the depreciation of `self.fit_params` to the constructor of `BaseSearchCV` in scikit-learn 0.21.0 ( https://github.com/scikit-learn/scikit-learn/commit/#13519 ).
> 
> A simple way to solve it is simply to remove `fit_params = fit_params` in `super(BayesSearchCV, self).__init__(...)` and add `self.fit_params = fit_params`. That's what I did for now, if you're just doing a few tests you can use my fork for now (only changed this problem): `pip install -e git://github.com/YannDubs/scikit-optimize.git#egg=scikit-optimize` (and then uninstall it once this is solved on the main branch, as mine will not be updated).
> 
> Not sure if this is the best way to do (`skopt` might want to also remove `fit_params` to be consistent) with sklearn), but it's a good way of using the latest version of scikit-learn.
> 
> @iaroslav-ai might be worth solving this before putting v0.6 on pip (+ it's only 2 lines to change).

what files should be modified?

**Comment by zoj613** [comment]
So whats the verdict regarding this issue. I see there are some active PR that seem to have fixed the bug. Are there any plans to release a new version or at least merge the fixes on the master branch?

**Comment by oli5679** [comment]
Use https://github.com/darenr/scikit-optimize for a fork incorporating the simple fix to this bug. 

conda uninstall scikit-optimize OR pip uninstall scikit-optimize
git clone https://github.com/darenr/scikit-optimize
cd scikit-optimize
pip install .

**Comment by zoj613** [comment]
> Use https://github.com/darenr/scikit-optimize for a fork incorporating the simple fix to this bug.
> 
> conda uninstall scikit-optimize OR pip uninstall scikit-optimize
> git clone https://github.com/darenr/scikit-optimize
> cd scikit-optimize
> pip install .

I'm already using that fork. I am however curious about why it is taking long to merge the fix to the main repo. Has the author abandoned this project?

**Comment by oli5679** [comment]
> > Use https://github.com/darenr/scikit-optimize for a fork incorporating the simple fix to this bug.
> > conda uninstall scikit-optimize OR pip uninstall scikit-optimize
> > git clone https://github.com/darenr/scikit-optimize
> > cd scikit-optimize
> > pip install .
> 
> I'm already using that fork. I am however curious about why it is taking long to merge the fix to the main repo. Has the author abandoned this project?

I'm also worried that this project might be abandoned.

@iaroslav-ai, thanks for creating such a useful tool. Is this actively maintained by anyone? If not, would it be possible to give @darenr merge permissions?

**Comment by glouppe** [comment]
Hi! This project is indeed no longer maintained unfortunately. We are looking for people to take over.

**Comment by dmvieira** [comment]
For this issue:
`pip install git+https://github.com/darenr/scikit-optimize`

@glouppe I'm volunteer

**Comment by oli5679** [comment]
@glouppe I'm also happy to volunteer.

> Hi! This project is indeed no longer maintained unfortunately. We are looking for people to take over.

**Comment by zoj613** [comment]
> Hi! This project is indeed no longer maintained unfortunately. We are looking for people to take over.

I'd be happy to volunteer too.

**Comment by SimonHStats** [comment]
Would be good to see if we can get Conda forge to point at the fixed version really.

**Comment by sousablde** [comment]
Hello I've tried some of the solutions proposed here but I am still getting the error related to fit_params.
I am using scikit-learn 0.21.0

**Comment by ogencoglu** [comment]
Any updates on this?
