### ISSUE TITLE
Warm starting vs. pickling

### ISSUE THREAD

**Issue by smdubarry** [scikit-optimize/scikit-optimize#766]
I am using ask and tell to optimize a simulation which takes days to run in parallel batches of 3. Is there any significant difference between the following two workflows?

1. Every time I have new evaluations to add, just create a new Optimizer, tell all the existing evaluations, and ask for 3 new points.

2. Create the Optimizer once. Every time I have new evaluations to add, restore the pickled Optimizer, tell the new evaluations, ask for 3 new points, and pickle the Optimizer again.

**Comment by felipeportella** [comment]
Hi @smdubarry, in terms of results both approaches are equal, but in terms of performance (2) is better. Notice that the tell method is costly, so doing it again and again in approach (1) will make you waste time if you can use the built-in methods [dump](https://scikit-optimize.github.io/#skopt.dump) and [load](https://scikit-optimize.github.io/#skopt.load) to archive the proposed in (2). 

I did a quick comparation of 1 vs 2 after 50 samples in a problem I'm working on:

_Approach (1):_
```
Generating CSV file = 0:00:00.005922
```
+
```
Updating skopt from the CSV file = 0:00:46.702515                                                                                                             
[51] (2019-05-27 18:09:24) [-13.7098, -3.1763] => 3653438.444755996
```

_Approach (2):_
```
skopt.dump = 0:00:00.259374
```
+
```
skopt.load = 0:00:00.107910
[51] (2019-05-27 18:16:59) [-13.7098, -3.1763] => 3653438.4447477306
```

Note that the points sampled were the same in both cases  [-13.7098, -3.1763] but took me 46 seconds less with dump+load :)
