### ISSUE TITLE
reference citations

### ISSUE THREAD

**Issue by jiayeah9508** [scikit-optimize/scikit-optimize#775]
hello!
I want to use skopt to find a optimal combination of hyperparameters in my project and cite it in a paper, but I can not determine how many iterations should  I set（for SVM，RF，LR... I  used 50 times for any classifer..），if there is not some good ways to determine it(if you know the way, please feel free to give me your advice!) , I want to take a leaf out of other people's paper , so I wonder if any papers use this library, thank you very much!

**Comment by jonnor** [comment]
50 iterations sounds reasonable for a small number of hyperparameters. To verify that 50 iters is enough, plot the performance on your fitness function, and see that it converges in all cases. It makes sense to use the same for all classifiers (to give them the same chance).
