### ISSUE TITLE
Skopt fails on Keras tuning

### ISSUE THREAD

**Issue by Koranten** [scikit-optimize/scikit-optimize#778]
I am having an issue with Scikit Optimize.

I am using it to optimize a Keras neural network.

I'm not using BayesSearchCV, just gp/forest/gbrt_minimize.

Everything runs but Skopt fails to perform better than a simple grid search because sometimes Keras fails and produce a huge error. 

I think this is an initialization problem, sometimes Keras does just that, but it does that quite often so Skopt (be it gp minimize, forest minimize or gprt minimize) is 'confused' because of this huge error : for a given set of parameters, Keras SHOULD have a low error, but sometimes as I say, it doesn't. 

(If we could re-launch Keras with the same parameters but a different initialization, it would work and give a small error as expected.) 

But of course Skopt doesn't 'know' that, so it assumes this parameter set is just not good so it goes to look elsewhere.

Skopt ends up with a surrogate model of the error that doesn't make any sense so it cannot find its way do the optimum.

I'm quite sure of it because I monitor the error as a function of the parameters, and I can see that maybe 20% of the time this problem arises. When I delete these points set from the database and run a machine learning model on this 'cleaned' database, I can build a reliable surrogate model of the error.. When I keep these points it's not possible to build a reliable surrogate model so I'm pretty sure that's why Skopt fails.

So I'm stuck because I can't find a way to 'tell' Skopt to just dismiss these points. 

My question is then : is there a way to 'tell' Skopt to 'forget' a point for, say, any error over some threshold?

**Comment by chnzhangrui** [comment]
Hi,

In your particular case, it is worth to try ask-and-tell interface. There you start a loop of n_iter, and ask for a point, evaluate the point, and tell the result to the optimizer. So you have full control of whether you want to `tell` the result or not. But be sure not stuck in an infinite loop - if you don't update the optimizer, it probably will always predict the same point.
