### ISSUE TITLE
Add scikit-learn compatible BayesSearchCV

### ISSUE THREAD

**Issue by amueller** [scikit-optimize/scikit-optimize#78]
Hey.
Do you intent to provide a GridSearchCV plug-in replacement or only the optimizer?
The thing is that it might take a while to get that into scikit-learn, and it would be nice if people had access to it.

Cheers,
Andy

**Comment by glouppe** [comment]
Would be a nice thing to have indeed! There is already a rudimentary example at https://github.com/scikit-optimize/scikit-optimize/blob/master/examples/plot_random_vs_gp.py but it would be even better to wrap to into a `BayesSearchCV` object.

**Comment by betatim** [comment]
We should take inspiration from the discussion and design in scikit-learn/scikit-learn#5491

**Comment by betatim** [comment]
http://arxiv.org/abs/1603.06560 via http://www.argmin.net/2016/06/20/hypertuning/ so we just wrap `dummy_minimize`? IMHO we should do some benchmarking 📊 😀

**Comment by glouppe** [comment]
Random search for parameters is already in scikit-learn :)

**Comment by betatim** [comment]
I was practicing my sarcasm, before it becomes illegal after the 🇬🇧  votes to leave 💶  (really money is the only euro symbol we have? 😢)

**Comment by betatim** [comment]
On a more serious note, reading the blog a bit more carefully I think what they found is that if you can run twice as many points when doing random sampling then that beats BO. Slightly 🍎 to 🍑  comparison.

**Comment by amueller** [comment]
Why do you think so? It is just trying to put some perspective into what the baseline of hyperparameter search should be.
I think "how much better than random is state of the art smbo?" is a good question, and the answer is that it is between 1x and 2x faster, but in no setting they looked at was it more than 2x faster.

**Comment by betatim** [comment]
I think it is an interesting investigation for sure. The way the paper is phrased it comes across a bit dismissive of BO. The advice "evaluate your expensive functions twice as often and you will get a better result" is a bit impractical if your function is expensive to evaluate which is presumably why you are bothering with something complex like BO. That is all.

**Comment by glouppe** [comment]
#112 demonstrates how to use `skopt` for hyper-parameter optimisation. 

Might still be worth also providing something like a `SkoptSearchCV` object though, behaving like an actual scikit-learn estimator.

**Comment by glouppe** [comment]
Bumping this. Having a `SkoptSearchCV` would be nice.

**Comment by betatim** [comment]
Not sure about the name, but otherwise like the idea!

**Comment by iaroslav-ai** [comment]
Was just about to open an issue, but found this :)
Is anyone working on this issue? I have a working draft implementation of `SkoptSearchCV` in one of my forks, which extends `BaseSearchCV` and behaves kinda like `RandomizedSearchCV`. I could create a pull request over next days if no one is working on this. Seems like a cool thing to have around.

**Comment by glouppe** [comment]
Please do :)

**Comment by iaroslav-ai** [comment]
Ok then :) Will review the code once again and open a PR somewhere close to the weekends.

**Comment by glouppe** [comment]
Done!
