### ISSUE TITLE
[Feature request] Allow choosing the acq_function during ask().

### ISSUE THREAD

**Issue by thomasahle** [scikit-optimize/scikit-optimize#787]
Currently, skopt requires the acquisition function and parameters to be given as an `Optimizer` object is created. However, it would be nice if this was specifiable for each `opt.ask()` call.

In particular, I'd like to use LCB with different kappa values to output a final table over the best points. I might also like to use acq-optimizer=samplilng with a large n_points once in a while to output "best so far" stats.

**Comment by holgern** [comment]
Can be done now with the new `update_next` function, will be included in release 0.7.2

```
acq_func_kwargs = {"kappa": 0}
opt = Optimizer([(-2.0, 2.0)], "GP", n_initial_points=1,
                acq_func="LCB", acq_optimizer="sampling",
                acq_func_kwargs=acq_func_kwargs)
opt.run(objective, n_iter=20)

acq_func_kwargs = {"kappa": 100000}
opt.acq_func_kwargs = acq_func_kwargs
opt.update_next()
opt.run(objective, n_iter=20)
```
