### ISSUE TITLE
No support for plot_objective using Classifier class

### ISSUE THREAD

**Issue by tordbb** [scikit-optimize/scikit-optimize#789]
I can't seem to use the functions plot_objective or plot_evaluations for results retrieved using the Optimizer class. This is sad, because this class is the best way I have found to optimize both the ML model structure, the preprocessing routines and other settings in the same process. And visualization would be very insightful.

Error message:
> AttributeError: 'Optimizer' object has no attribute 'x_iters'

Code example:
```
def test_plot():
    space = [skopt.space.Integer(2, 300, name='first_parameter'),
             skopt.space.Integer(2, 100, name='second_parameter')]

    opt = skopt.Optimizer(space, "GP", acq_optimizer="sampling")

    for i in range(10):
        # Ask optimiser for settings to try
        settings = opt.ask()

        score = settings[0] + settings[1]
        opt.tell(settings, -score)

    plot_objective(opt)
    plot_evaluations(opt)

if __name__ == "__main__":
    test_plot()
```

**Comment by sqbl** [comment]
Hi tordbb,

You have to store the last opt.tell(setting,score) in a variable. And then call that variable in the plot_objective().

Like:
result = opt.tell(settings[-1], score[-1])
plot_objective(result, dimensions=['first_parameter', 'second_parameter'])

Hope it helps

**Comment by tordbb** [comment]
Thank you so much, sqbl!

I had to tweak a little more to make the plots show in pyCharm, but now it all works. Here is the complete, working code:

```
import random
import skopt
from skopt import plots
from matplotlib import pyplot as plt


def test_plot():
    space = [skopt.space.Integer(2, 300, name='param1'),
             skopt.space.Integer(2, 100, name='param2')]

    opt = skopt.Optimizer(space, "GP", acq_optimizer="sampling")

    for i in range(10):
        # Ask optimiser for settings to try
        settings = opt.ask()

        score = random.random()
        res = opt.tell(settings, -score)

    plots.plot_objective(res, dimensions=['param1', 'param2'])
    plots.plot_evaluations(res, dimensions=['param1', 'param2'])
    plt.show()


if __name__ == "__main__":
    test_plot()
```
