### ISSUE TITLE
ask for help!(TypeError:__init__() got an unexpected keyword argument 'fit_params')

### ISSUE THREAD

**Issue by XT-Tahoe** [scikit-optimize/scikit-optimize#792]
from skopt import BayesSearchCV
from sklearn.datasets import load_digits
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

X, y = load_digits(10, True)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, test_size=.25, random_state=0)

# log-uniform: understand as search over p = exp(x) by varying x
opt = BayesSearchCV(
    SVC(),
    {
        'C': (1e-6, 1e+6, 'log-uniform'),  
        'gamma': (1e-6, 1e+1, 'log-uniform'),
        'degree': (1, 8),  # integer valued parameter
        'kernel': ['linear', 'poly', 'rbf'],  # categorical parameter
    },
    n_iter=32,
    cv=3
)

opt.fit(X_train, y_train)

print("val. score: %s" % opt.best_score_)
print("test score: %s" % opt.score(X_test, y_test))

TypeError:__init__() got an unexpected keyword argument 'fit_params. Please teach me how to solve the problem?

**Comment by zoj613** [comment]
I get the same error when I try to use BayesSearch

**Comment by XT-Tahoe** [comment]
That’s the version problem. It’s easy to solve.&nbsp;



发自我的iPhone


------------------ Original ------------------

**Comment by wud666** [comment]
I've found this is a problem with sklearn 0.21+, But I dont know how to solve it, Anyone could help?

**Comment by zoj613** [comment]
> I've found this is a problem with sklearn 0.21+, But I dont know how to solve it, Anyone could help?

https://github.com/scikit-optimize/scikit-optimize/issues/762#issuecomment-542621818

**Comment by betatim** [comment]
Closed by #777
