### ISSUE TITLE
setting n_jobs has no effect

### ISSUE THREAD

**Issue by montanier** [scikit-optimize/scikit-optimize#793]
Hello,

I'm trying to parallelize my evaluations without success so far. Here is a minimal code illustrating my problem:
```python
import numpy as np
from skopt import gp_minimize
import time

def f(x):
    return (np.sin(5 * x[0]) * (1 - np.tanh(x[0] ** 2)) *
            np.random.randn() * 0.1)

start = time.time()
res = gp_minimize(f, 
                  [(-2.0, 2.0)], 
                  acq_optimizer = 'lbfgs',
                  n_jobs=1)
end = time.time()
print(f'1 job ran for {end-start}')

start = time.time()
res = gp_minimize(f, 
                  [(-2.0, 2.0)], 
                  acq_optimizer = 'lbfgs',
                  n_jobs=-1)
end = time.time()
print(f'n jobs ran for {end-start}')
```

On my local computer I get the following result:
```bash
1 job ran for 41.537992000579834
n jobs ran for 40.21194672584534
```

On a Standard NC6 instance on azure I get:
```bash
1 job ran for 40.63985991477966
n jobs ran for 50.71987843513489
```

I was expecting to see a reduced running time by setting n_jobs to -1.

Trying to add a ```time.sleep(1)``` in the method f(x) so as to simulate some work getting done leads me to similar results.
```bash
1 job ran for 139.99551463127136
n jobs ran for 143.19317412376404
```

I guess I am missing something. Could someone point me to the correct set of parameters to parallelize the evaluation ?

Thanks,
Jean-Marc

**Comment by montanier** [comment]
Yes by default `acq_optimizer` is set to `lbfgs`. I had also made test by specifying it (just to be sure), but with the same result.

Anyway, since the repo is not maintained, there is no real point to keep this issue open. 

Thanks :)

**Comment by kylegilde** [comment]
Are there any plans to parallelize the objective function's n_initial_points?
