### ISSUE TITLE
plot_results returns keyeror

### ISSUE THREAD

**Issue by romanovzky** [scikit-optimize/scikit-optimize#794]
Hi there,
I have results over a space composed of three integer and one categorical variables, using `gbrt_minimize`. When using the `plot_objective` function I get
```python
KeyError: 0.02564102564102564
```
I suspect this is due to the categorical variable, as I had run the same optimization previously without the categorical variable and had no problems.
Is this a known bug?

**Comment by chnzhangrui** [comment]
Hi, as far as I know, `plot_objective` doesn't support categorical variables as the gradient is not calculable. You will have to hack the `plot.py` code and convert categorical variables into integers to plot.

**Comment by romanovzky** [comment]
Indeed! Thanks!
