### ISSUE TITLE
Ask for help  TypeError: __init__() got an unexpected keyword argument 'whitelist'  [Program finished]

### ISSUE THREAD

**Issue by janat237** [scikit-optimize/scikit-optimize#795]
I've started to use instabot with this code
`   from instabot import Bot
bot = Bot(
            proxy=None,
            max_likes_per_day=1000,
            max_unlikes_per_day=1000,
            max_follows_per_day=350,
            max_unfollows_per_day=350,
            max_comments_per_day=100,
            max_likes_to_like=100,
            max_followers_to_follow=2000,
            min_followers_to_follow=10,
            max_following_to_follow=10000,
            min_following_to_follow=10,
            max_followers_to_following_ratio=10,
            max_following_to_followers_ratio=2,
            min_media_count_to_follow=3,
            like_delay=10,
            unlike_delay=10,
            follow_delay=30,
            unfollow_delay=30,
            comment_delay=60,
            whitelist=False,
            blacklist=False,
            comments_file=False,
            stop_words=['shop', 'store', 'free']
)      `

And it didn't work gave this erorr
`  Traceback (most recent call last):
  File "/data/data/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/data/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 25, in <module>
TypeError: __init__() got an unexpected keyword argument 'whitelist'

[Program finished] `

How can I solve this problem

**Comment by chnzhangrui** [comment]
Hi,

I am not sure why this error is related to skopt?
