### ISSUE TITLE
Refactor minimize functions to make use of sampling API

### ISSUE THREAD

**Issue by glouppe** [scikit-optimize/scikit-optimize#81]
Now that #75 has been merged, we should refactor all `*_minimize` functions in order to make use of the new API.

We may need to make a few internal changes since `sample_points` return values in the original space, while we will need to feed the transformed values instead to the optimizer. 

I would expect something along the following lines:

1. Make `_check_grid` a public util returning the corresponding list of Distribution objects.
2. `sample_grid(grid, n_samples)`
3. `warp(grid, samples)`: from original to warped space
4. `unwarp(grid, samples)`: from warped to original sapce

**Comment by AlexanderFabisch** [comment]
The names `warp` and `unwarp` seem to be very generic. I think I would easily forget whether I want to use `warp` or `unwarp`. Maybe we can make it more explicit? Something like `optimizer_space_to_parameter_space`? Maybe we should come up with something shorter. :)

**Comment by MechCoder** [comment]
Maybe just `opt_to_param` and `param_to_opt` ?

**Comment by MechCoder** [comment]
What do we do when we don't want to transform some hyperparameters and don't want to transform others? (For instance, when the model can handle categorical parameters out of the box, for instance in https://github.com/scikit-optimize/scikit-optimize/pull/62). Provide a mask?

**Comment by glouppe** [comment]
Also, not sure we should care about nested grids for now. What do you think?

**Comment by MechCoder** [comment]
Sure. KISS ;)

**Comment by betatim** [comment]
How about `transform` and `inverse_transform` as alternative to `warp`/`unwarp`? Personally I like `warp` because it is short and there doesn't seem to be a good one word name for the parameter-space-used-by-the-optimiser (aka the warped one).

Could we leave it to the user to configure the parameter to use the `Identity` transform in the case where the optimiser natively supports it? An alternative could be that each optimiser provides its own `warp`/`unwarp` which knows to skip certain types?

**Comment by MechCoder** [comment]
+1 for `transform` and `inverse_transform`. I would be in favour of an explicit parameter (a mask) that tells us which parameters to warp and which to leave as is.

Any volunteers? :-)

**Comment by glouppe** [comment]
I'll try to have a go at the refactoring sometime this week.

**Comment by MechCoder** [comment]
Thanks!

**Comment by glouppe** [comment]
Done as part of #83
