### ISSUE TITLE
Add Gitter rooms and badge.

### ISSUE THREAD

**Issue by raghavrv** [scikit-optimize/scikit-optimize#82]
Add a gitter rooms -

- [ ] https://gitter.im/scikit-optimize/user (public room)
- [ ] https://gitter.im/scikit-optimize/dev (invite only, private room)
- [ ] A gitter badge to the user channel on README.md ;)

**Comment by betatim** [comment]
Do we need a private room?

And because I am feeling old: do we need a chat? Not sure what I think, just wanted to throw this out there because it seems number of comms channels always increase, a bit like the universe's entropy :)

**Comment by glouppe** [comment]
+0 for gitter.
-1 for a private chat room

**Comment by MechCoder** [comment]
Not sure, I've hardly used these.
