### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by ogencoglu** [scikit-optimize/scikit-optimize#824]
_BayesSearchCV example_ link seems to be broken in the documentation:

https://scikit-optimize.github.io/notebooks/hyperparameter-optimization.html

**Comment by holgern** [comment]
I'm working on a complete switch to sphinx, could you check
https://scikit-optimize.github.io/beta/html/
and report bugs, that would be great.

**Comment by holgern** [comment]
New documentation is live
