### ISSUE TITLE
Incompatibility with Python 2.7.x?

### ISSUE THREAD

**Issue by ardunn** [scikit-optimize/scikit-optimize#87]
I noticed that when run with 2.7.11, there is a syntax error:
```
in space.py
def __init__(self, *categories, prior=None):
SyntaxError: invalid syntax
```
The regular argument cannot come after the *argument. Simply reversing these parameters causes other issues in space.py
This seems to be in accordance with [this accepted Python enhancement proposal](https://www.python.org/dev/peps/pep-3102/).

Do the devs plan on making skopt compatible with 2.7.x?

**Comment by betatim** [comment]
Can you think of a way to make it work with the old versions of python without making the interface (much) more clunky to use?

The mantra we followed so far is to not try to break `python2.7` compatibility for the sake of it but also not make a particular effort to check we are compatible. The rational goes something like: this is a new project, py2.7 is on the way out, lots of useful features in python, and it is a considerable maintanance burden to have compatibility for both versions.

**Comment by glouppe** [comment]
Indeed, we have not made much efforts for compatibility with legacy Python. I guess the necessary changes are still minimal. Feel free to submit a pull request if you want to help us fix this :)

**Comment by glouppe** [comment]
> fixing this right now.

as you go along, you can probably replace in `.travis.yml` tests for 3.4 with tests for 2.7. Not sure why we are testing now for both 3.4 and 3.5...

**Comment by betatim** [comment]
@ardunn `python2` should work now and we decided to start testing against `python2.7` in our CI setup.
---
@glouppe @MechCoder does this mean we now officially support legacy python?

**Comment by ardunn** [comment]
@betatim That is great! Thank you!
