### ISSUE TITLE
Broken zenodo entry

### ISSUE THREAD

**Issue by holgern** [scikit-optimize/scikit-optimize#881]
As seen in https://zenodo.org/record/1207017, the newest releases are not available in zenodo.

**Comment by holgern** [comment]
https://github.com/zenodo/zenodo/issues/1948
The issue is caused by an outdated github token

**Comment by holgern** [comment]
@glouppe Could you go to https://zenodo.org/record/1207017 and fix the stucked indexing? There seems to have lost the API key, you need to reenable the repo. I'm not allowed to do this:

![image](https://user-images.githubusercontent.com/2202263/92218119-ec974e00-ee98-11ea-907a-ec76f1b25bfc.png)

**Comment by glouppe** [comment]
I believe this is now fixed. See https://zenodo.org/record/4014775 which correctly updated to 0.8.1.
