### ISSUE TITLE
python crashes due to KERNELBASE.dll

### ISSUE THREAD

**Issue by GlennCeusters** [scikit-optimize/scikit-optimize#890]
Hi Guys,

My python environment crashes when trying to use skopt for hyper parameter tuning.

> Faulting application name: python.exe, version: 3.7.6150.1013, time stamp: 0x5e163a94
Faulting module name: KERNELBASE.dll, version: 10.0.17763.914, time stamp: 0xfb6790ac
Exception code: 0xe0000002
Fault offset: 0x0000000000039159
Faulting process id: 0x3d28
Faulting application start time: 0x01d5f7ae8e270e9e
Faulting application path: C:\Users\BEGLCEU\AppData\Local\Continuum\anaconda3\envs\gym\python.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 82bbace7-17ce-43ba-950e-f0f7cc80d55e

I've also attached the crash report.
Many thanks in advance for your replies!

Cheers,
/Glenn

[Report.txt](https://github.com/scikit-optimize/scikit-optimize/files/4318731/Report.txt)

**Comment by holgern** [comment]
Hi Glenn,
I do not think that skopt could case such crashes.

Take a look here:
https://github.com/ContinuumIO/anaconda-issues/issues/9518
Here, it was cased by an installed program: "NetWorx : bandwidth monitor"

**Comment by GlennCeusters** [comment]
Hi holgern,

You are right, I'm running the same python env and script in a clean windows environment (azure vm) and now everything seems fine.

Thanks for taking a look!

Cheers,
/Glenn

**Comment by GlennCeusters** [comment]
FYI, hereby the crash report from the clean win64.

[Report_clean_win64.txt](https://github.com/scikit-optimize/scikit-optimize/files/4323033/Report_clean_win64.txt)


Cheers,
/Glenn

**Comment by holgern** [comment]
Can you give me the version of your installed packages:
```
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import sklearn; print("Scikit-Learn", sklearn.__version__)
import skopt; print("Scikit-Optimize", skopt.__version__)
```
Can you give me also some more information about your setting?

**Comment by GlennCeusters** [comment]
I tracked it down to a tensorflow error.

> Iteration No: 1 started. Evaluating function at random point.
2020-03-12 09:39:42.714716: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-03-12 09:39:42.742958: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-03-12 09:39:42.751521: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2020-03-12 09:39:42.762318: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DekstopVM
2020-03-12 09:39:42.781263: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DekstopVM

**Comment by GlennCeusters** [comment]
> Can you give me the version of your installed packages:
> 
> ```
> import platform; print(platform.platform())
> import sys; print("Python", sys.version)
> import numpy; print("NumPy", numpy.__version__)
> import scipy; print("SciPy", scipy.__version__)
> import sklearn; print("Scikit-Learn", sklearn.__version__)
> import skopt; print("Scikit-Optimize", skopt.__version__)
> ```
> 
> Can you give me also some more information about your setting?

Windows-10-10.0.18362-SP0
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
NumPy 1.18.1
SciPy 1.4.1
Scikit-Learn 0.22.2.post1
Scikit-Optimize 0.7.4

**Comment by GlennCeusters** [comment]
my using the following search space:

```
     space = [Categorical([1, 2, 4, 8, 16, 32, 64], name='nminibatches'),
             Categorical([16, 32, 64, 128, 256, 512, 1024, 2048], name='n_steps'),
             Categorical([0.9, 0.95, 0.98, 0.99, 0.995, 0.999, 0.9999], name='gamma'),
             Real(1e-5, 1, name='learning_rate'),
             Real(0.00000001, 0.1, name='ent_coef'),
             Categorical([0.1, 0.2, 0.3, 0.4], name='cliprange'),
             Categorical([1, 5, 10, 20, 30, 50], name='noptepochs'),
             Categorical([0.8, 0.9, 0.92, 0.95, 0.98, 0.99, 1.0], name='lam')]
```

To tune a PPO2 algo from the stable-baseline.

```
@use_named_args(space)
    def objective(**model_params):
        """ Train the model and optimise
            maximises the negative log likelihood, so we
            need to negate the reward here
        """
        model = PPO2("MlpPolicy", env, verbose=0, **model_params)
        model.learn(50000)

        rewards = []
        n_episodes, reward_sum = 0, 0.0

        obs = eval_env.reset()
        while n_episodes < 1:
            action, _ = model.predict(obs)
            obs, reward, done, _ = eval_env.step(action)
            reward_sum += reward

            if done:
                rewards.append(reward_sum)
                reward_sum = 0.0
                n_episodes += 1
                obs = eval_env.reset()

        last_reward = np.mean(rewards)
        
        return -1 * last_reward
```

**Comment by GlennCeusters** [comment]
Argh, found it. The `n_steps` should be dividable by `nminibatches`.
