### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'log10'

### ISSUE THREAD

**Issue by karahbit** [scikit-optimize/scikit-optimize#897]
Hello,

I used to use 
```
scikit-optimize 0.5.2
```
and it worked fine.

Today, I tried my same experiment but using 
```
scikit-optimize 0.7.4
```
and I am having the following error:
```
File "/home/karahbit/ve-radical.hpo/lib/python3.6/site-packages/skopt/space/space.py", line 234, in __init__
    self.log_base = np.log10(base)
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable log10 method
AttributeError: 'NoneType' object has no attribute 'log10'
```

If I go back to 0.5.2, it stills works fine. Any ideas? Thanks!

**Comment by holgern** [comment]
Can you post your used spaces?

**Comment by karahbit** [comment]
The problem was on my end and I found out how to fix it already. I can’t eliminate this issue, so please close it and I apologize for the inconvenience.
