### ISSUE TITLE
ImportError: cannot import name 'MaskedArray' from 'sklearn.utils.fixes'

### ISSUE THREAD

**Issue by hnikana** [scikit-optimize/scikit-optimize#905]
since in the latest version of sklearn 0.23.0 the MaskedArray from sklearn/utils/fixes.py has been depreciated this error occurs , however I manually added that to my fixes.py function and it worked

**Comment by betatim** [comment]
Duplicate of https://github.com/scikit-optimize/scikit-optimize/issues/902 so closing for now.

Please take a look at existing issues and Pull Requests before opening new ones.
