### ISSUE TITLE
ExtraTrees returns NaN for std

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#92]
`yield (check_minimize, minimizer, bench1, 0., [(-2.0, 2.0)], 0.05, 75)` with `et_minimize` produces

```
scikit-optimize/skopt/acquisition.py:165: RuntimeWarning: invalid value encountered in greater
  mask = std > 0
```

and `std` is:
```
(Pdb) print(std)
[  0.00000000e+00   3.44874701e-01   4.35236492e-01              nan
   5.35666028e-01   3.76289149e-01   0.00000000e+00   3.44874701e-01
   3.03596891e-01   2.84929167e-01              nan              nan
   1.11601649e-01   3.44874701e-01              nan              nan
   2.98023224e-08   6.69582536e-01   1.68631973e-01              nan]
```

**Comment by glouppe** [comment]
Hmm good point, we should check these border cases.

**Comment by betatim** [comment]
For future debuggers: this is with `ETRegressor()` no special hp settings.

**Comment by glouppe** [comment]
In all our estimators, we should make sure that std=0.0 for all border cases (e.g. constant predictions), then deal properly with that in the acquisition functions.

**Comment by betatim** [comment]
I think so, at least haven't seen that warning anymore. Closing.
