### ISSUE TITLE
BayesSearchCV proposal time increases steadily over time

### ISSUE THREAD

**Issue by willjobs** [scikit-optimize/scikit-optimize#968]
See the plot below, which shows optimization of a scikit-learn DecisionTreeClassifier over four hyperparameters:

```
bayes_hyperparameters` = {
    'max_depth': Integer(25, 2000),
    'max_features': Categorical(['sqrt', 'log2']),
    'min_samples_split': Integer(2, 45),
    'min_samples_leaf': Integer(1, 100)
}

N_EVALS = 490  # except, we use DeltaYStopper for early stopping
```

I used a `TimerCallback` to track the total runtime, and extracted the mean_fit_time and mean_score_time from the cv_results_ dictionary. The "Bayes Update + Proposal" is the result of subtracting the (mean_fit_time * 5 + mean_score_time*5) from the `TimerCallback` times. [I multiplied the mean fit and score times by 5 due to 5-fold crossvalidation). The result is the graph below.

Is this expected? It seems like the update of the surrogate model and evaluation of the selection function (I used Expected Improvement) gets slower as more iterations happen.

![Figure 1](https://user-images.githubusercontent.com/7775919/98395798-c3c33e80-202a-11eb-80d5-48484cde4d29.png)

**Comment by xmatthias** [comment]
hi @willjobs,

are you able to provide a runnable (simple) sample which shows this?

I suspect this would facilitate having people investigate this issue further ...

**Comment by willjobs** [comment]
Thanks for following up, @xmatthias. After reading some literature, it turns out this is to be expected, at least for Gaussian processes (the default in scikit-optimize).

> "One downside of standard Gaussian processes is that they scale cubically in the number of data points, limiting their applicability when one can afford many function evaluations"
\- Hutter, F., Kotthoff, L. and Vanschoren, J., 2019. Automated machine learning: methods, systems, challenges. Springer Nature. [https://www.springer.com/gp/book/9783030053178](https://www.springer.com/gp/book/9783030053178)

So, this isn't actually a problem. I'll close the issue. Thanks again!
