### ISSUE TITLE
Define dimensions parameter when the objective function receives argument in NamedTuple format

### ISSUE THREAD

**Issue by imayachita** [scikit-optimize/scikit-optimize#983]
Hi there,

My objective function receives arguments in ```NamedTuple``` format. I can't change this because this is the requirement in the project I'm working on. I also want to pass a fixed hyperparameters set that I don't want to change. For example:
```
def objective(var_args, fixed_args):
    return var_args.foo * var_args.bar * fixed_args.foo1 * fixed_args.bar2
```

How can I define and pass the ```dimensions``` for ```Optimize``` and ```gp_minimize```?

Thank you

**Comment by kernc** [comment]
Opening a new issue is better than hijacking old, irrelevant issues, but please note, an issue tracker is not a discussion forum.

-----

You can wrap your `objective()` with another function that _wraps it_ and takes as input the structure scikit-optimize provides.
Such as:
```py
from collections import namedtuple

import skopt

ParamsTuple = namedtuple('ParamsTuple', ['foo', 'bar', 'foo1', 'bar2'])

dimensions = skopt.Space([skopt.space.Integer(...), ...])

@skopt.util.use_named_args(dimensions)
def my_objective(foo, bar, foo1, bar2):
    nt_params = ParamsTuple(foo, bar, foo1, bar2)
    assert hasattr(nt_params, 'foo')
    return objective(nt_params)
```
Look into [`skopt.utils.use_named_args`](https://scikit-optimize.github.io/stable/modules/generated/skopt.utils.use_named_args.html).

If you want to pass some parameters as fixed values, just exclude them from, or set them when instantiating `nt_params`.
Hth,
