### ISSUE TITLE
difference between scikit LHS and lhsdesign of matlab

### ISSUE THREAD

**Issue by giupardeb** [scikit-optimize/scikit-optimize#989]
Hi guys, I have a matlab's script that use [lhsdesign](https://it.mathworks.com/help/stats/lhsdesign.html) function. I would like convert my script matlab in python using LHS of sckit library and I would get the same results. But, if I setting the same seed in both the matlab script and the python script, I don't get the same result. Why? are there different implementations? Thanks!

**Comment by kernc** [comment]
[Our code](https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/sampler/lhs.py) is based on [pyDOE2's](https://github.com/clicumu/pyDOE2/blob/master/pyDOE2/doe_lhs.py) implementation. And [the source of randomness](https://numpy.org/doc/stable/reference/random/generator.html) (algorithm) also needs to be considered. It's not too surprising to get different results, even if our implementation happens to be correct.
We only cover it with a few tests that don't appear to be too strict:
https://github.com/scikit-optimize/scikit-optimize/blob/530da127c0e3d92fc5018115585e73fecced12a5/skopt/tests/test_sampler.py#L36-L107

**Comment by giupardeb** [comment]
Thank you @kernc for your explaination
