### ISSUE TITLE
from sklearn.ensemble.forest import RandomForestClassifier ModuleNotFoundError: No module named 'sklearn.ensemble.forest'

### ISSUE THREAD

**Issue by vishalediga8899** [scikit-optimize/scikit-optimize#993]
I am  getting error like this, can any body plz help

**Comment by kernc** [comment]
Try:
```py
from sklearn.ensemble import RandomForestClassifier
```
Is this supposed to be a bug in scikit-optimize? We don't import [`from sklearn.ensemble.forest`](https://github.com/scikit-optimize/scikit-optimize/search?q=%22sklearn.ensemble.forest%22&type=code) anywhere.

**Comment by vishalediga8899** [comment]
Brother it is again showing "in RanFor = pickle.load(f) ModuleNotFoundError: No module named 'sklearn.ensemble.forest'"
like this

**Comment by vishalediga8899** [comment]
@kernc :please help bro

**Comment by kernc** [comment]
Without seeing any code, you seem to be trying to unpickle a model from a prior, over a year old version of scikit-learn, which defined `RandomForestClassifier` still in _sklearn/ensemble/forest.py_.

Unfortunately, [scikit-learn's position](https://github.com/scikit-learn/scikit-learn/issues/16570#issuecomment-592195945) on the matter is:

> we don't support pickling/unpickling across different scikit-learn version

meaning you'll have to re-fit the model.
